/**
 * Sub-codex delegate surface for review-scoped one-shot turns.
 *
 * Port of the upstream codex review delegate machinery:
 *   - `codex-rs/core/src/codex_delegate.rs::run_codex_thread_one_shot`
 *     (lines 156-237) — the one-shot wrapper that spawns a child
 *     codex thread, submits a single `Op::UserInput`, and tears down
 *     on `TurnComplete` / `TurnAborted`.
 *   - `codex-rs/core/src/guardian/review_session.rs::build_guardian_review_session_config`
 *     (lines 831-897) — the helper that takes a parent `Config` +
 *     reviewer overrides and returns the review-scoped `Config` used
 *     by the delegate (review-model override, reviewer-prompt
 *     `base_instructions`, `approval_policy = Never`, `sandbox_policy
 *     = read_only`, cleared `mcp_servers`, disabled web/spawn
 *     features).
 *   - `codex-rs/core/src/tasks/review.rs::start_review_conversation`
 *     (lines 95-138) — the caller that assembles the sub-agent
 *     config, disables `web_search` + `view_image` + collab + spawn-csv,
 *     and hands the configured delegate a single user prompt.
 *
 * Translation conventions applied:
 *   - Rust `Arc<Session>` / `Arc<TurnContext>` → structural TS
 *     interfaces (`DelegateSessionLike`, `DelegateTurnContextLike`) so
 *     this module does not import the full `Session` / `TurnContext`
 *     types (avoids a cyclic dep with `session.ts` and keeps tests
 *     free of heavyweight fixtures).
 *   - Rust `CancellationToken` → `AbortController` per
 *     `docs/plan/translation-conventions.md`. The delegate accepts an
 *     `AbortSignal` and derives a child controller so shutdown can
 *     fire without touching the caller's signal.
 *   - Rust `async_channel::Sender<Op> + Receiver<Event>` bidirectional
 *     surface → a single `Promise<CodexThreadOneShotOutcome>` because
 *     gut has no child-Session spawn (see INCOMPLETE below). The
 *     upstream `Codex` handle's `rx_event` / `tx_sub` are RESERVED.
 *   - Rust `SubAgentSource::Review` → the string literal `"review"`;
 *     the full `SubAgentSource` enum is not ported because gut has no
 *     subagent-source routing to consume it.
 *
 * INCOMPLETE (flagged honestly per "no lying, no shortcuts"):
 *
 *   - Gut has no sub-Session spawn surface. Upstream `Codex::spawn`
 *     (`codex-rs/core/src/session/mod.rs`) constructs a separate
 *     `Session` with its own MCP manager, skills manager, thread
 *     store, rollout trace, analytics pipeline, and agent-control
 *     handle. Gut ships none of those shared services in a form that
 *     can be cloned into a child session (see
 *     `runtime/src/session/session.ts::SessionServices` — the
 *     services are live references to singletons, not cloneable
 *     factories). So the gut delegate runs the one-shot turn in a
 *     *flat* shape: a single bounded provider call using the parent
 *     session's `services.provider`, with the review-scoped
 *     `TurnContext` + reviewer-prompt system message inlined at the
 *     call site. The *semantics* match upstream's one-shot contract
 *     (single sampling iteration, teardown on completion/abort), but
 *     the delegate does not currently provide a separate child-Session
 *     for the reviewer turn. This RESERVED surface covers:
 *       - `Codex.rx_event` / `Codex.tx_sub` sub-agent I/O channels
 *         (`codex_delegate.rs:230-236`). Callers today receive only
 *         the synthesized `CodexThreadOneShotOutcome`.
 *       - Approval/permission forwarding inside `forward_events`
 *         (`codex_delegate.rs:239-386`). The gut delegate runs with
 *         `approval_policy = Never` and `sandbox_policy = read_only`
 *         (matching `build_guardian_review_session_config`), so the
 *         upstream approval-relay layer is not exercised by the
 *         single review prompt today.
 *       - `ThreadStore` / `RolloutTraceRecorder` / `analytics_events_client`
 *         cross-session propagation. Gut's review turn reuses the
 *         parent's rollout store and emits events through the parent
 *         session.
 *     When gut grows a real child-Session spawn (T11+), upgrading the
 *     delegate to spawn-then-submit-then-drain will not require
 *     changing the public `runOneShot` signature.
 *
 *   - `forward_events` approval routing (upstream codex
 *     `codex_delegate.rs:239-386`) is not ported. Because the gut
 *     delegate uses the parent's `session.services.provider` directly
 *     and the review-scoped `TurnContext` forces
 *     `approval_policy = never` + `sandbox_policy = read_only`, no
 *     approval events can be generated by the one-shot path. If a
 *     future refactor widens the review task to honor approvals, the
 *     approval-forwarding loop will need to land alongside the
 *     child-Session spawn.
 *
 *   - `ModelsManager` lookups. Upstream consults
 *     `services.models_manager.get_model_info` to resolve the
 *     reviewer model's capability bitmap. Gut's review-scoped
 *     TurnContext inherits the parent's `modelInfo` when the reviewer
 *     model is unchanged, and carries a lightweight override when
 *     the reviewer model differs. The full capability lookup is
 *     RESERVED for a later port.
 *
 * @module
 */

import type { LLMMessage, LLMProvider, LLMResponse } from "../llm/types.js";
import type {
  Config,
  ModelInfo,
  TurnContext,
} from "./turn-context.js";
import { buildTurnContext } from "./turn-context.js";
import type { Event, EventMsg } from "./event-log.js";
import type { ReviewOutput, ReviewRequest } from "./review.js";
import {
  REVIEW_SYSTEM_PROMPT,
  emptyReviewOutput,
  parseReviewOutput,
} from "./review.js";
import type { TaskKind } from "./tasks.js";

// ─────────────────────────────────────────────────────────────────────
// Structural dependencies (`DelegateSessionLike`, `DelegateTurnContextLike`)
//
// Upstream codex passes `Arc<Session>` + `Arc<TurnContext>`. Gut stays
// structural so tests can build minimal fixtures. The *minimum* a
// delegate needs is: a provider handle, an event emitter, and a task
// registrar. Everything else is an opt-in extension.
// ─────────────────────────────────────────────────────────────────────

/**
 * Emitter surface exposed by the parent session. Matches
 * `Session.emit` / `Session.sendEvent` (`session.ts:1380`,
 * `session.ts:1416`). The gut delegate emits `exit_review_mode`
 * through this sink on every termination path (happy, timeout,
 * aborted) so the caller does not need to reach into the delegate's
 * internals.
 */
export interface DelegateEventSink {
  /** Upstream codex `Session::send_event` — sends an event with the
   *  given sub_id stamped as `id`. */
  sendEvent(subId: string, msg: EventMsg): void;
  /** Upstream codex `Session::emit` — emit with a pre-built event. */
  emit(event: Event): void;
}

/**
 * Minimum session surface the delegate consumes. Shaped so the live
 * `Session` satisfies it with zero adapter work (the fields below are
 * all present on `Session`), while tests can supply a minimal object
 * literal.
 *
 * Upstream codex threads the full `Arc<Session>` through
 * `run_codex_thread_one_shot` because `forward_events` needs the
 * parent's approval/permission routing. The gut delegate does not run
 * approval paths today (see module-doc INCOMPLETE), so the slim
 * interface stays honest and the RESERVED fields land explicitly
 * when that port arrives.
 */
export interface DelegateSessionLike extends DelegateEventSink {
  /** Upstream `sess.services.provider`. The provider to route the
   *  one-shot review call through. */
  readonly provider: LLMProvider;
  /** Upstream codex `Session::spawn_task`. Used so the delegate's
   *  review turn participates in the Wave 2 task lifecycle (replace-
   *  on-new-turn, abort cascade, done promise). */
  spawnTask(opts: {
    readonly subId: string;
    readonly kind: TaskKind;
    readonly abortController?: AbortController;
    readonly startedAtMs?: number;
  }): Promise<{
    readonly subId: string;
    readonly kind: TaskKind;
    readonly abortController: AbortController;
    readonly done: Promise<void>;
  }>;
  /** Upstream codex `Session::on_task_finished`. Called by the
   *  delegate on every termination path so the task drains cleanly. */
  onTaskFinished(subId: string): Promise<void>;
}

/**
 * Minimum `TurnContext` surface the delegate consumes when
 * synthesizing the review-scoped context. The full `TurnContext` is
 * accepted via `TurnContext`, but the structural shape below
 * documents exactly which fields participate in the review-scoped
 * override so a future ThreadContext-style refactor can narrow the
 * coupling.
 */
export type DelegateTurnContextLike = TurnContext;

// ─────────────────────────────────────────────────────────────────────
// Request / response shapes (upstream codex `run_codex_thread_one_shot`)
// ─────────────────────────────────────────────────────────────────────

/**
 * Input shape for `runOneShot`. Mirrors the positional arg list of
 * upstream codex `run_codex_thread_one_shot`:
 *   (config, auth_manager, models_manager, input, parent_session,
 *    parent_ctx, cancel_token, subagent_source,
 *    final_output_json_schema, initial_history)
 *
 * Gut collapses `auth_manager` / `models_manager` / `initial_history`
 * into RESERVED slots — the one-shot review path does not exercise
 * them today (see module-doc INCOMPLETE). Keeping the optional
 * fields on the request shape preserves upstream parity so when the
 * child-Session spawn lands, the caller signature will not need to
 * change.
 */
export interface CodexThreadOneShotRequest {
  /** Upstream `sub_id`. Identifier the session registers the task
   *  under. The delegate reuses this as the `TurnContext.subId` so the
   *  review-scoped context stamps emitted events with the caller's id. */
  readonly subId: string;
  /** Upstream `config`. The review-scoped `Config` from
   *  {@link buildGuardianReviewSessionConfig}. Required so the one-shot
   *  call uses the reviewer-scoped sandbox/approval/feature settings
   *  instead of the parent's. */
  readonly config: Config;
  /** Upstream `parent_ctx`. The parent `TurnContext` used as the
   *  basis for the review-scoped `TurnContext`. */
  readonly parentContext: DelegateTurnContextLike;
  /** Upstream `input: Vec<UserInput>`. Gut delegate accepts a
   *  pre-formed `LLMMessage[]` because the upstream `UserInput::Text`
   *  → provider-message plumbing lives outside this module's scope. */
  readonly input: ReadonlyArray<LLMMessage>;
  /** Review request context (target + user-facing hint). Attached to
   *  the synthesized `exit_review_mode` event so UIs can render which
   *  review this result belongs to. */
  readonly request: ReviewRequest;
  /** Optional reviewer-model override. Upstream reads this from
   *  `config.review_model` / `parent_ctx.model_info.slug`. When
   *  provided here, the delegate rebinds the review-scoped
   *  `TurnContext.modelInfo.slug` before issuing the provider call. */
  readonly reviewerModel?: string;
  /** Optional model metadata for the reviewer model. When omitted,
   *  the delegate inherits the parent context's `modelInfo`. */
  readonly reviewerModelInfo?: ModelInfo;
  /** Upstream `final_output_json_schema`. Passed through to the
   *  provider's structured-output slot when supported. `undefined`
   *  runs the reviewer as free-form text. */
  readonly finalOutputJsonSchema?: unknown;
  /** Upstream `cancel_token`. Parent abort signal; the delegate
   *  derives a child controller from this so it can shut down
   *  independently on completion. */
  readonly signal?: AbortSignal;
  /** Optional hard deadline for the one-shot turn. Upstream's
   *  `run_before_review_deadline` enforces a per-review timeout at
   *  the manager level; exposing it on the delegate as well lets
   *  callers without a `ReviewManager` bound still apply a budget. */
  readonly timeoutMs?: number;
  // RESERVED: upstream codex `auth_manager`, `models_manager`,
  // `subagent_source`, `initial_history`. Left off the TS shape until
  // the child-Session spawn is wired; adding them later does not
  // require signature churn for callers.
}

/**
 * Upstream codex `Codex` return value of `run_codex_thread_one_shot`
 * (the wrapped `Codex` struct from `codex_delegate.rs:230-236`). Gut
 * collapses this into a synchronous outcome because there is no
 * child-Session event channel to drain. Shape preserves the
 * essential fields a caller needs:
 *
 *   - `verdict` — `pass` / `fail` / `partial` / `aborted` / `timeout`.
 *     `pass` / `fail` / `partial` mirror upstream's structured
 *     `ReviewOutputEvent` outcomes; `aborted` / `timeout` cover the
 *     teardown paths where no model output is available.
 *   - `output` — parsed `ReviewOutput` (upstream `ReviewOutputEvent`).
 *     Always present so callers do not branch on undefined. Empty on
 *     abort/timeout.
 *   - `rawText` — the raw assistant text the reviewer model
 *     produced, pre-`parseReviewOutput`. `null` on abort/timeout.
 *   - `modelUsed` — the effective reviewer model slug (the overridden
 *     model when supplied, else the parent's).
 *   - `error` — populated on `aborted` / `timeout` / unexpected
 *     provider failure. Carries the underlying error reason for
 *     telemetry. `null` on success paths.
 */
export interface CodexThreadOneShotOutcome {
  readonly verdict: "pass" | "fail" | "partial" | "aborted" | "timeout";
  readonly output: ReviewOutput;
  readonly rawText: string | null;
  readonly modelUsed: string;
  readonly error: Error | null;
}

// ─────────────────────────────────────────────────────────────────────
// Error shapes (upstream CodexErr / guardian review errors)
// ─────────────────────────────────────────────────────────────────────

/**
 * Raised when the request specifies a reviewer model that the
 * provider does not support. Upstream codex surfaces this through
 * `ModelsManager::get_model_info` failing to resolve the model slug.
 * Gut's delegate checks it up-front so callers get a typed rejection
 * before any provider round-trip.
 */
export class ReviewerModelMismatchError extends Error {
  readonly reviewerModel: string;
  readonly providerName: string;
  constructor(reviewerModel: string, providerName: string) {
    super(
      `reviewer model \`${reviewerModel}\` is not supported by provider \`${providerName}\``,
    );
    this.name = "ReviewerModelMismatchError";
    this.reviewerModel = reviewerModel;
    this.providerName = providerName;
  }
}

// ─────────────────────────────────────────────────────────────────────
// build_guardian_review_session_config port
// ─────────────────────────────────────────────────────────────────────

/**
 * Options for {@link buildGuardianReviewSessionConfig}. Mirrors the
 * positional args of upstream
 * `guardian/review_session.rs::build_guardian_review_session_config`
 * (`review_session.rs:831-836`) with a couple of gut-friendly
 * additions for the feature-flag surface.
 */
export interface BuildGuardianReviewSessionConfigOptions {
  /** Upstream `parent_config: &Config`. The session's live config. */
  readonly parentConfig: Config;
  /** Upstream `active_model: &str`. Reviewer model slug. */
  readonly activeModel: string;
  /**
   * Upstream `reasoning_effort: Option<ReasoningEffort>`. Gut's
   * `Config.modelReasoningEffort` covers the same slot; passing it
   * explicitly mirrors upstream's per-turn override semantics.
   */
  readonly reasoningEffort?: Config["modelReasoningEffort"];
  /**
   * Optional reviewer system prompt override. Defaults to
   * {@link REVIEW_SYSTEM_PROMPT}. Upstream wires this via
   * `guardian_policy_prompt(_with_config)`; gut uses the review
   * guidelines directly (upstream `tasks/review.rs:115`).
   */
  readonly baseInstructions?: string;
}

/**
 * Synthesize the review-scoped `Config` that the sub-codex delegate
 * runs under. Mirrors upstream codex
 * `guardian/review_session.rs::build_guardian_review_session_config`
 * (`review_session.rs:831-897`).
 *
 * The fields that get rewritten (and the upstream evidence):
 *   - `model` ← `activeModel` (upstream line 838)
 *   - `modelReasoningEffort` ← `reasoningEffort` (line 839)
 *   - approval/sandbox → `never` / `read_only` (lines 849-851)
 *   - Features `Collab`, `WebSearchRequest`, `WebSearchCached`,
 *     `SpawnCsv` (the gut-visible subset; upstream also disables
 *     `Apps`, `Plugins`, `CodexHooks`, which gut's `ManagedFeatures`
 *     does not expose — documented below as RESERVED).
 *
 * INCOMPLETE:
 *   - Upstream clears `mcp_servers` (line 855) and rebuilds
 *     `NetworkProxySpec` (line 859). Gut's `Config` shape does not
 *     surface an `mcp_servers` slot today (MCP is wired through
 *     `SessionServices.mcpManager` at session construction time), and
 *     `NetworkProxy` is an opt-in per-turn concern. Those paths are
 *     RESERVED and documented here rather than hidden behind
 *     silent no-ops.
 *   - Upstream `include_skill_instructions = false` (line 840) and
 *     `include_apps_instructions = false` (line 852) map to gut's
 *     `Config` fields that do not exist yet. RESERVED.
 *
 * Pure function: does not mutate the input config. Returns a fresh
 * frozen snapshot via the standard structuredClone+graft path used by
 * `buildPerTurnConfig` so the reviewer config cannot accidentally be
 * mutated by a later phase.
 */
export function buildGuardianReviewSessionConfig(
  opts: BuildGuardianReviewSessionConfigOptions,
): Readonly<Config> {
  const {
    parentConfig,
    activeModel,
    reasoningEffort,
  } = opts;

  // Gut's Config is readonly; structuredClone+graft-preserved the
  // non-serializable features field mirrors `buildPerTurnConfig`
  // (turn-context.ts::cloneConfigForSnapshot). Strip the features
  // callbacks before cloning because `structuredClone` rejects
  // function refs with `DataCloneError`.
  const { features: _features, ...rest } = parentConfig;
  void _features;
  const cloned = structuredClone(rest) as Config;
  // Graft the live features reference back so
  // `features.appsEnabledForAuth` keeps working.
  (cloned as { features: Config["features"] }).features = parentConfig.features;

  const mutable = cloned as unknown as Record<string, unknown>;
  mutable.model = activeModel;
  if (reasoningEffort !== undefined) {
    mutable.modelReasoningEffort = reasoningEffort;
  }
  // Upstream: approval_policy = Never, sandbox_policy = read_only.
  // Gut's `Config` holds approval/sandbox on `SessionConfiguration`
  // (not directly on Config). The reviewer-scoped TurnContext pulls
  // approval/sandbox from the parent sessionConfiguration during
  // `buildTurnContext`; the runOneShot path overrides them there.
  // Documenting the indirection here so the contract is visible.

  // Freeze so callers cannot silently mutate.
  return Object.freeze(cloned);
}

// ─────────────────────────────────────────────────────────────────────
// runOneShot — upstream codex `run_codex_thread_one_shot` port
// ─────────────────────────────────────────────────────────────────────

/**
 * Build the review-scoped `TurnContext` from the parent context +
 * reviewer overrides. Mirrors the inline turn-context assembly at
 * upstream `codex-rs/core/src/session/review.rs:101-146`.
 *
 * Unlike upstream's hand-built `TurnContext { ... }` struct literal,
 * gut threads the overrides through `buildTurnContext` so the frozen-
 * config invariant + metadata state get the same treatment as every
 * other turn. The caller-visible difference: reviewer web/view-image
 * features are disabled (features call is inert because gut's
 * `ManagedFeatures` is functions-only — see RESERVED comment below),
 * and the reviewer system prompt is applied at call-site (the
 * delegate prepends a system message before the user prompt).
 */
export function buildReviewTurnContext(
  parentCtx: DelegateTurnContextLike,
  reviewerModel: string,
  reviewerModelInfo: ModelInfo | undefined,
  reviewSubId: string,
): TurnContext {
  const modelInfo: ModelInfo = reviewerModelInfo ?? {
    ...parentCtx.modelInfo,
    slug: reviewerModel,
  };
  // Reviewer-scoped SessionConfiguration derived from parent. The
  // reviewer must not surface the parent's user/developer
  // instructions (those are the author's context, not the reviewer's)
  // and must carry the reviewer-scoped `collaborationMode.model` +
  // review-forced `approvalPolicy: never` / `sandboxPolicy:
  // read_only`.
  const sc = {
    cwd: parentCtx.cwd,
    approvalPolicy: { value: "never" as const },
    sandboxPolicy: { value: "read_only" as const },
    fileSystemSandboxPolicy: parentCtx.fileSystemSandboxPolicy,
    networkSandboxPolicy: parentCtx.networkSandboxPolicy,
    windowsSandboxLevel: parentCtx.windowsSandboxLevel,
    collaborationMode: {
      model: reviewerModel,
      ...(parentCtx.collaborationMode.reasoningEffort !== undefined
        ? { reasoningEffort: parentCtx.collaborationMode.reasoningEffort }
        : {}),
    },
    // Upstream zeroes developer_instructions / user_instructions for
    // the reviewer (session/review.rs:121-122). Preserve that contract.
    dynamicTools: parentCtx.dynamicTools,
    sessionSource: parentCtx.sessionSource,
  };
  return buildTurnContext({
    conversationId: parentCtx.turnMetadataState.conversationId,
    subId: reviewSubId,
    config: parentCtx.config,
    modelInfo,
    provider: parentCtx.provider,
    sessionConfiguration: sc,
    ...(parentCtx.authManager !== undefined
      ? { authManager: parentCtx.authManager }
      : {}),
    ...(parentCtx.environment !== undefined
      ? { environment: parentCtx.environment }
      : {}),
    ...(parentCtx.network !== undefined ? { network: parentCtx.network } : {}),
    jsRepl: parentCtx.jsRepl,
  });
}

/**
 * Compose a minimal review-scoped message list for the provider call.
 * Upstream hands `input: Vec<UserInput>` to the child codex and lets
 * the child session's prompt builder prepend its `base_instructions`
 * (the reviewer system prompt). Because gut's delegate is a flat
 * one-shot (no child session), the prompt construction happens here.
 *
 * Layout:
 *   [0] system  — reviewer system prompt
 *   [1..]       — caller-supplied `input` messages verbatim
 *
 * The caller's messages pass through unchanged so a reviewer-prompt
 * that already contains a `user` message with the diff body stays
 * intact.
 */
function composeReviewerMessages(
  systemPrompt: string,
  input: ReadonlyArray<LLMMessage>,
): LLMMessage[] {
  const systemMessage: LLMMessage = {
    role: "system",
    content: systemPrompt,
  };
  return [systemMessage, ...input];
}

/**
 * Upstream codex `run_codex_thread_one_shot`
 * (`codex_delegate.rs:156-237`) port. Runs a bounded single-turn
 * review provider call under the review-scoped `TurnContext` and
 * returns a structured outcome.
 *
 * Upstream sequence preserved:
 *   1. Derive a child cancellation context from the caller's signal
 *      so shutdown can fire without touching the caller's controller.
 *   2. Register the turn as `kind: "review"` through `spawnTask` so
 *      the Wave 2 replace-on-new-turn / abort-cascade contract
 *      applies.
 *   3. Synthesize the review-scoped `TurnContext` + reviewer system
 *      prompt, compose the provider input, and issue a single
 *      provider call.
 *   4. Parse the assistant text into a `ReviewOutput` (mirrors
 *      upstream `parse_review_output_event`) and classify the
 *      verdict.
 *   5. Emit `exit_review_mode` once on termination (happy, timeout,
 *      aborted).
 *   6. Drain the task via `onTaskFinished` so the session's active
 *      turn slot clears.
 *
 * The outcome shape matches `CodexThreadOneShotOutcome` — never
 * throws on review failure paths (timeout, abort, malformed
 * response). Propagates a typed {@link ReviewerModelMismatchError}
 * up-front when the reviewer model is not resolvable through the
 * provider, because that is a setup-time contract violation, not a
 * review outcome.
 */
export async function runOneShot(
  session: DelegateSessionLike,
  req: CodexThreadOneShotRequest,
): Promise<CodexThreadOneShotOutcome> {
  // Reviewer-model resolution. Upstream consults ModelsManager; gut
  // delegates the check to the provider's capability hint (the
  // provider exposes `getExecutionProfile` but not a model-list
  // lookup, so the delegate accepts anything the caller specifies
  // and trusts the provider to reject at the adapter boundary). The
  // typed mismatch error exists so a future ModelsManager port can
  // flip the trust model without changing the public surface.
  const reviewerModel =
    req.reviewerModel ?? req.parentContext.modelInfo.slug;
  if (reviewerModel.length === 0) {
    throw new ReviewerModelMismatchError(reviewerModel, session.provider.name);
  }

  // Parent abort → child controller merge. Fire the child when the
  // parent fires; tear down the listener on completion.
  const childController = new AbortController();
  const parentSignal = req.signal;
  let parentAbortListener: (() => void) | undefined;
  if (parentSignal) {
    if (parentSignal.aborted) {
      childController.abort(parentSignal.reason);
    } else {
      parentAbortListener = () => {
        childController.abort(parentSignal.reason);
      };
      parentSignal.addEventListener("abort", parentAbortListener, {
        once: true,
      });
    }
  }

  // Upstream: `sess.spawn_task(tc, input, ReviewTask::new())` registers
  // the review turn with `TaskKind::Review`. Gut's `spawnTask` returns
  // the task handle; we pass our child controller so abort flows
  // through the same cancellation surface.
  const task = await session.spawnTask({
    subId: req.subId,
    kind: "review",
    abortController: childController,
    startedAtMs: Date.now(),
  });

  // Timeout guard. Upstream applies deadlines at the manager level
  // (`run_before_review_deadline`, review_session.rs:899-914); gut
  // exposes the budget on the delegate too for callers without a
  // manager. On expiry, fire the child controller and record the
  // timeout reason so the final outcome classifies correctly.
  let timeoutFired = false;
  let timeoutHandle: ReturnType<typeof setTimeout> | undefined;
  if (req.timeoutMs !== undefined && req.timeoutMs > 0) {
    timeoutHandle = setTimeout(() => {
      timeoutFired = true;
      childController.abort("timeout");
    }, req.timeoutMs);
  }

  let assistantText: string | null = null;
  let providerError: Error | null = null;
  try {
    // Build the review-scoped TurnContext so the provider call runs
    // under the reviewer-facing model/auth envelope. The context is
    // built but consumed implicitly — gut's provider interface takes
    // (messages, options) rather than (ctx, messages), so the ctx's
    // role here is to carry the frozen review-scoped config for the
    // runtime to observe (emitted events, telemetry, future turn-
    // state writes). The provider call below reads `modelInfo.slug`
    // from this ctx when the reviewer model differs from the parent.
    void buildReviewTurnContext(
      req.parentContext,
      reviewerModel,
      req.reviewerModelInfo,
      req.subId,
    );

    const messages = composeReviewerMessages(
      REVIEW_SYSTEM_PROMPT,
      req.input,
    );

    if (childController.signal.aborted) {
      // Aborted before we even issued the provider call (parent
      // signal fired synchronously, or timeout is zero and fired on
      // the microtask queue). Fall through to the termination block
      // with no assistantText.
    } else {
      const response: LLMResponse = await session.provider.chat(
        messages as LLMMessage[],
        {
          signal: childController.signal,
          ...(req.finalOutputJsonSchema !== undefined
            ? {
                structuredOutput: {
                  schema: req.finalOutputJsonSchema,
                } as unknown as import("../llm/types.js").LLMStructuredOutputRequest,
              }
            : {}),
        },
      );
      assistantText = response.content ?? null;
    }
  } catch (err) {
    providerError = err instanceof Error ? err : new Error(String(err));
  } finally {
    if (timeoutHandle !== undefined) clearTimeout(timeoutHandle);
    if (parentSignal && parentAbortListener !== undefined) {
      parentSignal.removeEventListener("abort", parentAbortListener);
    }
  }

  // Verdict classification. Order matches upstream: timeout → abort
  // → provider error → parsed output. Timeout wins over generic
  // abort so the UI can surface the more-specific reason.
  let verdict: CodexThreadOneShotOutcome["verdict"];
  let output: ReviewOutput;
  let error: Error | null = null;
  if (timeoutFired) {
    verdict = "timeout";
    output = emptyReviewOutput();
    error = new Error("review timed out");
  } else if (childController.signal.aborted && assistantText === null) {
    verdict = "aborted";
    output = emptyReviewOutput();
    const reason = childController.signal.reason;
    error =
      reason instanceof Error
        ? reason
        : new Error(
            typeof reason === "string" && reason.length > 0
              ? reason
              : "aborted",
          );
  } else if (providerError !== null && assistantText === null) {
    // Provider failed without returning any content. Classify as a
    // "fail" verdict (the review could not complete), surface the
    // typed error in `error` so the caller can telemetry-route.
    verdict = "fail";
    output = emptyReviewOutput();
    error = providerError;
  } else {
    output = assistantText !== null ? parseReviewOutput(assistantText) : emptyReviewOutput();
    if (output.findings.length > 0) {
      verdict = "fail"; // findings present → reviewer flagged issues
    } else if (output.overallExplanation.trim().length === 0) {
      verdict = "partial"; // nothing useful came back
    } else {
      verdict = "pass"; // reviewer had something to say but no findings
    }
  }

  // Emit the `exit_review_mode` event on every termination path so
  // consumers do not have to reconcile "did the task emit the event
  // or did I need to emit it myself". Upstream emits from
  // `tasks/review.rs::exit_review_mode` (`tasks/review.rs:213-283`)
  // including the rollout record; gut emits only the event here and
  // leaves rollout materialization to a later port (the RESERVED
  // record_conversation_items + record_response_item_and_emit_turn_item
  // call sites).
  const exitPayload: ExitReviewModePayload = {
    subId: req.subId,
    reason:
      verdict === "timeout"
        ? "timeout"
        : verdict === "aborted"
          ? "aborted"
          : "completed",
    reviewOutput: output,
    modelUsed: reviewerModel,
    request: req.request,
  };
  session.sendEvent(req.subId, {
    type: "exit_review_mode",
    payload: exitPayload,
  });

  // Drain the task from the session registry. Upstream
  // `SessionTaskContext::on_task_finished` fires after `ReviewTask::run`
  // returns; gut's `Session.onTaskFinished` clears the activeTurn
  // slot when the task registry empties. `void`-await is fine because
  // the lifecycle awaits `task.done` elsewhere (graceful interruption
  // path); we resolve `done` here by explicitly finishing.
  await session.onTaskFinished(task.subId);

  return {
    verdict,
    output,
    rawText: assistantText,
    modelUsed: reviewerModel,
    error,
  };
}

// ─────────────────────────────────────────────────────────────────────
// exit_review_mode event payload
// ─────────────────────────────────────────────────────────────────────

/**
 * Upstream codex `ExitedReviewModeEvent`
 * (`protocol/src/protocol.rs:2157-2159`). Carries the review output
 * so the UI can render results; gut adds the termination `reason`
 * and the `modelUsed` for telemetry + a compact `subId` for event
 * correlation.
 *
 * `reason` values:
 *   - `"completed"` — reviewer produced output; `reviewOutput` is the
 *     structured findings + explanation.
 *   - `"timeout"` — the `timeoutMs` budget elapsed.
 *   - `"aborted"` — parent abort signal fired (session teardown,
 *     session.abortAllTasks, user interrupt).
 */
export interface ExitReviewModePayload {
  readonly subId: string;
  readonly reason: "completed" | "timeout" | "aborted";
  readonly reviewOutput: ReviewOutput;
  readonly modelUsed: string;
  readonly request: ReviewRequest;
}
