import { AsyncLocalStorage } from "node:async_hooks";
import { dirname, resolve } from "node:path";

type WriteBehindJob = { readonly kind: string; readonly run: () => void };
const currentQueue = new AsyncLocalStorage<SessionWriteBehindQueue>();
const writers = new Map<string, { project: string; queue: SessionWriteBehindQueue }>();

export function registerSessionWriteBehind(rolloutPath: string, queue: SessionWriteBehindQueue): () => void {
  const path = resolve(rolloutPath);
  const entry = { project: dirname(dirname(dirname(path))), queue };
  writers.set(path, entry);
  return () => { if (writers.get(path) === entry) writers.delete(path); };
}

export function drainRolloutWriteBehind(rolloutPath: string): void {
  const queue = writers.get(resolve(rolloutPath))?.queue;
  queue?.barrier();
}

export function drainProjectWriteBehind(projectDir: string): void {
  const project = resolve(projectDir);
  for (const entry of writers.values()) {
    if (entry.project === project) entry.queue.barrier();
  }
}

/** One session's ordered persistence work. Jobs must capture their inputs. */
export class SessionWriteBehindQueue {
  private jobs: WriteBehindJob[] = [];
  private enabled = false;
  private runInOwnerScope: ReturnType<typeof AsyncLocalStorage.snapshot> | undefined;
  private depth = 0;
  private observing = false;
  private failed = false;
  private failure: unknown;

  get pending(): number { return this.jobs.length; }
  get deferring(): boolean { return this.enabled && this.depth === 0; }
  get draining(): boolean { return this.depth !== 0; }

  /** Internal writes can read their own projection; public observers drain. */
  barrier(): void {
    this.assertHealthy();
    if (!this.draining || this.observing) this.drain();
  }

  observe<T>(run: () => T): T {
    const previous = this.observing;
    this.observing = true;
    try { return run(); }
    finally { this.observing = previous; }
  }

  /** Start one loss window; the preceding step must have been flushed. */
  beginStep(): void {
    this.drain();
    this.runInOwnerScope = AsyncLocalStorage.snapshot();
    this.enabled = true;
  }

  /** Returns false when the caller must perform the work synchronously. */
  defer(kind: string, run: () => void): boolean {
    this.assertHealthy();
    if (!this.deferring) return false;
    this.enqueue(kind, run);
    return true;
  }

  /** Retain follow-up work generated by a running persistence job. */
  enqueue(kind: string, run: () => void): void {
    this.assertHealthy();
    this.jobs.push({ kind, run });
  }

  /** Readers and terminal paths call this before observing durable state. */
  drain(): void {
    this.assertHealthy();
    this.depth += 1;
    try {
      while (this.jobs.length > 0) {
        this.assertHealthy();
        // Retain a failed job and all successors. They remain
        // owned by this failed session; they are never silently discarded.
        const job = this.jobs.shift()!;
        const previousObserver = this.observing;
        this.observing = false;
        try {
          if (this.runInOwnerScope) this.runInOwnerScope(job.run);
          else job.run();
        }
        catch (error) {
          this.jobs.unshift(job);
          this.failed = true;
          this.failure = error;
          throw error;
        }
        finally { this.observing = previousObserver; }
      }
      this.assertHealthy();
    } finally { this.depth -= 1; }
  }

  finish(): void {
    this.enabled = false;
    this.drain();
  }

  assertHealthy(): void {
    if (this.failed) throw this.failure;
  }
}

/** Async scope is explicit; there is no process-wide session fallback. */
export function withSessionWriteBehind<T>(queue: SessionWriteBehindQueue, run: () => T): T {
  return currentQueue.run(queue, run);
}

export function currentSessionWriteBehind(): SessionWriteBehindQueue | undefined {
  return currentQueue.getStore();
}
