export {
  AmendError,
  ExampleDidMatchError,
  ExampleDidNotMatchError,
  ExecPolicyError,
  Policy,
  PolicyParser,
  blockingAppendAllowPrefixRule,
  blockingAppendNetworkRule,
  createPolicyParser,
  evaluatePolicyCommand,
  formatMatchesJson,
  loadPolicies,
  normalizeNetworkRuleHost,
  parseDecision,
  parseExecPolicyArgv,
  parseNetworkRuleProtocol,
  parsePolicy,
  runExecPolicyCheckCommand,
  runExecPolicyCli,
  serializeRuleMatch,
  type Decision,
  type ErrorLocation,
  type Evaluation,
  type ExecPolicyCheckCommand,
  type ExecPolicyCheckOutput,
  type HeuristicsFallback,
  type MatchOptions,
  type NetworkRule,
  type NetworkRuleProtocol,
  type PatternToken,
  type PrefixPattern,
  type PrefixRule,
  type Rule,
  type RuleMatch,
  type SerializedRuleMatch,
  type TextPosition,
  type TextRange,
} from "./index.js";

export const EXECPOLICY_PUBLIC_SURFACE = [
  "PolicyParser",
  "Policy",
  "parsePolicy",
  "formatMatchesJson",
  "blockingAppendAllowPrefixRule",
  "blockingAppendNetworkRule",
] as const;
