/**
 * Compact conversation helpers.
 *
 * Source snapshot: `src/services/compact/compact.ts` and
 * `src/services/compact/prompt.ts` at
 * `0ca43335375beec6e58711b797d5b0c4bb5019b8`.
 *
 * AgenC keeps the live runtime surface strict-safe and delegates provider
 * summary calls through the caller-supplied compact context.
 */

import { randomUUID } from "node:crypto";
import type { CompactContext, CompactionResult, RuntimeMessage } from "./types.js";
import { runPostCompactCleanup } from "./postCompactCleanup.js";
import {
  getCompactPrompt,
  getCompactUserSummaryMessage,
  getPartialCompactPrompt,
  type PartialCompactDirection,
} from "./prompt.js";
import {
  estimateMessagesTokens,
  messageText,
} from "./_deps/runtime.js";

const SUMMARY_MAX_OUTPUT_TOKENS = 4_000;
const MAX_SUMMARY_INPUT_CHARS = 48_000;
const NO_CONTENT_MESSAGE = "(no content)";
export const ERROR_MESSAGE_USER_ABORT = "User aborted";
const COMMAND_NAME_TAG = "command-name";
const COMMAND_MESSAGE_TAG = "command-message";
const COMMAND_ARGS_TAG = "command-args";
const LOCAL_COMMAND_CAVEAT_TAG = "local-command-caveat";

export async function manualCompactCall(
  args: string,
  context: CompactContext & { readonly messages?: RuntimeMessage[] },
): Promise<{
  readonly type: "compact";
  readonly compactionResult: CompactionResult;
  readonly displayText: string;
}> {
  const messages = context.messages ?? [];
  if (messages.length === 0) {
    throw new Error("No messages to compact");
  }
  context.onCompactProgress?.({
    type: "hooks_start",
    hookType: "pre_compact",
  });
  context.setSDKStatus?.("compacting");
  try {
    context.setStreamMode?.("requesting");
    context.setResponseLength?.(() => 0);
    context.onCompactProgress?.({ type: "compact_start" });
    const compactionResult = await compactConversation(
      messages,
      context,
      args.trim(),
    );
    runPostCompactCleanup(context.deps?.cleanup);
    return {
      type: "compact",
      compactionResult,
      displayText: compactionResult.userDisplayMessage ?? "Conversation compacted",
    };
  } finally {
    context.setStreamMode?.("requesting");
    context.setResponseLength?.(() => 0);
    context.onCompactProgress?.({ type: "compact_end" });
    context.setSDKStatus?.(null);
  }
}

export function buildPostCompactMessages(
  result: CompactionResult,
): RuntimeMessage[] {
  return [
    result.boundaryMarker,
    ...result.summaryMessages,
    ...(result.messagesToKeep ?? []),
    ...result.attachments,
    ...result.hookResults,
  ];
}

export function createUserMessage({
  content,
  isMeta,
  uuid,
  timestamp,
}: {
  readonly content: string | readonly Record<string, unknown>[];
  readonly isMeta?: true;
  readonly uuid?: string;
  readonly timestamp?: string;
}): RuntimeMessage {
  const normalizedContent =
    typeof content === "string" && content.length === 0
      ? NO_CONTENT_MESSAGE
      : content;
  return {
    type: "user",
    role: "user",
    message: {
      role: "user",
      content: normalizedContent,
    },
    content: normalizedContent,
    isMeta,
    uuid: uuid ?? randomUUID(),
    timestamp: timestamp ?? new Date().toISOString(),
  };
}

export function createSyntheticUserCaveatMessage(): RuntimeMessage {
  return createUserMessage({
    content: `<${LOCAL_COMMAND_CAVEAT_TAG}>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</${LOCAL_COMMAND_CAVEAT_TAG}>`,
    isMeta: true,
  });
}

export function formatCommandInputTags(
  commandName: string,
  args: string,
): string {
  const escapedCommandName = escapeTagText(commandName);
  const escapedArgs = escapeTagText(args);
  return `<${COMMAND_NAME_TAG}>/${escapedCommandName}</${COMMAND_NAME_TAG}>
            <${COMMAND_MESSAGE_TAG}>${escapedCommandName}</${COMMAND_MESSAGE_TAG}>
            <${COMMAND_ARGS_TAG}>${escapedArgs}</${COMMAND_ARGS_TAG}>`;
}

export async function compactConversation(
  messages: readonly RuntimeMessage[],
  context: CompactContext,
  customInstructions = "",
): Promise<CompactionResult> {
  const normalizedMessages = stripImagesFromMessages(messages);
  const preCompactTokenCount = estimateMessagesTokens(normalizedMessages, context);
  const keepCount = chooseKeepCount(normalizedMessages);
  // chooseKeepCount picks a positional split. resolveAtomicSliceIndex
  // walks that index forward past any leading `role: "tool"` message
  // so the kept suffix never starts with a tool_result whose parent
  // assistant tool_call lives in the summarized prefix. Without this
  // adjustment the kept suffix is provider-invalid (every openai-
  // compatible endpoint 400s on an orphaned tool message).
  const candidateSplit = Math.max(0, normalizedMessages.length - keepCount);
  const splitIndex = resolveAtomicSliceIndex(normalizedMessages, candidateSplit);
  const messagesToSummarize = normalizedMessages.slice(0, splitIndex);
  const messagesToKeep = normalizedMessages.slice(splitIndex);
  const summary = await summarizeMessages(
    messagesToSummarize.length > 0 ? messagesToSummarize : normalizedMessages,
    context,
    customInstructions,
  );
  const boundaryMarker = createRuntimeMessage(
    "user",
    `<compact>Conversation compacted at ${new Date().toISOString()}</compact>`,
    true,
  );
  const summaryMessage = createRuntimeMessage(
    "user",
    getCompactUserSummaryMessage(summary),
    true,
  );
  const attachments = await context.deps?.createAttachments?.(
    normalizedMessages,
    context,
  ) ?? [];
  const hookResults = await context.deps?.createHookResults?.(
    summary,
    context,
  ) ?? [];
  const postCompactTokenCount = estimateMessagesTokens(
    [
      boundaryMarker,
      summaryMessage,
      ...messagesToKeep,
      ...attachments,
      ...hookResults,
    ],
    context,
  );
  return {
    boundaryMarker,
    summaryMessages: [summaryMessage],
    messagesToKeep,
    attachments,
    hookResults,
    userDisplayMessage: "Conversation compacted",
    preCompactTokenCount,
    postCompactTokenCount,
    truePostCompactTokenCount: postCompactTokenCount,
  };
}

export function partialCompactConversation(
  messages: readonly RuntimeMessage[],
  options: {
    readonly keepPrefixCount?: number;
    readonly keepSuffixCount?: number;
  } = {},
): RuntimeMessage[] {
  const keepPrefixCount = Math.max(0, options.keepPrefixCount ?? 0);
  const keepSuffixCount = Math.max(0, options.keepSuffixCount ?? 0);
  const prefix = messages.slice(0, keepPrefixCount);
  const suffixStart = Math.max(keepPrefixCount, messages.length - keepSuffixCount);
  return [...prefix, ...messages.slice(suffixStart)];
}

export async function partialCompactConversationAsync(
  messages: readonly RuntimeMessage[],
  selectedIndex: number,
  context: CompactContext,
  options: {
    readonly direction: PartialCompactDirection;
    readonly feedback?: string;
    readonly signal?: AbortSignal;
  },
): Promise<CompactionResult> {
  if (!Number.isInteger(selectedIndex) || selectedIndex < 0 || selectedIndex >= messages.length) {
    throw new Error("Selected message is outside the compactable history");
  }
  throwIfAborted(options.signal);
  const normalizedMessages = stripImagesFromMessages(messages);
  const preCompactTokenCount = estimateMessagesTokens(normalizedMessages, context);
  const messagesToSummarize =
    options.direction === "up_to"
      ? normalizedMessages.slice(0, selectedIndex)
      : normalizedMessages.slice(selectedIndex);
  const messagesToKeep =
    options.direction === "up_to"
      ? normalizedMessages.slice(selectedIndex)
      : normalizedMessages.slice(0, selectedIndex);
  const hasMessagesToSummarize = messagesToSummarize.length > 0;
  const summary = hasMessagesToSummarize
    ? await summarizeMessagesWithPrompt(
        messagesToSummarize,
        context,
        getPartialCompactPrompt(options.feedback, options.direction),
        options.signal,
      )
    : "No earlier messages to summarize.";
  throwIfAborted(options.signal);
  const boundaryMarker = createRuntimeMessage(
    "user",
    `<compact>Conversation partially compacted at ${new Date().toISOString()}</compact>`,
    true,
  );
  const summaryMessage = createRuntimeMessage(
    "user",
    getCompactUserSummaryMessage(summary, false, undefined, true),
    true,
  );
  const attachments = await context.deps?.createAttachments?.(
    normalizedMessages,
    context,
  ) ?? [];
  const hookResults = await context.deps?.createHookResults?.(
    summary,
    context,
  ) ?? [];
  const summaryMessages =
    options.direction === "up_to" ? [summaryMessage] : [];
  const orderedMessagesToKeep =
    options.direction === "up_to"
      ? messagesToKeep
      : [...messagesToKeep, summaryMessage];
  const postCompactTokenCount = estimateMessagesTokens(
    [
      boundaryMarker,
      ...summaryMessages,
      ...orderedMessagesToKeep,
      ...attachments,
      ...hookResults,
    ],
    context,
  );
  return {
    boundaryMarker,
    summaryMessages,
    messagesToKeep: orderedMessagesToKeep,
    attachments,
    hookResults,
    userDisplayMessage: "Conversation summarized",
    preCompactTokenCount,
    postCompactTokenCount,
    truePostCompactTokenCount: postCompactTokenCount,
  };
}

async function summarizeMessages(
  messages: readonly RuntimeMessage[],
  context: CompactContext,
  customInstructions: string,
): Promise<string> {
  return summarizeMessagesWithPrompt(
    messages,
    context,
    getCompactPrompt(customInstructions),
    context.abortController?.signal,
  );
}

async function summarizeMessagesWithPrompt(
  messages: readonly RuntimeMessage[],
  context: CompactContext,
  compactPrompt: string,
  signal: AbortSignal | undefined,
): Promise<string> {
  throwIfAborted(signal);
  const transcript = boundTranscript(messages.map(formatForSummary).join("\n\n"));
  const fallback = fallbackSummary(transcript);
  const provider = context.provider;
  if (!provider) return fallback;
  try {
    const response = await provider.chat(
      [{
        role: "user",
        content: `${compactPrompt}\n\n<transcript>\n${transcript}\n</transcript>`,
      }],
      {
        model: context.options?.mainLoopModel,
        systemPrompt: "You produce compact continuation summaries.",
        maxOutputTokens: Math.min(
          context.options?.maxOutputTokens ?? SUMMARY_MAX_OUTPUT_TOKENS,
          SUMMARY_MAX_OUTPUT_TOKENS,
        ),
        signal: signal ?? context.abortController?.signal,
      },
    );
    throwIfAborted(signal);
    const text = response.content.trim();
    return text.length > 0 ? text : fallback;
  } catch (error) {
    throwIfAborted(signal);
    if (error instanceof Error && error.name === "AbortError") throw error;
    return fallback;
  }
}

function throwIfAborted(signal: AbortSignal | undefined): void {
  if (signal?.aborted !== true) return;
  throw new Error("Partial compaction aborted");
}

function chooseKeepCount(messages: readonly RuntimeMessage[]): number {
  if (messages.length <= 2) return 0;
  return Math.min(4, Math.max(1, Math.floor(messages.length * 0.2)));
}

/**
 * Resolve the message-list slice index where compaction can split
 * messages into [summarized prefix | kept verbatim suffix] WITHOUT
 * orphaning a `role: "tool"` message whose matching assistant
 * `tool_calls` parent lives in the prefix.
 *
 * Why: the model's wire-level contract requires every `role: "tool"`
 * message to follow an assistant message that carries the matching
 * `tool_calls[].id` (this is enforced by every openai-compatible
 * provider — the request 400s otherwise). The previous behavior was
 * to slice purely by position, so a tool_call at index N-1 could end
 * up summarized while its tool_result at N was kept verbatim. The
 * tool-turn-validator strips those orphans downstream, but by then
 * the summary already references work whose evidence is gone.
 *
 * Algorithm: starting at the candidate index, walk forward past any
 * leading `role: "tool"` messages until we land on the first non-tool
 * message. Tool-result messages MUST be preceded by their parent
 * assistant in the same kept slice (or summarized along with the
 * parent), so any leading tool result in the candidate suffix is
 * proof the parent is in the prefix — drop it forward into the
 * summarized side.
 *
 * Returns the resolved slice index (0..messages.length). Always
 * returns a value ≥ candidateIndex (we never widen the kept suffix
 * past what chooseKeepCount asked for; we only narrow it).
 */
export function resolveAtomicSliceIndex(
  messages: readonly RuntimeMessage[],
  candidateIndex: number,
): number {
  if (candidateIndex <= 0 || candidateIndex >= messages.length) {
    return Math.max(0, Math.min(candidateIndex, messages.length));
  }
  let index = candidateIndex;
  while (index < messages.length && isToolRoleMessage(messages[index]!)) {
    index += 1;
  }
  return index;
}

function isToolRoleMessage(message: RuntimeMessage): boolean {
  const role = message.role ?? message.message?.role ?? message.originalRole;
  return role === "tool" || message.toolCallId !== undefined;
}

function formatForSummary(message: RuntimeMessage): string {
  const role = message.message?.role ?? message.role ?? message.type ?? "unknown";
  return `<message role="${role}">\n${messageText(message)}\n</message>`;
}

function boundTranscript(transcript: string): string {
  const trimmed = transcript.trim();
  if (trimmed.length <= MAX_SUMMARY_INPUT_CHARS) return trimmed;
  const side = Math.floor((MAX_SUMMARY_INPUT_CHARS - 100) / 2);
  return `${trimmed.slice(0, side)}\n\n[...middle omitted during compaction...]\n\n${trimmed.slice(-side)}`;
}

function fallbackSummary(transcript: string): string {
  const trimmed = transcript.trim();
  if (trimmed.length <= 8_000) return trimmed;
  return `${trimmed.slice(0, 4_000)}\n\n[...middle omitted during compaction...]\n\n${trimmed.slice(-4_000)}`;
}

function stripImagesFromMessages(
  messages: readonly RuntimeMessage[],
): RuntimeMessage[] {
  return messages.map((message) => {
    const content = message.message?.content ?? message.content;
    const stripped = stripMediaContent(content);
    if (stripped === content) return message;
    return {
      ...message,
      content: stripped,
      message: {
        role: message.message?.role ?? message.role ?? "user",
        content: stripped,
      },
    };
  });
}

function stripMediaContent(content: unknown): unknown {
  if (!Array.isArray(content)) return content;
  let changed = false;
  const next = content.map((part) => {
    if (!part || typeof part !== "object") return part;
    const block = part as Record<string, unknown>;
    if (
      block.type === "image" ||
      block.type === "document" ||
      block.type === "image_url"
    ) {
      changed = true;
      return { type: "text", text: `[${String(block.type)}]` };
    }
    if (block.type === "tool_result" && Array.isArray(block.content)) {
      const nested = stripMediaContent(block.content);
      if (nested !== block.content) {
        changed = true;
        return { ...block, content: nested };
      }
    }
    return part;
  });
  return changed ? next : content;
}

function escapeTagText(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function createRuntimeMessage(
  role: "user" | "assistant" | "system",
  content: string,
  isMeta: boolean,
): RuntimeMessage {
  return {
    role,
    type: role,
    content,
    message: { role, content },
    uuid: randomUUID(),
    timestamp: new Date().toISOString(),
    isMeta,
  };
}
