/**
 * OpenClaude-shaped keybinding configuration schema surface.
 *
 * `loadUserBindingsSync()` accepts this upstream-shaped block format and
 * aliases it into AgenC's live keybinding contexts. This module keeps the
 * full OpenClaude context/action catalog available for config validation,
 * docs generation, and parity helpers while the provider resolves the
 * smaller set of contexts that are active in the AgenC shell.
 */

export const KEYBINDING_CONTEXTS = [
  "Global",
  "Chat",
  "Autocomplete",
  "Confirmation",
  "Help",
  "Transcript",
  "HistorySearch",
  "Task",
  "ThemePicker",
  "Settings",
  "Tabs",
  "Attachments",
  "Footer",
  "MessageSelector",
  "DiffDialog",
  "ModelPicker",
  "Select",
  "Plugin",
  "Scroll",
  "Modal",
] as const;

export const KEYBINDING_CONTEXT_DESCRIPTIONS: Record<
  (typeof KEYBINDING_CONTEXTS)[number],
  string
> = {
  Global: "Active everywhere, regardless of focus",
  Chat: "When the chat input is focused",
  Autocomplete: "When autocomplete menu is visible",
  Confirmation: "When a confirmation/permission dialog is shown",
  Help: "When the help overlay is open",
  Transcript: "When viewing the transcript",
  HistorySearch: "When searching command history",
  Task: "When a task/agent is running in the foreground",
  ThemePicker: "When the theme picker is open",
  Settings: "When the settings menu is open",
  Tabs: "When tab navigation is active",
  Attachments: "When navigating image attachments in a select dialog",
  Footer: "When footer indicators are focused",
  MessageSelector: "When the message selector is open",
  DiffDialog: "When the diff dialog is open",
  ModelPicker: "When the model picker is open",
  Select: "When a select/list component is focused",
  Plugin: "When the plugin dialog is open",
  Scroll: "When scroll navigation is active",
  Modal: "AgenC compatibility alias for modal overlays",
};

export const KEYBINDING_ACTIONS = [
  "app:interrupt",
  "app:exit",
  "app:toggleTodos",
  "app:toggleTasks",
  "app:toggleTranscript",
  "app:toggleBrief",
  "app:toggleTeammatePreview",
  "app:toggleTerminal",
  "app:redraw",
  "app:globalSearch",
  "app:quickOpen",
  "history:search",
  "history:previous",
  "history:next",
  "history:prev",
  "chat:cancel",
  "chat:killAgents",
  "chat:cycleMode",
  "chat:modelPicker",
  "chat:fastMode",
  "chat:thinkingToggle",
  "chat:submit",
  "chat:acceptSuggestion",
  "chat:newline",
  "chat:undo",
  "chat:externalEditor",
  "chat:stash",
  "chat:imagePaste",
  "chat:messageActions",
  "chat:voiceInput",
  "chat:killToEnd",
  "chat:yank",
  "autocomplete:accept",
  "autocomplete:dismiss",
  "autocomplete:previous",
  "autocomplete:next",
  "confirm:yes",
  "confirm:no",
  "confirm:previous",
  "confirm:next",
  "confirm:nextField",
  "confirm:previousField",
  "confirm:cycleMode",
  "confirm:toggle",
  "confirm:toggleExplanation",
  "tabs:next",
  "tabs:previous",
  "transcript:toggleShowAll",
  "transcript:exit",
  "historySearch:next",
  "historySearch:accept",
  "historySearch:cancel",
  "historySearch:execute",
  "task:background",
  "theme:toggleSyntaxHighlighting",
  "help:dismiss",
  "attachments:next",
  "attachments:previous",
  "attachments:remove",
  "attachments:exit",
  "footer:up",
  "footer:down",
  "footer:next",
  "footer:previous",
  "footer:openSelected",
  "footer:clearSelection",
  "footer:close",
  "messageSelector:up",
  "messageSelector:down",
  "messageSelector:top",
  "messageSelector:bottom",
  "messageSelector:select",
  "diff:dismiss",
  "diff:previousSource",
  "diff:nextSource",
  "diff:back",
  "diff:viewDetails",
  "diff:previousFile",
  "diff:nextFile",
  "modelPicker:decreaseEffort",
  "modelPicker:increaseEffort",
  "select:next",
  "select:previous",
  "select:accept",
  "select:cancel",
  "plugin:toggle",
  "plugin:install",
  "permission:toggleDebug",
  "settings:search",
  "settings:retry",
  "settings:close",
  "voice:pushToTalk",
  "scroll:pageUp",
  "scroll:pageDown",
  "scroll:halfPageUp",
  "scroll:halfPageDown",
  "scroll:fullPageUp",
  "scroll:fullPageDown",
  "scroll:lineUp",
  "scroll:lineDown",
  "scroll:top",
  "scroll:bottom",
  "selection:copy",
  "modal:confirm",
  "modal:cancel",
  "modal:yes",
  "modal:no",
  "modal:allowSession",
  "modal:deny",
] as const;

export type KeybindingsSchemaType = {
  $schema?: string;
  $docs?: string;
  bindings: Array<{
    context: (typeof KEYBINDING_CONTEXTS)[number];
    bindings: Record<
      string,
      (typeof KEYBINDING_ACTIONS)[number] | `command:${string}` | null
    >;
  }>;
};

export const KeybindingBlockSchema = {
  type: "object",
  required: ["context", "bindings"],
  properties: {
    context: { enum: KEYBINDING_CONTEXTS },
    bindings: { type: "object" },
  },
} as const;

export const KeybindingsSchema = {
  type: "object",
  required: ["bindings"],
  properties: {
    $schema: { type: "string" },
    $docs: { type: "string" },
    bindings: {
      type: "array",
      items: KeybindingBlockSchema,
    },
  },
} as const;
