// Byte-canonical standalone-installer wrapper contract shared by the runtime
// updater and both embedded installers. Parsing is deliberately full-file:
// marker substrings must never grant ownership of a user-authored executable.

import { isAbsolute, posix, win32 } from "node:path";

export const GENERATED_WRAPPER_MAX_BYTES = 64 * 1024;
const POSIX_WRAPPER_SIGNATURE = "Generated by AgenC install.sh";
const CMD_WRAPPER_SIGNATURE = "Generated by AgenC install.ps1";
const WRAPPER_METADATA_PREFIX = "AgenC wrapper metadata v1:";

function validateValues(kind, values) {
  if (!values || typeof values !== "object") {
    throw new TypeError("wrapper values must be an object");
  }
  for (const label of ["nodeBin", "runtimeBin", "agencHome"]) {
    const value = values[label];
    if (typeof value !== "string") throw new TypeError(`wrapper ${label} must be a string`);
    if (value.includes("\0")) throw new Error(`wrapper ${label} contains NUL`);
    if (kind === "cmd" && /["\r\n]/u.test(value)) {
      throw new Error(`Windows wrapper ${label} contains an unsupported character`);
    }
  }
  if (!isAbsolute(values.agencHome)) {
    throw new Error("wrapper AGENC_HOME must be an absolute path");
  }
  if (values.nodeLibraryPath !== undefined) {
    if (typeof values.nodeLibraryPath !== "string") {
      throw new TypeError("wrapper nodeLibraryPath must be a string");
    }
    if (values.nodeLibraryPath.includes("\0")) {
      throw new Error("wrapper nodeLibraryPath contains NUL");
    }
    if (!isAbsolute(values.nodeLibraryPath)) {
      throw new Error("wrapper nodeLibraryPath must be an absolute path");
    }
    if (kind === "cmd") {
      throw new Error("Windows wrappers do not support nodeLibraryPath");
    }
  }
}

function metadataFor(values) {
  const metadata = {
    nodeBin: values.nodeBin,
    runtimeBin: values.runtimeBin,
    agencHome: values.agencHome,
    ...(values.nodeLibraryPath === undefined
      ? {}
      : { nodeLibraryPath: values.nodeLibraryPath }),
  };
  return Buffer.from(JSON.stringify(metadata), "utf8").toString("base64url");
}

function renderLegacyOomPosixWrapper({ nodeBin, runtimeBin, agencHome }) {
  return [
    "#!/bin/sh",
    `# ${POSIX_WRAPPER_SIGNATURE} — rewritten on every install/upgrade.`,
    `export AGENC_HOME="\${AGENC_HOME:-${agencHome}}"`,
    "# OOM self-diagnosis: have V8 write a heap snapshot from inside the GC when",
    "# the heap nears its limit (reliable even in the end-stage GC stall where JS",
    "# timers starve), into $AGENC_HOME/oom-snapshots. The runtime prunes old",
    "# captures and points at fresh ones on the next startup. User-provided",
    "# NODE_OPTIONS win: ours are prepended, and we skip entirely when the user",
    "# already tunes heap snapshots.",
    'case " ${NODE_OPTIONS:-} " in',
    "  *heapsnapshot-near-heap-limit*) : ;;",
    "  *)",
    '    mkdir -p "${AGENC_HOME}/oom-snapshots" 2>/dev/null || :',
    '    NODE_OPTIONS="--heapsnapshot-near-heap-limit=1 --diagnostic-dir=${AGENC_HOME}/oom-snapshots ${NODE_OPTIONS:-}"',
    "    export NODE_OPTIONS",
    "    ;;",
    "esac",
    `exec "${nodeBin}" "${runtimeBin}" "$@"`,
    "",
  ].join("\n");
}

export function renderGeneratedWrapperContent({
  kind,
  nodeBin,
  runtimeBin,
  agencHome,
  nodeLibraryPath,
}) {
  if (kind !== "posix" && kind !== "cmd") {
    throw new TypeError(`unsupported wrapper kind: ${String(kind)}`);
  }
  const values = { nodeBin, runtimeBin, agencHome, nodeLibraryPath };
  validateValues(kind, values);
  const metadata = metadataFor(values);
  if (kind === "cmd") {
    const batch = (value) => value.replaceAll("%", "%%");
    const nodeDir = win32.dirname(nodeBin);
    return [
      "@echo off",
      "setlocal DisableDelayedExpansion",
      `rem ${CMD_WRAPPER_SIGNATURE} - rewritten on every install/upgrade.`,
      `rem ${WRAPPER_METADATA_PREFIX} ${metadata}`,
      `if not defined AGENC_HOME set "AGENC_HOME=${batch(agencHome)}"`,
      `set "PATH=${batch(nodeDir)};%PATH%"`,
      `"${batch(nodeBin)}" "${batch(runtimeBin)}" %*`,
      "",
    ].join("\r\n");
  }
  const quote = (value) => `'${value.replaceAll("'", `'"'"'`)}'`;
  const nodeDir = posix.dirname(nodeBin);
  const execPrefix = nodeLibraryPath === undefined
    ? "exec "
    : `LD_LIBRARY_PATH=${quote(nodeLibraryPath)} exec `;
  return [
    "#!/bin/sh",
    `# ${POSIX_WRAPPER_SIGNATURE} — rewritten on every install/upgrade.`,
    `# ${WRAPPER_METADATA_PREFIX} ${metadata}`,
    'if [ -z "${AGENC_HOME:-}" ]; then',
    `  export AGENC_HOME=${quote(agencHome)}`,
    "fi",
    'if [ -n "${PATH:-}" ]; then',
    `  export PATH=${quote(nodeDir)}:"$PATH"`,
    "else",
    `  export PATH=${quote(nodeDir)}`,
    "fi",
    "# Capture one V8 near-heap-limit snapshot unless the operator already configured it.",
    'case " ${NODE_OPTIONS:-} " in',
    "  *heapsnapshot-near-heap-limit*)",
    `    ${execPrefix}${quote(nodeBin)} ${quote(runtimeBin)} "$@"`,
    "    ;;",
    "  *)",
    '    mkdir -p "${AGENC_HOME}/oom-snapshots" 2>/dev/null || :',
    `    ${execPrefix}${quote(nodeBin)} --heapsnapshot-near-heap-limit=1 ` +
      '--diagnostic-dir="${AGENC_HOME}/oom-snapshots" ' +
      `${quote(runtimeBin)} "$@"`,
    "    ;;",
    "esac",
    "",
  ].join("\n");
}

// Releases 0.6.2 through 0.10.0 emitted this immutable metadata-v1 shape
// before standalone installs carried a private Node runtime. Keep the renderer
// private: it exists only so ownership can be proven by exact full-file
// reconstruction, never by trusting the historical marker or metadata alone.
function renderPrePrivateNodeWrapperContent({
  kind,
  nodeBin,
  runtimeBin,
  agencHome,
}) {
  if (kind !== "posix" && kind !== "cmd") {
    throw new TypeError(`unsupported wrapper kind: ${String(kind)}`);
  }
  const values = { nodeBin, runtimeBin, agencHome };
  validateValues(kind, values);
  const metadata = Buffer.from(JSON.stringify({
    nodeBin,
    runtimeBin,
    agencHome,
  }), "utf8").toString("base64url");
  if (kind === "cmd") {
    const batch = (value) => value.replaceAll("%", "%%");
    return [
      "@echo off",
      "setlocal DisableDelayedExpansion",
      `rem ${CMD_WRAPPER_SIGNATURE} - rewritten on every install/upgrade.`,
      `rem ${WRAPPER_METADATA_PREFIX} ${metadata}`,
      `if not defined AGENC_HOME set "AGENC_HOME=${batch(agencHome)}"`,
      `"${batch(nodeBin)}" "${batch(runtimeBin)}" %*`,
      "",
    ].join("\r\n");
  }
  const quote = (value) => `'${value.replaceAll("'", `'"'"'`)}'`;
  return [
    "#!/bin/sh",
    `# ${POSIX_WRAPPER_SIGNATURE} — rewritten on every install/upgrade.`,
    `# ${WRAPPER_METADATA_PREFIX} ${metadata}`,
    'if [ -z "${AGENC_HOME:-}" ]; then',
    `  export AGENC_HOME=${quote(agencHome)}`,
    "fi",
    "# Capture one V8 near-heap-limit snapshot unless the operator already configured it.",
    'case " ${NODE_OPTIONS:-} " in',
    "  *heapsnapshot-near-heap-limit*)",
    `    exec ${quote(nodeBin)} ${quote(runtimeBin)} "$@"`,
    "    ;;",
    "  *)",
    '    mkdir -p "${AGENC_HOME}/oom-snapshots" 2>/dev/null || :',
    `    exec ${quote(nodeBin)} --heapsnapshot-near-heap-limit=1 ` +
      '--diagnostic-dir="${AGENC_HOME}/oom-snapshots" ' +
      `${quote(runtimeBin)} "$@"`,
    "    ;;",
    "esac",
    "",
  ].join("\n");
}

function decodeCanonicalMetadata(encoded) {
  try {
    const bytes = Buffer.from(encoded, "base64url");
    if (bytes.toString("base64url") !== encoded) return undefined;
    const decoded = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
    const value = JSON.parse(decoded);
    if (value === null || typeof value !== "object" || Array.isArray(value)) return undefined;
    const keys = Object.keys(value);
    const expectedKeys = value.nodeLibraryPath === undefined
      ? ["nodeBin", "runtimeBin", "agencHome"]
      : ["nodeBin", "runtimeBin", "agencHome", "nodeLibraryPath"];
    if (
      keys.length !== expectedKeys.length ||
      !expectedKeys.every((key, index) => keys[index] === key) ||
      typeof value.nodeBin !== "string" ||
      typeof value.runtimeBin !== "string" ||
      typeof value.agencHome !== "string" ||
      (value.nodeLibraryPath !== undefined && typeof value.nodeLibraryPath !== "string")
    ) return undefined;
    return {
      nodeBin: value.nodeBin,
      runtimeBin: value.runtimeBin,
      agencHome: value.agencHome,
      ...(value.nodeLibraryPath === undefined
        ? {}
        : { nodeLibraryPath: value.nodeLibraryPath }),
    };
  } catch {
    return undefined;
  }
}

function parseModern(path, content) {
  const marker = content.match(
    /^(#|rem) AgenC wrapper metadata v1: ([A-Za-z0-9_-]+)\r?$/mu,
  );
  if (marker === null) return undefined;
  const kind = marker[1] === "rem" ? "cmd" : "posix";
  const values = decodeCanonicalMetadata(marker[2]);
  if (values === undefined) return undefined;
  try {
    const wrapper = { kind, path, ...values };
    if (renderGeneratedWrapperContent(wrapper) === content) return wrapper;
    if (
      values.nodeLibraryPath === undefined &&
      renderPrePrivateNodeWrapperContent(wrapper) === content
    ) return wrapper;
    return undefined;
  } catch {
    return undefined;
  }
}

function parseLegacy(path, content) {
  const posix = content.match(
    /^#!\/bin\/sh\n# Generated by AgenC install\.sh — rewritten on every install\/upgrade\.\nexport AGENC_HOME="\$\{AGENC_HOME:-([^}"\n]+)\}"\nexec "([^"\n]+)" "([^"\n]+)" "\$@"\n$/u,
  );
  if (posix !== null) {
    const values = { agencHome: posix[1], nodeBin: posix[2], runtimeBin: posix[3] };
    try {
      validateValues("posix", values);
      return { kind: "posix", path, ...values };
    } catch {
      return undefined;
    }
  }
  // 0.6.2 development main briefly emitted this exact full-file wrapper before
  // activation ownership became canonical. Accepting only a byte-for-byte
  // reconstruction preserves upgrades from that surface without turning the
  // historical marker into a general ownership oracle.
  const oomPosix = content.match(
    /^#!\/bin\/sh\n# Generated by AgenC install\.sh — rewritten on every install\/upgrade\.\nexport AGENC_HOME="\$\{AGENC_HOME:-([^}"\n]+)\}"\n[\s\S]*\nexec "([^"\n]+)" "([^"\n]+)" "\$@"\n$/u,
  );
  if (oomPosix !== null) {
    const values = {
      agencHome: oomPosix[1],
      nodeBin: oomPosix[2],
      runtimeBin: oomPosix[3],
    };
    try {
      validateValues("posix", values);
      if (renderLegacyOomPosixWrapper(values) === content) {
        return { kind: "posix", path, ...values };
      }
    } catch {
      return undefined;
    }
  }
  const cmd = content.match(
    /^@echo off(\r?\n)rem Generated by AgenC install\.ps1 - rewritten on every install\/upgrade\.\1if not defined AGENC_HOME set "AGENC_HOME=([^"\r\n]+)"\1"([^"\r\n]+)" "([^"\r\n]+)" %\*\1$/u,
  );
  if (cmd === null) return undefined;
  const values = { agencHome: cmd[2], nodeBin: cmd[3], runtimeBin: cmd[4] };
  try {
    validateValues("cmd", values);
    return { kind: "cmd", path, ...values };
  } catch {
    return undefined;
  }
}

export function parseGeneratedWrapperContent(path, content) {
  if (
    typeof path !== "string" || !isAbsolute(path) ||
    typeof content !== "string" || Buffer.byteLength(content, "utf8") > GENERATED_WRAPPER_MAX_BYTES
  ) return null;
  return parseModern(path, content) ?? parseLegacy(path, content) ?? null;
}
