// Byte-canonical standalone-installer wrapper contract shared by the runtime
// updater and both embedded installers. Parsing is deliberately full-file:
// marker substrings must never grant ownership of a user-authored executable.

import { isAbsolute } from "node:path";

export const GENERATED_WRAPPER_MAX_BYTES = 64 * 1024;
const POSIX_WRAPPER_SIGNATURE = "Generated by AgenC install.sh";
const CMD_WRAPPER_SIGNATURE = "Generated by AgenC install.ps1";
const WRAPPER_METADATA_PREFIX = "AgenC wrapper metadata v1:";

function validateValues(kind, values) {
  if (!values || typeof values !== "object") {
    throw new TypeError("wrapper values must be an object");
  }
  for (const label of ["nodeBin", "runtimeBin", "agencHome"]) {
    const value = values[label];
    if (typeof value !== "string") throw new TypeError(`wrapper ${label} must be a string`);
    if (value.includes("\0")) throw new Error(`wrapper ${label} contains NUL`);
    if (kind === "cmd" && /["\r\n]/u.test(value)) {
      throw new Error(`Windows wrapper ${label} contains an unsupported character`);
    }
  }
  if (!isAbsolute(values.agencHome)) {
    throw new Error("wrapper AGENC_HOME must be an absolute path");
  }
}

function metadataFor(values) {
  return Buffer.from(JSON.stringify({
    nodeBin: values.nodeBin,
    runtimeBin: values.runtimeBin,
    agencHome: values.agencHome,
  }), "utf8").toString("base64url");
}

export function renderGeneratedWrapperContent({ kind, nodeBin, runtimeBin, agencHome }) {
  if (kind !== "posix" && kind !== "cmd") {
    throw new TypeError(`unsupported wrapper kind: ${String(kind)}`);
  }
  const values = { nodeBin, runtimeBin, agencHome };
  validateValues(kind, values);
  const metadata = metadataFor(values);
  if (kind === "cmd") {
    const batch = (value) => value.replaceAll("%", "%%");
    return [
      "@echo off",
      "setlocal DisableDelayedExpansion",
      `rem ${CMD_WRAPPER_SIGNATURE} - rewritten on every install/upgrade.`,
      `rem ${WRAPPER_METADATA_PREFIX} ${metadata}`,
      `if not defined AGENC_HOME set "AGENC_HOME=${batch(agencHome)}"`,
      `"${batch(nodeBin)}" "${batch(runtimeBin)}" %*`,
      "",
    ].join("\r\n");
  }
  const quote = (value) => `'${value.replaceAll("'", `'"'"'`)}'`;
  return [
    "#!/bin/sh",
    `# ${POSIX_WRAPPER_SIGNATURE} — rewritten on every install/upgrade.`,
    `# ${WRAPPER_METADATA_PREFIX} ${metadata}`,
    'if [ -z "${AGENC_HOME:-}" ]; then',
    `  export AGENC_HOME=${quote(agencHome)}`,
    "fi",
    `exec ${quote(nodeBin)} ${quote(runtimeBin)} "$@"`,
    "",
  ].join("\n");
}

function decodeCanonicalMetadata(encoded) {
  try {
    const bytes = Buffer.from(encoded, "base64url");
    if (bytes.toString("base64url") !== encoded) return undefined;
    const decoded = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
    const value = JSON.parse(decoded);
    if (value === null || typeof value !== "object" || Array.isArray(value)) return undefined;
    if (
      Object.keys(value).length !== 3 ||
      typeof value.nodeBin !== "string" ||
      typeof value.runtimeBin !== "string" ||
      typeof value.agencHome !== "string"
    ) return undefined;
    return {
      nodeBin: value.nodeBin,
      runtimeBin: value.runtimeBin,
      agencHome: value.agencHome,
    };
  } catch {
    return undefined;
  }
}

function parseModern(path, content) {
  const marker = content.match(
    /^(#|rem) AgenC wrapper metadata v1: ([A-Za-z0-9_-]+)\r?$/mu,
  );
  if (marker === null) return undefined;
  const kind = marker[1] === "rem" ? "cmd" : "posix";
  const values = decodeCanonicalMetadata(marker[2]);
  if (values === undefined) return undefined;
  try {
    const wrapper = { kind, path, ...values };
    return renderGeneratedWrapperContent(wrapper) === content ? wrapper : undefined;
  } catch {
    return undefined;
  }
}

function parseLegacy(path, content) {
  const posix = content.match(
    /^#!\/bin\/sh\n# Generated by AgenC install\.sh — rewritten on every install\/upgrade\.\nexport AGENC_HOME="\$\{AGENC_HOME:-([^}"\n]+)\}"\nexec "([^"\n]+)" "([^"\n]+)" "\$@"\n$/u,
  );
  if (posix !== null) {
    const values = { agencHome: posix[1], nodeBin: posix[2], runtimeBin: posix[3] };
    try {
      validateValues("posix", values);
      return { kind: "posix", path, ...values };
    } catch {
      return undefined;
    }
  }
  const cmd = content.match(
    /^@echo off(\r?\n)rem Generated by AgenC install\.ps1 - rewritten on every install\/upgrade\.\1if not defined AGENC_HOME set "AGENC_HOME=([^"\r\n]+)"\1"([^"\r\n]+)" "([^"\r\n]+)" %\*\1$/u,
  );
  if (cmd === null) return undefined;
  const values = { agencHome: cmd[2], nodeBin: cmd[3], runtimeBin: cmd[4] };
  try {
    validateValues("cmd", values);
    return { kind: "cmd", path, ...values };
  } catch {
    return undefined;
  }
}

export function parseGeneratedWrapperContent(path, content) {
  if (
    typeof path !== "string" || !isAbsolute(path) ||
    typeof content !== "string" || Buffer.byteLength(content, "utf8") > GENERATED_WRAPPER_MAX_BYTES
  ) return null;
  return parseModern(path, content) ?? parseLegacy(path, content) ?? null;
}
