/**
 * ContextSuggestions
 *
 * Ported from upstream. Renders a list of token-savings suggestions
 * generated by the host (e.g. "drop unused MCP servers, save ~12k
 * tokens"). The widget is purely presentational — the host computes
 * `suggestions` from its context analysis and passes them in.
 */

import React from 'react'

import { Box, Text } from '../ink-public.js'
import { StatusIcon } from '../design-system/StatusIcon.js'

const ARROW_RIGHT = '→'

export type ContextSuggestionSeverity =
  | 'success'
  | 'error'
  | 'warning'
  | 'info'
  | 'pending'

export interface ContextSuggestion {
  /** One-line headline shown next to the severity icon. */
  readonly title: string
  /** Long-form explanation surfaced below the title. */
  readonly detail: string
  /** Visual severity — drives the StatusIcon glyph and color. */
  readonly severity: ContextSuggestionSeverity
  /** Estimated tokens recoverable if the suggestion is applied. */
  readonly savingsTokens?: number
}

export interface ContextSuggestionsProps {
  readonly suggestions: readonly ContextSuggestion[]
  /**
   * Optional formatter for token counts. Defaults to a compact
   * `1.2k` / `3.4M` form.
   */
  readonly formatTokens?: (tokens: number) => string
}

function defaultFormatTokens(tokens: number): string {
  if (!Number.isFinite(tokens) || tokens <= 0) {
    return '0'
  }
  if (tokens < 1_000) {
    return String(Math.round(tokens))
  }
  if (tokens < 1_000_000) {
    return `${(tokens / 1_000).toFixed(1)}k`
  }
  return `${(tokens / 1_000_000).toFixed(2)}M`
}

export function ContextSuggestions({
  suggestions,
  formatTokens = defaultFormatTokens,
}: ContextSuggestionsProps): React.ReactElement | null {
  if (suggestions.length === 0) {
    return null
  }
  return (
    <Box flexDirection="column" marginTop={1}>
      <Text bold={true}>Suggestions</Text>
      {suggestions.map((suggestion, i) => (
        <Box
          key={`${suggestion.title}-${i}`}
          flexDirection="column"
          marginTop={i === 0 ? 0 : 1}
        >
          <Box>
            <StatusIcon status={suggestion.severity} withSpace={true} />
            <Text bold={true}>{suggestion.title}</Text>
            {suggestion.savingsTokens ? (
              <Text dimColor={true}>
                {` ${ARROW_RIGHT} save ~${formatTokens(suggestion.savingsTokens)}`}
              </Text>
            ) : null}
          </Box>
          <Box marginLeft={2}>
            <Text dimColor={true}>{suggestion.detail}</Text>
          </Box>
        </Box>
      ))}
    </Box>
  )
}

export default ContextSuggestions
