import { readFileSync } from "node:fs";
import { isAbsolute } from "node:path";

export const APPARMOR_RESTRICT_UNPRIVILEGED_USERNS_PATH =
  "/proc/sys/kernel/apparmor_restrict_unprivileged_userns";
export const AGENC_APPARMOR_PROFILE_PATH =
  "/etc/apparmor.d/agenc-native-userns";

const APPARMOR_USERNS_FAILURE_PATTERNS = [
  /loopback:\s+Failed RTM_NEW(?:ADDR|LINK):\s+Operation not permitted/iu,
  /setting up uid map:\s+Permission denied/iu,
  /setting up uid map:\s+Operation not permitted/iu,
] as const;

export const APPARMOR_USERNS_REMEDIATION =
  "Ubuntu AppArmor is restricting the user namespace bubblewrap needs. " +
  "Install AgenC's narrow per-command profile with: " +
  `agenc doctor --apparmor-profile | sudo tee ${AGENC_APPARMOR_PROFILE_PATH} >/dev/null && ` +
  `sudo apparmor_parser -r ${AGENC_APPARMOR_PROFILE_PATH}; ` +
  "then run `agenc doctor` again.";

export function readAppArmorUserNamespaceRestriction(): string | null {
  try {
    return readFileSync(
      APPARMOR_RESTRICT_UNPRIVILEGED_USERNS_PATH,
      "utf8",
    ).trim();
  } catch {
    return null;
  }
}

export function isAppArmorUserNamespaceDenial(
  diagnostic: string,
  restriction = readAppArmorUserNamespaceRestriction(),
): boolean {
  return (
    restriction === "1" &&
    APPARMOR_USERNS_FAILURE_PATTERNS.some((pattern) => pattern.test(diagnostic))
  );
}

function quoteAppArmorAttachment(path: string): string {
  if (
    !isAbsolute(path) ||
    path.includes("\0") ||
    path.includes("\r") ||
    path.includes("\n")
  ) {
    throw new Error(
      "AppArmor profile attachment must be an absolute single-line path",
    );
  }
  return `"${path.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/**
 * Render the Ubuntu-supported per-application user-namespace exception.
 *
 * The attachment is the byte-canonical standalone installer wrapper that
 * Doctor has already proven launches this exact runtime. The profile otherwise
 * remains unconfined, matching Ubuntu's packaged application profiles, and
 * grants only the userns feature AppArmor restricts.
 */
export function renderAgenCAppArmorProfile(wrapperPath: string): string {
  const attachment = quoteAppArmorAttachment(wrapperPath);
  return [
    "# Generated by `agenc doctor --apparmor-profile`.",
    "# Allows AgenC's bubblewrap sandbox to create its required user namespace.",
    "abi <abi/4.0>,",
    "include <tunables/global>",
    "",
    `profile agenc-native-userns ${attachment} flags=(unconfined) {`,
    "  userns,",
    "",
    "  include if exists <local/agenc-native-userns>",
    "}",
    "",
  ].join("\n");
}
