// @ts-nocheck
// Stub — feature-gated path; real implementation lives in openclaude upstream.
const __stubProxy: any = new Proxy(function __stub(..._args: any[]): any { return __stubProxy; }, {
  get(target, prop) {
    if (prop === 'then') return undefined;
    if (prop === Symbol.toPrimitive) return () => '';
    if (prop === Symbol.iterator) return function* () {};
    if (prop === Symbol.asyncIterator) return async function* () {};
    if (prop === 'length') return 0;
    if (prop === 'size') return 0;
    if (prop === 'cache') return new Map();
    return __stubProxy;
  },
  apply() { return __stubProxy; },
  construct() { return __stubProxy; },
  has() { return true; },
  set() { return true; },
});
export type ApiKeySource<_T = any> = any;
export const ApiKeySource: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type OrgValidationResult<_T = any> = any;
export const OrgValidationResult: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type UserAccountInfo<_T = any> = any;
export const UserAccountInfo: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type calculateApiKeyHelperTTL<_T = any> = any;
export const calculateApiKeyHelperTTL: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type checkAndRefreshOAuthTokenIfNeeded<_T = any> = any;
export const checkAndRefreshOAuthTokenIfNeeded: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type checkGcpCredentialsValid<_T = any> = any;
export const checkGcpCredentialsValid: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearApiKeyHelperCache<_T = any> = any;
export const clearApiKeyHelperCache: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearAwsCredentialsCache<_T = any> = any;
export const clearAwsCredentialsCache: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearGcpCredentialsCache<_T = any> = any;
export const clearGcpCredentialsCache: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearOAuthTokenCache<_T = any> = any;
export const clearOAuthTokenCache: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getAccountInformation<_T = any> = any;
export const getAccountInformation: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getAnthropicApiKey<_T = any> = any;
export const getAnthropicApiKey: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getAnthropicApiKeyWithSource<_T = any> = any;
export const getAnthropicApiKeyWithSource: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getApiKeyFromApiKeyHelper<_T = any> = any;
export const getApiKeyFromApiKeyHelper: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getApiKeyFromApiKeyHelperCached<_T = any> = any;
export const getApiKeyFromApiKeyHelperCached: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getApiKeyFromConfigOrMacOSKeychain<_T = any> = any;
export const getApiKeyFromConfigOrMacOSKeychain: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getApiKeyHelperElapsedMs<_T = any> = any;
export const getApiKeyHelperElapsedMs: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getAuthTokenSource<_T = any> = any;
export const getAuthTokenSource: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getClaudeAIOAuthTokens<_T = any> = any;
export const getClaudeAIOAuthTokens: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getClaudeAIOAuthTokensAsync<_T = any> = any;
export const getClaudeAIOAuthTokensAsync: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getConfiguredApiKeyHelper<_T = any> = any;
export const getConfiguredApiKeyHelper: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getOauthAccountInfo<_T = any> = any;
export const getOauthAccountInfo: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getOtelHeadersFromHelper<_T = any> = any;
export const getOtelHeadersFromHelper: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getRateLimitTier<_T = any> = any;
export const getRateLimitTier: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSubscriptionName<_T = any> = any;
export const getSubscriptionName: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSubscriptionType<_T = any> = any;
export const getSubscriptionType: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type handleOAuth401Error<_T = any> = any;
export const handleOAuth401Error: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type hasAnthropicApiKeyAuth<_T = any> = any;
export const hasAnthropicApiKeyAuth: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type hasOpusAccess<_T = any> = any;
export const hasOpusAccess: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type hasProfileScope<_T = any> = any;
export const hasProfileScope: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type is1PApiCustomer<_T = any> = any;
export const is1PApiCustomer: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isAnthropicAuthEnabled<_T = any> = any;
export const isAnthropicAuthEnabled: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isAwsAuthRefreshFromProjectSettings<_T = any> = any;
export const isAwsAuthRefreshFromProjectSettings: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isAwsCredentialExportFromProjectSettings<_T = any> = any;
export const isAwsCredentialExportFromProjectSettings: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isClaudeAISubscriber<_T = any> = any;
export const isClaudeAISubscriber: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isConsumerSubscriber<_T = any> = any;
export const isConsumerSubscriber: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isCustomApiKeyApproved<_T = any> = any;
export const isCustomApiKeyApproved: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isEnterpriseSubscriber<_T = any> = any;
export const isEnterpriseSubscriber: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isGcpAuthRefreshFromProjectSettings<_T = any> = any;
export const isGcpAuthRefreshFromProjectSettings: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isMaxSubscriber<_T = any> = any;
export const isMaxSubscriber: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isOtelHeadersHelperFromProjectOrLocalSettings<_T = any> = any;
export const isOtelHeadersHelperFromProjectOrLocalSettings: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isOverageProvisioningAllowed<_T = any> = any;
export const isOverageProvisioningAllowed: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isProSubscriber<_T = any> = any;
export const isProSubscriber: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isTeamPremiumSubscriber<_T = any> = any;
export const isTeamPremiumSubscriber: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isTeamSubscriber<_T = any> = any;
export const isTeamSubscriber: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isUsing3PServices<_T = any> = any;
export const isUsing3PServices: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type prefetchApiKeyFromApiKeyHelperIfSafe<_T = any> = any;
export const prefetchApiKeyFromApiKeyHelperIfSafe: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type prefetchAwsCredentialsAndBedRockInfoIfSafe<_T = any> = any;
export const prefetchAwsCredentialsAndBedRockInfoIfSafe: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type prefetchGcpCredentialsIfSafe<_T = any> = any;
export const prefetchGcpCredentialsIfSafe: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type refreshAndGetAwsCredentials<_T = any> = any;
export const refreshAndGetAwsCredentials: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type refreshAwsAuth<_T = any> = any;
export const refreshAwsAuth: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type refreshGcpAuth<_T = any> = any;
export const refreshGcpAuth: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type refreshGcpCredentialsIfNeeded<_T = any> = any;
export const refreshGcpCredentialsIfNeeded: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type removeApiKey<_T = any> = any;
export const removeApiKey: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type saveApiKey<_T = any> = any;
export const saveApiKey: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type saveOAuthTokensIfNeeded<_T = any> = any;
export const saveOAuthTokensIfNeeded: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type validateForceLoginOrg<_T = any> = any;
export const validateForceLoginOrg: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
