// Runtime-facing typed bridge to the launcher's canonical release trust policy.

export {
  MAX_RUNTIME_ARTIFACT_BYTES,
  MAX_RUNTIME_ATTESTATION_BYTES,
  MAX_RUNTIME_MANIFEST_BYTES,
  FROZEN_LEGACY_RUNTIME_VERSION,
  MINIMUM_PRIVATE_NODE_RUNTIME_VERSION,
  PRIVATE_NODE_BOOTSTRAP_RELEASE_TAG,
  OFFICIAL_RELEASE_WORKFLOW,
  OFFICIAL_RELEASE_REPOSITORY,
  OFFICIAL_SOURCE_REPOSITORY,
  PINNED_GITHUB_CLI_ARTIFACTS,
  PINNED_GITHUB_CLI_VERSION,
  RUNTIME_ATTESTATION_POLICY,
  RUNTIME_MANIFEST_TRUST_MODES,
  canonicalRuntimeAttestationVerificationArgs,
  canonicalLocalFileUrlToPath,
  canonicalRuntimeArtifactName,
  requireRuntimeManifestTrustMode,
  requireSupportedRuntimeVersion,
  validateRuntimeReleaseManifest,
  type RuntimeManifestTrustMode,
  type RuntimeReleaseArtifact,
  type RuntimeReleaseManifest,
} from "../../../packages/agenc/lib/runtime-release-contract.mjs";
