// @ts-nocheck
// Stub — feature-gated path; real implementation lives in openclaude upstream.
const __stubProxy: any = new Proxy(function __stub(..._args: any[]): any { return __stubProxy; }, {
  get(target, prop) {
    if (prop === 'then') return undefined;
    if (prop === Symbol.toPrimitive) return () => '';
    if (prop === Symbol.iterator) return function* () {};
    if (prop === Symbol.asyncIterator) return async function* () {};
    if (prop === 'length') return 0;
    if (prop === 'size') return 0;
    if (prop === 'cache') return new Map();
    return __stubProxy;
  },
  apply() { return __stubProxy; },
  construct() { return __stubProxy; },
  has() { return true; },
  set() { return true; },
});
export type IdleNotificationMessage<_T = any> = any;
export const IdleNotificationMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type ModeSetRequestMessage<_T = any> = any;
export const ModeSetRequestMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type ModeSetRequestMessageSchema<_T = any> = any;
export const ModeSetRequestMessageSchema: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type PermissionRequestMessage<_T = any> = any;
export const PermissionRequestMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type PermissionResponseMessage<_T = any> = any;
export const PermissionResponseMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type PlanApprovalRequestMessage<_T = any> = any;
export const PlanApprovalRequestMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type PlanApprovalRequestMessageSchema<_T = any> = any;
export const PlanApprovalRequestMessageSchema: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type PlanApprovalResponseMessage<_T = any> = any;
export const PlanApprovalResponseMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type PlanApprovalResponseMessageSchema<_T = any> = any;
export const PlanApprovalResponseMessageSchema: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type SandboxPermissionRequestMessage<_T = any> = any;
export const SandboxPermissionRequestMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type SandboxPermissionResponseMessage<_T = any> = any;
export const SandboxPermissionResponseMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type ShutdownApprovedMessage<_T = any> = any;
export const ShutdownApprovedMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type ShutdownApprovedMessageSchema<_T = any> = any;
export const ShutdownApprovedMessageSchema: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type ShutdownRejectedMessage<_T = any> = any;
export const ShutdownRejectedMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type ShutdownRejectedMessageSchema<_T = any> = any;
export const ShutdownRejectedMessageSchema: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type ShutdownRequestMessage<_T = any> = any;
export const ShutdownRequestMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type ShutdownRequestMessageSchema<_T = any> = any;
export const ShutdownRequestMessageSchema: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type TaskAssignmentMessage<_T = any> = any;
export const TaskAssignmentMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type TeamPermissionUpdateMessage<_T = any> = any;
export const TeamPermissionUpdateMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type TeammateMessage<_T = any> = any;
export const TeammateMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearMailbox<_T = any> = any;
export const clearMailbox: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type createIdleNotification<_T = any> = any;
export const createIdleNotification: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type createModeSetRequestMessage<_T = any> = any;
export const createModeSetRequestMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type createPermissionRequestMessage<_T = any> = any;
export const createPermissionRequestMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type createPermissionResponseMessage<_T = any> = any;
export const createPermissionResponseMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type createSandboxPermissionRequestMessage<_T = any> = any;
export const createSandboxPermissionRequestMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type createSandboxPermissionResponseMessage<_T = any> = any;
export const createSandboxPermissionResponseMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type createShutdownApprovedMessage<_T = any> = any;
export const createShutdownApprovedMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type createShutdownRejectedMessage<_T = any> = any;
export const createShutdownRejectedMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type createShutdownRequestMessage<_T = any> = any;
export const createShutdownRequestMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type formatTeammateMessages<_T = any> = any;
export const formatTeammateMessages: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getInboxPath<_T = any> = any;
export const getInboxPath: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getLastPeerDmSummary<_T = any> = any;
export const getLastPeerDmSummary: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isIdleNotification<_T = any> = any;
export const isIdleNotification: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isModeSetRequest<_T = any> = any;
export const isModeSetRequest: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isPermissionRequest<_T = any> = any;
export const isPermissionRequest: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isPermissionResponse<_T = any> = any;
export const isPermissionResponse: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isPlanApprovalRequest<_T = any> = any;
export const isPlanApprovalRequest: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isPlanApprovalResponse<_T = any> = any;
export const isPlanApprovalResponse: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isSandboxPermissionRequest<_T = any> = any;
export const isSandboxPermissionRequest: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isSandboxPermissionResponse<_T = any> = any;
export const isSandboxPermissionResponse: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isShutdownApproved<_T = any> = any;
export const isShutdownApproved: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isShutdownRejected<_T = any> = any;
export const isShutdownRejected: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isShutdownRequest<_T = any> = any;
export const isShutdownRequest: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isStructuredProtocolMessage<_T = any> = any;
export const isStructuredProtocolMessage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isTaskAssignment<_T = any> = any;
export const isTaskAssignment: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isTeamPermissionUpdate<_T = any> = any;
export const isTeamPermissionUpdate: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type markMessageAsReadByIndex<_T = any> = any;
export const markMessageAsReadByIndex: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type markMessagesAsRead<_T = any> = any;
export const markMessagesAsRead: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type markMessagesAsReadByPredicate<_T = any> = any;
export const markMessagesAsReadByPredicate: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type readMailbox<_T = any> = any;
export const readMailbox: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type readUnreadMessages<_T = any> = any;
export const readUnreadMessages: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type sendShutdownRequestToMailbox<_T = any> = any;
export const sendShutdownRequestToMailbox: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type writeToMailbox<_T = any> = any;
export const writeToMailbox: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
