/** Standalone aliases of the daemon-owned routine wire contract. */
export type {
  RoutineSchedule,
  RoutineRunStatus,
  RoutineRun,
  RoutineCreateParams,
  RoutineConfig,
  RoutineWorkspaceExpectation,
  Routine,
  RoutineIdParams,
  RoutineUpdateParams,
  RoutineDeleteParams,
  RoutineRunParams,
  RoutineRunsParams,
  RoutineCancelParams,
  RoutineCapabilities,
  RoutineResult,
  RoutineRunResult,
  RoutineListResult,
  RoutineRunsResult,
  RoutineDeleteResult,
  RoutineUpdatedEvent,
} from "./protocol-wire.generated.js";
