// @generated from runtime/src/app-server/protocol/index.ts. Do not edit.
// This file is automatically generated from the daemon protocol.
// Verify with: npm --workspace=@tetsuo-ai/runtime run check:sdk-generated-types

type TranscriptV2JsonPrimitive = string | number | boolean | null;
type TranscriptV2JsonValue =
  | TranscriptV2JsonPrimitive
  | readonly TranscriptV2JsonValue[]
  | TranscriptV2JsonObject;
type JsonValue = TranscriptV2JsonValue;
interface TranscriptV2JsonObject {
  readonly [key: string]: TranscriptV2JsonValue | undefined;
}

export interface SessionTranscriptV2Message extends TranscriptV2JsonObject {
  readonly messageId: string;
  readonly commitEventId: string;
  readonly role: "user" | "assistant";
  readonly text: string;
  /** Full UTF-8 text when the snapshot substitutes a bounded reference. */
  readonly textArtifact?: { readonly id: string; readonly digest: string; readonly size: number; readonly mimeType: "text/plain" };
  readonly turnId?: string;
  readonly clientMessageId?: string;
  /** Zero only for migrated response_item rows that predate event sequencing. */
  readonly committedSequence: number;
}

export interface SessionTranscriptV2ActiveTurn extends TranscriptV2JsonObject {
  readonly turnId: string;
  readonly clientMessageId?: string;
}

export interface SessionTranscriptV2TurnResult extends TranscriptV2JsonObject {
  readonly turnId: string;
  /** Durable sequence of the turn's terminal event; anchors placement. */
  readonly committedSequence: number;
  readonly outcome: "completed" | "aborted" | "errored";
  readonly durationMs?: number;
  readonly inputTokens?: number;
  readonly outputTokens?: number;
  readonly totalTokens?: number;
  readonly model?: string;
  readonly provider?: string;
}

export interface DisplayAttachment extends TranscriptV2JsonObject {
  readonly id: string;
  readonly kind: "chart" | "table" | "image" | "file";
  readonly title: string;
  readonly mimeType: string;
  readonly size: number;
  readonly digest: string;
  readonly data?: JsonValue;
}

export interface SessionTranscriptV2Event extends TranscriptV2JsonObject {
  readonly eventId: string;
  readonly committedSequence: number;
  /**
   * `approval_denied` names a call the user denied (`callId`, `toolName`,
   * `stage`, and `input` bounded to the fields that identify its target).
   */
  readonly type: "token_count" | "session_usage" | "turn_failed" | "turn_aborted" | "approval_denied" | "tool_call_completed";
  readonly payload: {
    readonly runId?: string;
    readonly sequence?: number;
    readonly costUsd?: number;
    readonly heldCostUsd?: number;
    readonly inputTokens?: number;
    readonly outputTokens?: number;
    readonly modelCalls?: number;
    readonly hasUnknownCost?: boolean;
    readonly models?: readonly {
      readonly model: string;
      readonly provider?: string;
      readonly costUsd: number;
      readonly heldCostUsd: number;
      readonly inputTokens: number;
      readonly outputTokens: number;
      readonly totalTokens: number;
      readonly modelCalls: number;
      readonly hasUnknownCost: boolean;
    }[];
    readonly agents?: readonly {
      readonly runId: string;
      readonly costUsd: number;
      readonly heldCostUsd: number;
      readonly inputTokens: number;
      readonly outputTokens: number;
      readonly totalTokens: number;
      readonly modelCalls: number;
      readonly hasUnknownCost: boolean;
    }[];
    readonly promptTokens?: number;
    readonly completionTokens?: number;
    readonly totalTokens?: number;
    readonly cachedInputTokens?: number;
    readonly cacheCreationInputTokens?: number;
    readonly reasoningOutputTokens?: number;
    readonly webSearchRequests?: number;
    readonly model?: string;
    readonly provider?: string;
    readonly turnId?: string;
    readonly code?: string;
    readonly message?: string;
    readonly reason?: string;
    readonly callId?: string;
    readonly toolName?: string;
    readonly result?: string;
    readonly isError?: boolean;
    readonly input?: { readonly [key: string]: string };
    readonly stage?: "before_execution" | "sandbox_escalation";
    readonly displayAttachments?: readonly DisplayAttachment[];
  };
}

export interface SessionTranscriptV2Result extends TranscriptV2JsonObject {
  readonly schemaVersion: 2;
  readonly sessionId: string;
  readonly runId: string;
  readonly historyEpoch: string;
  readonly asOfSequence: number;
  readonly messages: readonly SessionTranscriptV2Message[];
  /** Older rows were omitted to keep the response within transport limits. */
  readonly truncated?: boolean;
  readonly activeTurn?: SessionTranscriptV2ActiveTurn;
  readonly turnResults?: readonly SessionTranscriptV2TurnResult[];
  readonly events?: readonly SessionTranscriptV2Event[];
  /**
   * Plan-mode state at `asOfSequence`, taken from the latest
   * run_runtime_settings_changed event in the same history the transcript was
   * rebuilt from. Absent when that history holds no settings event. A client
   * that receives it needs no run-journal replay to learn it.
   */
  readonly planModeActive?: boolean;
  readonly planModeSequence?: number;
}
