// @generated from runtime/src/app-server/protocol/index.ts. Do not edit.
// This file is automatically generated from the daemon protocol.
// Verify with: npm --workspace=@tetsuo-ai/runtime run check:sdk-generated-types

type TranscriptV2JsonPrimitive = string | number | boolean | null;
type TranscriptV2JsonValue =
  | TranscriptV2JsonPrimitive
  | readonly TranscriptV2JsonValue[]
  | TranscriptV2JsonObject;
interface TranscriptV2JsonObject {
  readonly [key: string]: TranscriptV2JsonValue | undefined;
}

export interface SessionTranscriptV2Message extends TranscriptV2JsonObject {
  readonly messageId: string;
  readonly commitEventId: string;
  readonly role: "user" | "assistant";
  readonly text: string;
  readonly turnId?: string;
  readonly clientMessageId?: string;
  /** Zero only for migrated response_item rows that predate event sequencing. */
  readonly committedSequence: number;
}

export interface SessionTranscriptV2ActiveTurn extends TranscriptV2JsonObject {
  readonly turnId: string;
  readonly clientMessageId?: string;
}

export interface SessionTranscriptV2TurnResult extends TranscriptV2JsonObject {
  readonly turnId: string;
  /** Durable sequence of the turn's terminal event; anchors placement. */
  readonly committedSequence: number;
  readonly outcome: "completed" | "aborted" | "errored";
  readonly durationMs?: number;
  readonly inputTokens?: number;
  readonly outputTokens?: number;
  readonly totalTokens?: number;
  readonly model?: string;
  readonly provider?: string;
}

export interface SessionTranscriptV2Result extends TranscriptV2JsonObject {
  readonly schemaVersion: 2;
  readonly sessionId: string;
  readonly runId: string;
  readonly historyEpoch: string;
  readonly asOfSequence: number;
  readonly messages: readonly SessionTranscriptV2Message[];
  readonly activeTurn?: SessionTranscriptV2ActiveTurn;
  readonly turnResults?: readonly SessionTranscriptV2TurnResult[];
}
