/**
 * @tetsuo-ai/runtime - Agent runtime infrastructure for AgenC
 *
 * This is the main entry point for the @tetsuo-ai/runtime package.
 * It re-exports all public APIs including agent management, types,
 * utilities, and key constants from @tetsuo-ai/sdk.
 *
 * @packageDocumentation
 */

// Re-export SDK constants for convenience
export {
  PROGRAM_ID,
  PRIVACY_CASH_PROGRAM_ID,
  DEVNET_RPC,
  MAINNET_RPC,
  SEEDS,
  HASH_SIZE,
  RESULT_DATA_SIZE,
  U64_SIZE,
  DISCRIMINATOR_SIZE,
  OUTPUT_FIELD_COUNT,
  PROOF_SIZE_BYTES,
  PERCENT_BASE,
  DEFAULT_FEE_PERCENT,
  BPS_BASE,
  BID_ID_MAX_LENGTH,
  MARKETPLACE_ID_PATTERN,
  DEFAULT_WEIGHTED_SCORE_WEIGHTS,
  canonicalizeMarketplaceId,
  validateMarketplaceId,
  isValidBps,
  TaskState,
  type TaskStatus,
} from "@tetsuo-ai/sdk";

// IDL and program creation
export {
  IDL,
  type AgencCoordination,
  createProgram,
  createReadOnlyProgram,
} from "./idl.js";

export const VERSION = "0.2.0";

// Runtime class
export { AgentRuntime } from "./runtime.js";

// Types (protocol, errors, wallet, config) — all via types barrel
export {
  // Protocol types
  ProtocolConfig,
  parseProtocolConfig,
  MAX_MULTISIG_OWNERS,
  // Error constants
  RuntimeErrorCodes,
  AnchorErrorCodes,
  // Error types
  type RuntimeErrorCode,
  type AnchorErrorCode,
  type AnchorErrorName,
  type ParsedAnchorError,
  // Error classes
  RuntimeError,
  AgentNotRegisteredError,
  AgentAlreadyRegisteredError,
  ValidationError,
  RateLimitError,
  InsufficientStakeError,
  ActiveTasksError,
  PendingDisputeVotesError,
  RecentVoteActivityError,
  TaskNotFoundError,
  TaskNotClaimableError,
  TaskExecutionError,
  TaskSubmissionError,
  ExecutorStateError,
  TaskTimeoutError,
  // Error helper functions
  isAnchorError,
  parseAnchorError,
  getAnchorErrorName,
  getAnchorErrorMessage,
  isRuntimeError,
  // Agent constants
  AgentCapabilities,
  AGENT_REGISTRATION_SIZE,
  AGENT_ID_LENGTH,
  MAX_ENDPOINT_LENGTH,
  MAX_METADATA_URI_LENGTH,
  MAX_REPUTATION,
  MAX_U8,
  CAPABILITY_NAMES,
  // Agent enum
  AgentStatus,
  // Agent functions
  agentStatusToString,
  isValidAgentStatus,
  Capability,
  combineCapabilities,
  hasCapability,
  getCapabilityNames,
  createCapabilityMask,
  parseAgentState,
  computeRateLimitState,
  // PDA derivation helpers
  deriveAgentPda,
  deriveProtocolPda,
  findAgentPda,
  findProtocolPda,
  deriveAuthorityVotePda,
  findAuthorityVotePda,
  // Event subscriptions
  subscribeToAgentRegistered,
  subscribeToAgentUpdated,
  subscribeToAgentDeregistered,
  subscribeToAgentSuspended,
  subscribeToAgentUnsuspended,
  subscribeToAllAgentEvents,
  // AgentManager class
  AgentManager,
  // Agent types
  type AgentCapability,
  type CapabilityName,
  type AgentState,
  type AgentRegistrationParams,
  type AgentUpdateParams,
  type RateLimitState,
  type AgentRegisteredEvent,
  type AgentUpdatedEvent,
  type AgentDeregisteredEvent,
  type AgentSuspendedEvent,
  type AgentUnsuspendedEvent,
  // PDA types
  type PdaWithBump,
  // Event types
  type AgentEventCallback,
  type EventSubscription,
  type AgentEventCallbacks,
  type EventSubscriptionOptions,
  // AgentManager types
  type AgentManagerConfig,
  type ProtocolConfigCacheOptions,
  type GetProtocolConfigOptions,
  // Wallet types and helpers
  type Wallet,
  type SignMessageWallet,
  KeypairFileError,
  ensureWallet,
  keypairToWallet,
  loadKeypairFromFile,
  loadKeypairFromFileSync,
  getDefaultKeypairPath,
  loadDefaultKeypair,
  // AgentRuntime types
  type AgentRuntimeConfig,
  isKeypair,
  // Task constants (Phase 3)
  TASK_ID_LENGTH,
  // Task enums
  OnChainTaskStatus,
  // Task functions
  taskStatusToString,
  taskTypeToString,
  parseTaskStatus,
  parseTaskType,
  parseOnChainTask,
  parseOnChainTaskClaim,
  isPrivateTask,
  isTaskExpired,
  isTaskClaimable,
  isPrivateExecutionResult,
  // Task PDA derivation
  deriveTaskPda,
  findTaskPda,
  deriveClaimPda,
  findClaimPda,
  deriveEscrowPda,
  findEscrowPda,
  // Task types
  type OnChainTask,
  type OnChainTaskClaim,
  type RawOnChainTask,
  type RawOnChainTaskClaim,
  type TaskExecutionContext,
  type TaskExecutionResult,
  type PrivateTaskExecutionResult,
  type TaskHandler,
  type DiscoveredTask,
  type TaskFilterConfig,
  type TaskScorer,
  type TaskDiscoveryConfig,
  type TaskOperationsConfig,
  type TaskCompletionAcceptedBidSettlement,
  type TaskCompletionOptions,
  type ClaimResult,
  type CompleteResult,
  type TaskExecutorConfig,
  type TaskExecutorEvents,
  type OperatingMode,
  type BatchTaskItem,
  type TaskExecutorStatus,
  // Config migration
  CURRENT_CONFIG_VERSION,
  KNOWN_CONFIG_KEYS,
  DEPRECATED_KEYS,
  ConfigMigrationError,
  configVersionToString,
  parseConfigVersion,
  compareVersions,
  migrateConfig,
  validateConfigStrict,
  buildConfigSchemaSnapshot,
  type ConfigVersion,
  type ConfigMigrationFn,
  type ConfigMigrationStep,
  type ConfigWarning,
  type ConfigValidationResult,
  type ConfigSchemaSnapshot,
} from "./types/index.js";

// Task module (Phase 3)
export {
  // TaskOperations class
  TaskOperations,
  type TaskOpsConfig,
  // Task filter functions
  matchesFilter,
  hasRequiredCapabilities,
  defaultTaskScorer,
  rankTasks,
  filterAndRank,
  // TaskDiscovery class
  TaskDiscovery,
  type TaskDiscoveryOptions,
  type TaskDiscoveryResult,
  type TaskDiscoveryListener,
  type TaskDiscoveryMode,
  // TaskExecutor class
  TaskExecutor,
} from "./task/index.js";

// Logger utilities
export { Logger, LogLevel, createLogger, silentLogger } from "./utils/index.js";

// Process utilities
export {
  runCommand,
  type RunCommandOptions,
  type RunCommandResult,
} from "./utils/index.js";

// Encoding utilities
export {
  generateAgentId,
  hexToBytes,
  bytesToHex,
  agentIdFromString,
  agentIdToString,
  agentIdToShortString,
  agentIdsEqual,
  lamportsToSol,
  solToLamports,
  bigintsToProofHash,
  proofHashToBigints,
  toAnchorBytes,
  uint8ToBase64,
  base64ToUint8,
} from "./utils/index.js";

// Validation utilities
export {
  type ValidationResult,
  validationResult,
  requireNonEmptyString,
  requireFiniteNumber,
  requireOneOf,
  requireIntRange,
} from "./utils/index.js";

// SPL Token utilities
export {
  isTokenTask,
  buildCompleteTaskTokenAccounts,
  buildResolveDisputeTokenAccounts,
  buildExpireDisputeTokenAccounts,
  buildApplyDisputeSlashTokenAccounts,
  buildCreateTaskTokenAccounts,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
} from "./utils/index.js";

// Event monitoring (Phase 2)
export {
  // Shared types
  type EventCallback,

  // Enums
  TaskType,
  ResolutionType,
  RateLimitActionType,
  RateLimitType,

  // Task events
  type TaskCreatedEvent,
  type TaskClaimedEvent,
  type TaskCompletedEvent,
  type TaskCancelledEvent,
  type DependentTaskCreatedEvent,
  type TaskEventCallbacks,
  type TaskEventFilterOptions,
  subscribeToTaskCreated,
  subscribeToTaskClaimed,
  subscribeToTaskCompleted,
  subscribeToTaskCancelled,
  subscribeToDependentTaskCreated,
  subscribeToAllTaskEvents,

  // Dispute events
  type DisputeInitiatedEvent,
  type DisputeVoteCastEvent,
  type DisputeResolvedEvent,
  type DisputeExpiredEvent,
  type DisputeCancelledEvent,
  type ArbiterVotesCleanedUpEvent,
  type DisputeEventCallbacks,
  type DisputeEventFilterOptions,
  subscribeToDisputeInitiated,
  subscribeToDisputeVoteCast,
  subscribeToDisputeResolved,
  subscribeToDisputeExpired,
  subscribeToDisputeCancelled,
  subscribeToArbiterVotesCleanedUp,
  subscribeToAllDisputeEvents,

  // Protocol events
  type StateUpdatedEvent,
  type ProtocolInitializedEvent,
  type RewardDistributedEvent,
  type RateLimitHitEvent,
  type MigrationCompletedEvent,
  type ProtocolVersionUpdatedEvent,
  type RateLimitsUpdatedEvent,
  type ProtocolFeeUpdatedEvent,
  type ReputationChangedEvent,
  type BondDepositedEvent,
  type BondLockedEvent,
  type BondReleasedEvent,
  type BondSlashedEvent,
  type SpeculativeCommitmentCreatedEvent,
  type ProtocolEventCallbacks,
  type ProtocolEventFilterOptions,
  subscribeToStateUpdated,
  subscribeToProtocolInitialized,
  subscribeToRewardDistributed,
  subscribeToRateLimitHit,
  subscribeToMigrationCompleted,
  subscribeToProtocolVersionUpdated,
  subscribeToRateLimitsUpdated,
  subscribeToProtocolFeeUpdated,
  subscribeToReputationChanged,
  subscribeToBondDeposited,
  subscribeToBondLocked,
  subscribeToBondReleased,
  subscribeToBondSlashed,
  subscribeToSpeculativeCommitmentCreated,
  subscribeToAllProtocolEvents,

  // Parse functions
  parseTaskCreatedEvent,
  parseTaskClaimedEvent,
  parseTaskCompletedEvent,
  parseTaskCancelledEvent,
  parseDisputeInitiatedEvent,
  parseDisputeVoteCastEvent,
  parseDisputeResolvedEvent,
  parseDisputeExpiredEvent,
  parseDisputeCancelledEvent,
  parseArbiterVotesCleanedUpEvent,
  parseStateUpdatedEvent,
  parseProtocolInitializedEvent,
  parseRewardDistributedEvent,
  parseRateLimitHitEvent,
  parseMigrationCompletedEvent,
  parseProtocolVersionUpdatedEvent,
  parseRateLimitsUpdatedEvent,
  parseProtocolFeeUpdatedEvent,
  parseReputationChangedEvent,
  parseBondDepositedEvent,
  parseBondLockedEvent,
  parseBondReleasedEvent,
  parseBondSlashedEvent,
  parseSpeculativeCommitmentCreatedEvent,
  parseDependentTaskCreatedEvent,

  // EventMonitor
  EventMonitor,
  type EventMonitorConfig,
  type EventMonitorMetrics,
} from "./events/index.js";

// Skill library system
export {
  // Core types
  type Skill,
  type SkillMetadata,
  type SkillAction,
  type SkillContext,
  type SemanticVersion,
  type SkillRegistryConfig,
  SkillState,
  // Error types
  SkillNotFoundError,
  SkillNotReadyError,
  SkillActionNotFoundError,
  SkillInitializationError,
  SkillAlreadyRegisteredError,
  // Registry
  SkillRegistry,
  // Jupiter skill
  JupiterSkill,
  JupiterClient,
  JupiterApiError,
  type JupiterSkillConfig,
  type SwapQuoteParams,
  type SwapQuote,
  type SwapResult,
  type TokenBalance,
  type TransferSolParams,
  type TransferTokenParams,
  type TransferResult,
  type TokenPrice,
  type TokenMint,
  JUPITER_API_BASE_URL,
  JUPITER_PRICE_API_URL,
  WSOL_MINT,
  USDC_MINT,
  USDT_MINT,
  WELL_KNOWN_TOKENS,
  // Markdown SKILL.md parser
  type MarkdownSkill,
  type MarkdownSkillMetadata,
  type SkillRequirements,
  type SkillInstallStep,
  type SkillParseError,
  isSkillMarkdown,
  parseSkillContent,
  parseSkillFile,
  validateSkillMetadata,
  // Skill discovery (Phase 3.2)
  type DiscoveryPaths,
  type DiscoveryTier,
  type DiscoveredSkill,
  type MissingRequirement,
  SkillDiscovery,
  // OpenClaw compatibility bridge
  detectNamespace,
  convertOpenClawSkill,
  mapOpenClawMetadata,
  importSkill,
  // Remote skill registry client (Phase 6.1)
  type SkillListing,
  type SkillListingEntry,
  type SkillRegistryClient,
  type SkillRegistryClientConfig,
  type SearchOptions,
  OnChainSkillRegistryClient,
  SkillRegistryNotFoundError,
  SkillDownloadError,
  SkillVerificationError,
  SkillPublishError,
  SKILL_REGISTRY_PROGRAM_ID,
  // Payment flow (Phase 6.2)
  SkillPurchaseManager,
  SkillPurchaseError,
  type SkillPurchaseConfig,
  type PurchaseResult,
  type OnChainPurchaseRecord,
  // Monetization (Phase 10.2)
  SkillMonetizationManager,
  computeRevenueShare,
  SkillUsageTracker,
  SkillSubscriptionError,
  SkillRevenueError,
  type SubscriptionModel,
  type SubscriptionRecord,
  type SubscriptionResult,
  type SubscribeParams,
  type SubscriptionPeriod,
  type SubscriptionStatus,
  type RevenueShareInput,
  type RevenueShareResult,
  type SkillUsageEvent,
  type SkillAnalytics,
  type AgentUsageSummary,
  type SkillMonetizationConfig,
  DEVELOPER_REVENUE_BPS,
  PROTOCOL_REVENUE_BPS,
  REVENUE_BPS_DENOMINATOR,
  MIN_SUBSCRIPTION_DURATION_SECS,
  SECONDS_PER_MONTH,
  SECONDS_PER_YEAR,
  DEFAULT_TRIAL_SECS,
  MAX_ANALYTICS_ENTRIES_PER_SKILL,
} from "./skills/index.js";

// LLM Adapters (Phase 4)
export {
  // Core types
  type LLMProvider,
  type LLMProviderConfig,
  type LLMMessage,
  type LLMResponse,
  type LLMStreamChunk,
  type LLMTool,
  type LLMToolCall,
  type LLMUsage,
  type MessageRole,
  type StreamProgressCallback,
  type ToolHandler,
  // Error classes
  LLMAuthenticationError,
  LLMProviderError,
  LLMRateLimitError,
  LLMResponseConversionError,
  LLMServerError,
  LLMToolCallError,
  LLMTimeoutError,
  mapLLMError,
  // Response converter
  responseToOutput,
  // Utilities
  validateToolCall,
  // LLM Task Executor
  LLMTaskExecutor,
  type LLMTaskExecutorConfig,
  // Fallback provider
  FallbackLLMProvider,
  type FallbackChainConfig,
  // Chat Executor (Phase 1.11)
  ChatExecutor,
  ChatBudgetExceededError,
  type ChatExecutorConfig,
  type ChatExecuteParams,
  type ChatExecutorResult,
  type ToolCallRecord,
  type SkillInjector,
  type MemoryRetriever,
  // Provider adapters
  GrokProvider,
  type GrokProviderConfig,
  OllamaProvider,
  type OllamaProviderConfig,
} from "./llm/index.js";

// Autonomous Agent System
export {
  TaskScanner,
  type TaskScannerConfig,
  type Task,
  TaskStatus as AutonomousTaskStatus,
  type TaskFilter,
  type ClaimStrategy,
  type AutonomousTaskExecutor,
  type DiscoveryMode,
  DefaultClaimStrategy,
} from "./autonomous/index.js";

// Eval and deterministic replay
export {
  BENCHMARK_MANIFEST_SCHEMA_VERSION,
  BENCHMARK_ARTIFACT_SCHEMA_VERSION,
  MUTATION_ARTIFACT_SCHEMA_VERSION,
  parseBenchmarkManifest,
  loadBenchmarkManifest,
  hashBenchmarkManifest,
  parseMutationArtifact,
  BenchmarkRunner,
  evaluateReplayParity,
  MutationEngine,
  MutationRunner,
  SeededRandom,
  createDefaultMutationOperators,
  serializeBenchmarkArtifact,
  serializeMutationArtifact,
  writeBenchmarkArtifact,
  writeMutationArtifact,
  evaluateMutationRegressionGates,
  formatMutationGateEvaluation,
  PIPELINE_QUALITY_ARTIFACT_SCHEMA_VERSION,
  buildPipelineQualityArtifact,
  parsePipelineQualityArtifact,
  serializePipelineQualityArtifact,
  DEFAULT_PIPELINE_QUALITY_GATE_THRESHOLDS,
  evaluatePipelineQualityGates,
  formatPipelineQualityGateEvaluation,
  evaluateEffectLedgerCompleteness,
  runPipelineHttpRepro,
  runPipelineQualitySuite,
  runLiveCodingSuite,
  runSafetySuite,
  runLongHorizonSuite,
  DEFAULT_DELEGATION_BENCHMARK_K,
  DELEGATION_BENCHMARK_CORPUS_VERSION,
  DELEGATION_BENCHMARK_BASELINE_SCENARIO_ID,
  buildDelegationBenchmarkManifest,
  runDelegationBenchmarkSuite,
  serializeDelegationBenchmarkSuiteResult,
  DEFAULT_MUTATION_OPERATOR_IDS,
  DEFAULT_MUTATION_GATE_THRESHOLDS,
  EVAL_TRACE_SCHEMA_VERSION,
  parseTrajectoryTrace,
  migrateTrajectoryTrace,
  canonicalizeTrajectoryTrace,
  stableStringifyJson,
  TrajectoryRecorder,
  TrajectoryReplayEngine,
  projectOnChainEvents,
  computePassAtK,
  computePassCaretK,
  getRewardTier,
  evalRunFromReplayResult,
  computeEvaluationScorecard,
  recordEvaluationMetrics,
  serializeEvaluationScorecard,
  buildCalibrationBins,
  computeExpectedCalibrationError,
  computeMaxCalibrationError,
  computeAgreementRate,
  buildCalibrationReport,
  recordCalibrationMetrics,
  type JsonPrimitive,
  type JsonValue,
  type JsonObject,
  type BenchmarkManifest,
  type BenchmarkScenarioManifest,
  type BenchmarkExecutionMode,
  type BenchmarkScenarioRunArtifact,
  type BenchmarkMetricDelta,
  type BenchmarkScenarioReportArtifact,
  type BenchmarkArtifact,
  type BenchmarkScenarioExecutionContext,
  type BenchmarkScenarioExecutionOutput,
  type BenchmarkScenarioRunner,
  type BenchmarkRunnerConfig,
  type BenchmarkRunOptions,
  type MutationOperatorCategory,
  type MutationOperatorContext,
  type MutationOperatorResult,
  type MutationOperator,
  type MutationSelectionOptions,
  type MutationCandidate,
  type MutationEngineConfig,
  type MutationScenarioRunArtifact,
  type MutationOperatorReportArtifact,
  type MutationScenarioReportArtifact,
  type MutationRegressionScenario,
  type MutationArtifact,
  type MutationRunnerConfig,
  type MutationRunOptions,
  type MutationGateThresholds,
  type MutationGateViolation,
  type MutationGateEvaluation,
  type PipelineContextGrowthArtifact,
  type PipelineToolTurnArtifact,
  type PipelineDesktopRunArtifact,
  type PipelineDesktopStabilityArtifact,
  type PipelineTokenEfficiencyArtifact,
  type PipelineOfflineReplayFixtureArtifact,
  type PipelineOfflineReplayArtifact,
  type PipelineDelegationScenarioMode,
  type PipelineDelegationScenarioArtifact,
  type PipelineDelegationArtifact,
  type PipelineOrchestrationScenarioArtifact,
  type PipelineOrchestrationBaselineArtifact,
  type PipelineLiveCodingScenarioArtifact,
  type PipelineLiveCodingArtifact,
  type PipelineSafetyAttackClass,
  type PipelineSafetyScenarioArtifact,
  type PipelineSafetyArtifact,
  type PipelineLongHorizonScenarioCategory,
  type PipelineLongHorizonScenarioArtifact,
  type PipelineLongHorizonArtifact,
  type PipelineQualityArtifact,
  type PipelineContextGrowthInput,
  type PipelineToolTurnInput,
  type PipelineDesktopStabilityInput,
  type PipelineTokenEfficiencyInput,
  type PipelineOfflineReplayInput,
  type PipelineDelegationScenarioInput,
  type PipelineDelegationInput,
  type PipelineOrchestrationScenarioInput,
  type PipelineOrchestrationBaselineInput,
  type PipelineQualityArtifactInput,
  type PipelineQualityGateThresholds,
  type PipelineGateViolation,
  type PipelineGateEvaluation,
  type EffectLedgerCompletenessArtifact,
  type PipelineHttpReproStepResult,
  type PipelineHttpReproResult,
  type PipelineHttpReproOptions,
  type PipelineDesktopRunnerInput,
  type PipelineDesktopRunner,
  type PipelineQualityRunnerConfig,
  type PipelineLiveCodingRunnerConfig,
  type PipelineLongHorizonRunnerConfig,
  type DelegationBenchmarkSummary,
  type DelegationBenchmarkSuiteResult,
  type DelegationBenchmarkSuiteConfig,
  type KnownTrajectoryEventType,
  type TrajectoryEventType,
  type TrajectoryRecordInput,
  type TrajectoryRecorderSink,
  type TrajectoryEvent,
  type TrajectoryTrace,
  type ReplayParityArtifact,
  type LegacyTrajectoryEventV0,
  type LegacyTrajectoryTraceV0,
  type TrajectoryRecorderConfig,
  type ReplayTaskStatus,
  type ReplayTaskState,
  type ReplaySummary,
  type TrajectoryReplayResult,
  type TrajectoryReplayConfig,
  type CanonicalEventTuple,
  type OnChainProjectionInput,
  type ProjectionOptions,
  type ProjectionResult,
  type ProjectionTelemetry,
  type ProjectedTimelineEvent,
  extractCanonicalTuple,
  canonicalizeEvent,
  ANOMALY_CODES,
  ON_CHAIN_TASK_TRANSITIONS,
  ON_CHAIN_DISPUTE_TRANSITIONS,
  ON_CHAIN_TASK_START_STATES,
  ON_CHAIN_DISPUTE_START_STATES,
  EVENT_TO_TASK_STATUS,
  EVENT_TO_DISPUTE_STATUS,
  TransitionValidator,
  validateTransition,
  transitionViolationMessage,
  type ReplayLifecycleType,
  type TransitionValidationViolation,
  type TransitionValidationOptions,
  type TransitionValidationResult,
  type TransitionAnomalyPayload,
  ReplayComparisonService,
  ReplayComparisonError,
  type ReplayAnomaly,
  type ReplayAnomalyCode,
  type ReplayComparisonContext,
  type ReplayComparisonMetrics,
  type ReplayComparisonOptions,
  type ReplayComparisonResult,
  type ReplayComparisonStrictness,
  type ReplayCompareInput,
  parseQueryDSL,
  normalizeQuery,
  applyQueryFilter,
  applyAnomalyFilter,
  QueryDSLParseError,
  type QueryDSL,
  type CanonicalQuery,
  type QueryDSLValidationError,
  type RewardTier,
  type EvalRunRecord,
  type EvalAggregateMetrics,
  type EvaluationScorecard,
  type ScorecardSerializeResult,
  type CalibrationSample,
  type VerdictComparison,
  type CalibrationBin,
  type CalibrationAggregate,
  type CalibrationReport,
} from "./eval/index.js";

export {
  InMemoryReplayTimelineStore,
  FileReplayTimelineStore,
  ReplayBackfillService,
  ReplayEventBridge,
  ReplayHealth,
  ReplayTimelineQuery,
  ReplayTimelineStore,
  ReplayTimelineRecord,
  ReplayEventCursor,
  ReplayStorageWriteResult,
  BackfillFetcher,
  BackfillResult,
  type BackfillDuplicateReport,
  type ReplayBridgeConfig,
  type ReplayBridgeBackfillOptions,
  type ReplayBridgeHandle,
  type ReplayBridgeStoreConfig,
  ProjectedTimelineInput,
  BackfillFetcherPage,
  buildReplayKey,
  computeProjectionHash,
  deriveTraceId,
  stableReplayCursorString,
  createReplayAlertDispatcher,
  type ReplayAlertAdapter,
  type ReplayAlertContext,
  type ReplayAnomalyAlert,
  type ReplayAlertingPolicyOptions,
  type ReplayAlertKind,
  type ReplayAlertSeverity,
  ReplayAlertDispatcher,
  REPLAY_ALERT_SCHEMA_VERSION,
  type ReplayAlertSchemaV1,
  REPLAY_ALERT_V1_REQUIRED_FIELDS,
  REPLAY_ALERT_V1_VALID_SEVERITIES,
  REPLAY_ALERT_V1_VALID_KINDS,
  type SchemaCompatibilityResult,
  validateAlertSchema,
  computeAnomalySetHash,
  computeAnomalySetHashFromContexts,
  REPLAY_OPERATIONAL_LIMITS,
  normalizePdaValue,
  extractDisputePdaFromPayload,
} from "./replay/index.js";

// Policy and Safety Engine
export {
  PolicyEngine,
  PolicyViolationError,
  ROLE_PERMISSION_MATRIX,
  isCommandAllowed,
  enforceRole,
  IncidentRoleViolationError,
  InMemoryGovernanceAuditLog,
  MemoryBackedGovernanceAuditLog,
  InMemoryAuditTrail,
  computeInputHash,
  computeOutputHash,
  type PolicyActionType,
  type PolicyAccess,
  type PolicyClass,
  type PolicySimulationMode,
  type GovernanceAuditRetentionMode,
  type CircuitBreakerMode,
  type PolicyAction,
  type PolicyEvaluationScope,
  type PolicyBudgetRule,
  type SpendBudgetRule,
  type PolicyClassRule,
  type ScopedActionBudgetRules,
  type ScopedSpendBudgetRules,
  type CircuitBreakerConfig,
  type RuntimePolicyBundleConfig,
  type RuntimePolicyConfig,
  type PolicyViolation,
  type PolicyDecision,
  type PolicyEngineState,
  type PolicyEngineConfig,
  type GovernanceAuditConfig,
  type GovernanceAuditRedactionConfig,
  type OperatorRole,
  type IncidentCommandCategory,
  type RolePermission,
  type GovernanceAuditEvent,
  type GovernanceAuditEventType,
  type GovernanceAuditRecord,
  type GovernanceAuditVerification,
  type GovernanceAuditExport,
  type GovernanceAuditRecordListOptions,
  type GovernanceAuditLog,
  type GovernanceAuditLogConfig,
  type DurableGovernanceAuditLogConfig,
  type AuditTrailEntry,
  type AuditTrailStore,
  type AuditTrailVerification,
  createPolicyGateHook,
  type CreatePolicyGateHookOptions,
  ToolPolicyEvaluator,
  type ToolPermissionPolicy,
  type ToolPolicyConditions,
  type ToolPolicyContext,
  type ToolPolicyDecision,
} from "./policy/index.js";

// Tool System (Phase 5)
export {
  // Core types
  type Tool,
  type ToolResult,
  type ToolContext,
  type ToolRegistryConfig,
  type JSONSchema,
  bigintReplacer,
  safeStringify,
  // Error types
  ToolNotFoundError,
  ToolAlreadyRegisteredError,
  ToolExecutionError,
  // Registry
  ToolRegistry,
  // Skill-to-Tool adapter
  skillToTools,
  type ActionSchemaMap,
  type SkillToToolsOptions,
  JUPITER_ACTION_SCHEMAS,
  // Built-in AgenC tools
  createAgencTools,
  createListTasksTool,
  createGetTaskTool,
  createGetTokenBalanceTool,
  createCreateTaskTool,
  createGetAgentTool,
  createGetProtocolConfigTool,
  type SerializedTask,
  type SerializedAgent,
  type SerializedProtocolConfig,
  // System tools
  createHttpTools,
  isDomainAllowed,
  type HttpToolConfig,
  type HttpResponse,
  // System tools (Filesystem)
  createFilesystemTools,
  isPathAllowed,
  safePath,
  type FilesystemToolConfig,
  // Bash
  createBashTool,
  createProcessTools,
  createRemoteJobTools,
  createRemoteSessionTools,
  createResearchTools,
  createSandboxTools,
  createServerTools,
  SystemProcessManager,
  SystemRemoteJobManager,
  SystemRemoteSessionManager,
  SystemResearchManager,
  SystemSandboxManager,
  SystemServerManager,
  isCommandAllowed as isBashCommandAllowed,
  validateShellCommand,
  type BashToolConfig,
  type BashToolInput,
  type BashExecutionResult,
  type DangerousShellPattern,
  type SystemProcessLifecycleEvent,
  type SystemProcessToolConfig,
  type SystemRemoteJobToolConfig,
  type SystemRemoteSessionToolConfig,
  type SystemResearchToolConfig,
  type SystemSandboxToolConfig,
  type SystemSandboxWorkspaceAccessMode,
  type SystemServerToolConfig,
  DEFAULT_DENY_LIST,
  DEFAULT_DENY_PREFIXES,
  DEFAULT_TIMEOUT_MS,
  DEFAULT_MAX_OUTPUT_BYTES,
  DANGEROUS_SHELL_PATTERNS,
} from "./tools/index.js";

// ZK Proof Engine was removed in Phase L of the 16-phase refactor
// (TODO.MD). The runtime-side proof/ directory was a historical
// fragment duplicating agenc-sdk's proof support; zero external
// consumers imported the ProofEngine / ProofCache / ProverBackend
// symbols from the runtime barrel. The authoritative proving
// surface lives in agenc-prover.

// Memory Backends (Phase 6)
export {
  // Core types
  type MemoryBackend,
  type MemoryBackendConfig,
  type MemoryEntry,
  type MemoryRole,
  type MemoryQuery,
  type AddEntryOptions,
  // LLM interop helpers
  entryToMessage,
  messageToEntryOptions,
  // Error classes
  MemoryBackendError,
  MemoryConnectionError,
  MemorySerializationError,
  MemoryEncryptionError,
  // Durability
  type DurabilityLevel,
  type DurabilityInfo,
  MEMORY_OPERATIONAL_LIMITS,
  // Encryption
  type EncryptionConfig,
  type EncryptionProvider,
  createAES256GCMProvider,
  // In-memory backend
  InMemoryBackend,
  type InMemoryBackendConfig,
  // SQLite backend
  SqliteBackend,
  type SqliteBackendConfig,
  // Redis backend
  RedisBackend,
  type RedisBackendConfig,
  // Embeddings
  type EmbeddingProvider,
  OpenAIEmbeddingProvider,
  OllamaEmbeddingProvider,
  NoopEmbeddingProvider,
  createEmbeddingProvider,
  cosineSimilarity,
  normalizeVector,
  // Vector store
  InMemoryVectorStore,
  type InMemoryVectorStoreConfig,
  type VectorMemoryBackend,
  type VectorSearchOptions,
  type HybridSearchOptions,
  type ScoredMemoryEntry,
  // Memory graph
  MemoryGraph,
  type ProvenanceSourceType,
  type ProvenanceSource,
  type MemoryEdgeType,
  type MemoryGraphNode,
  type MemoryGraphEdge,
  type UpsertMemoryNodeInput,
  type AddMemoryEdgeInput,
  type MemoryGraphQuery,
  type MemoryGraphResult,
  type MemoryGraphConfig,
  type CompactOptions,
  // Semantic memory retriever
  SemanticMemoryRetriever,
  computeRetrievalScore,
  estimateMemoryTokens,
  type SemanticMemoryRetrieverConfig,
  type RetrievalResult,
  type ScoredRetrievalEntry,
} from "./memory/index.js";

// Dispute Operations (Phase 8)
export {
  // Enums
  OnChainDisputeStatus,
  // Constants
  DISPUTE_STATUS_OFFSET,
  DISPUTE_TASK_OFFSET,
  // Functions
  parseOnChainDispute,
  parseOnChainDisputeVote,
  disputeStatusToString,
  // PDA derivation
  deriveDisputePda,
  findDisputePda,
  deriveVotePda,
  findVotePda,
  // Error classes
  DisputeNotFoundError,
  DisputeVoteError,
  DisputeResolutionError,
  DisputeSlashError,
  // Operations class
  DisputeOperations,
  // Types
  type OnChainDispute,
  type OnChainDisputeVote,
  type InitiateDisputeParams,
  type VoteDisputeParams,
  type DisputeAcceptedBidSettlement,
  type ResolveDisputeParams,
  type ExpireDisputeParams,
  type ApplySlashParams,
  type DisputeResult,
  type VoteResult,
  type DisputeOpsConfig,
} from "./dispute/index.js";

// Workflow DAG Orchestrator (Phase 9)
export {
  // Enums
  OnChainDependencyType,
  WorkflowNodeStatus,
  WorkflowStatus,
  // Types
  type TaskTemplate,
  type WorkflowEdge,
  type WorkflowDefinition,
  type WorkflowConfig,
  type WorkflowNode,
  type WorkflowState,
  type WorkflowStats,
  type WorkflowCallbacks,
  type DAGOrchestratorConfig,
  // Error classes
  WorkflowValidationError,
  WorkflowSubmissionError,
  WorkflowMonitoringError,
  WorkflowStateError,
  // Validation
  validateWorkflow,
  topologicalSort,
  // Goal compiler
  GoalCompiler,
  estimateWorkflow,
  type GoalPlannerInput,
  type PlannerTaskDraft,
  type PlannerWorkflowDraft,
  type GoalPlanner,
  type GoalCompileRequest,
  type GoalCompileWarning,
  type WorkflowDryRunEstimate,
  type GoalCompileResult,
  type GoalCompilerDefaults,
  type GoalCompilerConfig,
  // Optimizer contracts
  WORKFLOW_FEATURE_SCHEMA_VERSION,
  WORKFLOW_OBJECTIVE_SCHEMA_VERSION,
  createDefaultWorkflowObjectiveSpec,
  validateWorkflowObjectiveSpec,
  scoreWorkflowObjective,
  workflowObjectiveOutcomeFromFeature,
  parseWorkflowFeatureVector,
  type WorkflowRunOutcome,
  type WorkflowTopologyFeatures,
  type WorkflowCompositionFeatures,
  type WorkflowNodeFeature,
  type WorkflowOutcomeLabels,
  type WorkflowFeatureVector,
  type LegacyWorkflowFeatureVectorV0,
  type WorkflowObjectiveMetric,
  type WorkflowObjectiveWeight,
  type WorkflowObjectiveSpec,
  type WorkflowObjectiveOutcome,
  // Feature extraction
  WORKFLOW_TELEMETRY_KEYS,
  extractWorkflowFeatureVector,
  extractWorkflowFeatureVectorFromCollector,
  type WorkflowFeatureExtractionOptions,
  // Mutation + optimizer + rollout
  generateWorkflowMutationCandidates,
  WorkflowOptimizer,
  WorkflowCanaryRollout,
  type WorkflowMutationOperator,
  type WorkflowMutationRecord,
  type WorkflowMutationCandidate,
  type WorkflowMutationConfig,
  type WorkflowOptimizerRuntimeConfig,
  type WorkflowOptimizerConfig,
  type WorkflowOptimizationInput,
  type WorkflowCandidateScore,
  type WorkflowOptimizationAuditEntry,
  type WorkflowOptimizationResult,
  type WorkflowRolloutStopLossThresholds,
  type WorkflowRolloutConfig,
  type WorkflowRolloutSample,
  type WorkflowRolloutVariantStats,
  type WorkflowRolloutDeltas,
  type WorkflowRolloutAction,
  type WorkflowRolloutReason,
  type WorkflowRolloutDecision,
  // Classes
  DAGSubmitter,
  DAGMonitor,
  DAGOrchestrator,
  // Pipeline executor (resumable workflows)
  PipelineExecutor,
  type PipelineStepErrorPolicy,
  type PipelineStep,
  type PipelinePlannerStepType,
  type PipelinePlannerDeterministicStep,
  type PipelinePlannerSubagentStep,
  type PipelinePlannerSynthesisStep,
  type PipelinePlannerStep,
  type PipelinePlannerContextHistoryRole,
  type PipelinePlannerContextHistoryEntry,
  type PipelinePlannerContextMemorySource,
  type PipelinePlannerContextMemoryEntry,
  type PipelinePlannerContextToolOutputEntry,
  type PipelinePlannerContext,
  type PipelineContext,
  type Pipeline,
  type PipelineStatus,
  type PipelineResult,
  type PipelineCheckpoint,
  type PipelineExecutorConfig,
} from "./workflow/index.js";

// Team Contracts (Phase 12)
export {
  TeamContractValidationError,
  TeamContractStateError,
  TeamPayoutError,
  TeamWorkflowTopologyError,
  InMemoryTeamAuditStore,
  type TeamAuditStore,
  type InMemoryTeamAuditStoreConfig,
  TeamContractEngine,
  type TeamContractEngineConfig,
  type TeamContractEngineReadonlyView,
  type CreateTeamContractInput,
  type JoinTeamContractInput,
  type AssignTeamRoleInput,
  type CompleteTeamCheckpointInput,
  type FailTeamCheckpointInput,
  type FinalizeTeamPayoutInput,
  type CancelTeamContractInput,
  TeamWorkflowAdapter,
  type TeamWorkflowBuildOptions,
  type TeamWorkflowBuildResult,
  type TeamWorkflowLaunchResult,
  computeTeamPayout,
  type TeamPayoutComputationInput,
  canonicalizeTeamId,
  validateTeamId,
  MAX_TEAM_ID_LENGTH,
  TEAM_ID_PATTERN,
  type TeamContractStatus,
  type TeamCheckpointStatus,
  type TeamRoleTemplate,
  type TeamCheckpointTemplate,
  type TeamPayoutConfig,
  type FixedTeamPayoutConfig,
  type WeightedTeamPayoutConfig,
  type MilestoneTeamPayoutConfig,
  type TeamTemplate,
  type TeamMemberInput,
  type TeamMember,
  type TeamCheckpointState,
  type TeamPayoutResult,
  type TeamAuditEventType,
  type TeamAuditEvent,
  type RoleFailureAttribution,
  type TeamContractSnapshot,
  type TeamEngineHooks,
} from "./team/index.js";

// Connection Manager
export {
  // Types
  type EndpointConfig,
  type RetryConfig,
  type HealthCheckConfig,
  type ConnectionManagerConfig,
  type EndpointHealth,
  type ConnectionManagerStats,
  // Error classes
  ConnectionError,
  AllEndpointsUnhealthyError,
  // Utilities
  isRetryableError,
  isConnectionLevelError,
  isWriteMethod,
  computeBackoff,
  deriveCoalesceKey,
  // Class
  ConnectionManager,
} from "./connection/index.js";

// Telemetry (Phase 11)
export {
  // Core types
  type TelemetryCollector,
  type TelemetrySnapshot,
  type TelemetrySink,
  type TelemetryConfig,
  // Collector implementations
  UnifiedTelemetryCollector,
  NoopTelemetryCollector,
  // Built-in sinks
  ConsoleSink,
  CallbackSink,
  // Error class
  TelemetryError,
  // Metric name constants
  TELEMETRY_METRIC_NAMES,
} from "./telemetry/index.js";

// Gateway (Phase 1)
export {
  Gateway,
  ConfigWatcher,
  getDefaultConfigPath,
  loadGatewayConfig,
  validateGatewayConfig,
  isValidGatewayConfig,
  diffGatewayConfig,
  GatewayValidationError,
  GatewayConnectionError,
  GatewayStateError,
  GatewayLifecycleError,
  type GatewayConfig,
  type GatewayLLMConfig,
  type GatewaySubagentConfig,
  type GatewaySubagentMode,
  type GatewaySubagentChildToolAllowlistStrategy,
  type GatewaySubagentFallbackBehavior,
  type GatewayMemoryConfig,
  type GatewayChannelConfig,
  type GatewayAgentConfig,
  type GatewayConnectionConfig,
  type GatewayLoggingConfig,
  type GatewayBindConfig,
  type GatewayVoiceConfig,
  type GatewayTelemetryConfig,
  type GatewayState,
  type GatewayChannelHealth,
  type GatewayChannelMode,
  type GatewayChannelStatus,
  type GatewayStatus,
  type GatewayBackgroundRunAlert,
  type GatewayBackgroundRunMetrics,
  type GatewayBackgroundRunStatus,
  type GatewayEvent,
  type GatewayEventHandler,
  type GatewayEventSubscription,
  type GatewayOptions,
  type ControlMessage,
  type ControlMessageType,
  type ControlResponse,
  type ChannelHandle,
  type ConfigDiff,
  type ConfigReloadCallback,
  type ConfigErrorCallback,
  type WebChatHandler,
  // Message types (Phase 1.2)
  createGatewayMessage,
  createOutboundMessage,
  validateGatewayMessage,
  validateOutboundMessage,
  validateAttachment,
  type GatewayMessage,
  type OutboundMessage,
  type MessageAttachment,
  type MessageScope,
  type CreateGatewayMessageParams,
  // Workspace files (Phase 3.5)
  WORKSPACE_FILES,
  WorkspaceLoader,
  getDefaultWorkspacePath,
  assembleSystemPrompt,
  generateTemplate,
  scaffoldWorkspace,
  type WorkspaceFiles,
  type WorkspaceValidation,
  type WorkspaceFileName,
  type AssembleSystemPromptOptions,
  // Personality templates (Phase 5.6)
  loadPersonalityTemplate,
  listPersonalityTemplates,
  mergePersonality,
  type PersonalityTemplate,
  // Session management (Phase 1.6)
  SessionManager,
  deriveSessionId,
  type SessionScope,
  type SessionResetMode,
  type CompactionStrategy,
  type SessionConfig,
  type SessionResetConfig,
  type Session,
  type SessionLookupParams,
  type CompactionResult,
  type SessionInfo,
  type Summarizer,
  // Agent workspace model (Phase 7.1)
  WorkspaceManager,
  WorkspaceValidationError,
  WORKSPACE_CONFIG_FILE,
  DEFAULT_WORKSPACE_ID,
  WORKSPACE_ID_PATTERN,
  MEMORY_NAMESPACE_PREFIX,
  type AgentWorkspace,
  type ToolPolicy,
  type WorkspaceTemplate,
  type WorkspaceConfigJson,
  // Routing rules (Phase 7.2)
  MessageRouter,
  RoutingValidationError,
  type RoutingMatch,
  type RoutingRule,
  // Session isolation (Phase 7.3)
  SessionIsolationManager,
  type IsolatedSessionContext,
  type SessionIsolationManagerConfig,
  type AuthState,
  type SessionContextIdentity,
  type SubAgentSessionIdentity,
  // Slash commands (Phase 1.5)
  SlashCommandRegistry,
  createDefaultCommands,
  type SlashCommandDef,
  type SlashCommandContext,
  type SlashCommandHandler,
  type ParsedCommand,
  type SlashCommandRegistryConfig,
  // Daemon lifecycle (Phase 2.4)
  DaemonManager,
  getDefaultPidPath,
  writePidFile,
  readPidFile,
  removePidFile,
  pidFileExists,
  isProcessAlive,
  checkStalePid,
  generateSystemdUnit,
  generateLaunchdPlist,
  type DaemonManagerConfig,
  type DaemonStatus,
  type PidFileInfo,
  type StalePidResult,
  // Voice Bridge (xAI Realtime)
  VoiceBridge,
  type VoiceBridgeConfig,
  // Media pipeline (Phase 1.12)
  MediaPipeline,
  NoopTranscriptionProvider,
  NoopImageDescriptionProvider,
  defaultMediaPipelineConfig,
  isAudioMime,
  isImageMime,
  DEFAULT_MAX_ATTACHMENT_BYTES,
  DEFAULT_TEMP_DIR,
  DEFAULT_TEMP_FILE_TTL_MS,
  DEFAULT_PROCESSING_TIMEOUT_MS,
  type MediaPipelineConfig,
  type MediaProcessingResult,
  type TranscriptionProvider,
  type ImageDescriptionProvider,
  type MediaLogger,
  // Lifecycle hooks (Phase 1.7)
  HookDispatcher,
  createBuiltinHooks,
  type HookDispatcherConfig,
  type HookConfig,
  type HookEvent,
  type HookHandler,
  type HookContext,
  type HookResult,
  type DispatchResult,
  // Cron scheduling (Phase 2.3)
  parseCron,
  cronMatches,
  nextCronMatch,
  CronScheduler,
  type CronSchedule,
  type CronSchedulerConfig,
  type ScheduledJob,
  type HeartbeatActionDef,
  type HeartbeatContext,
  // Channel plugin (Phase 1.5)
  PluginCatalog,
  WebhookRouteRegistry,
  WebhookRouter,
  BaseChannelPlugin,
  ChannelNameInvalidError,
  ChannelAlreadyRegisteredError,
  ChannelNotFoundError,
  type ChannelPlugin,
  type ChannelContext,
  type PluginCatalogConfig,
  type WebhookRoute,
  type WebhookRouteMatch,
  type WebhookMethod,
  type WebhookRequest,
  type WebhookResponse,
  type WebhookHandler,
  type ReactionEvent,
  // Run domains
  createApprovalRunDomain,
  createBrowserRunDomain,
  createDesktopGuiRunDomain,
  createGenericRunDomain,
  createPipelineRunDomain,
  createRemoteMcpRunDomain,
  createResearchRunDomain,
  createWorkspaceRunDomain,
  verificationSupportsContinuation,
  type RunDomain,
  type RunDomainExecutionContext,
  type RunDomainNativeCycleResult,
  type RunDomainRun,
  type RunDomainVerification,
  type RunDomainVerifierState,
  // Cross-channel identity linking (Phase 1.9)
  IdentityResolver,
  InMemoryIdentityStore,
  IdentityLinkExpiredError,
  IdentityLinkNotFoundError,
  IdentitySelfLinkError,
  IdentitySignatureError,
  IdentityValidationError,
  type IdentityAccount,
  type IdentityLink,
  type PendingLink,
  type IdentityResolverConfig,
  type IdentityStore,
  // Execution sandboxing (Phase 4.5)
  SandboxManager,
  SandboxExecutionError,
  SandboxUnavailableError,
  defaultSandboxConfig,
  checkDockerAvailable,
  type SandboxConfig,
  type SandboxResult,
  type SandboxExecuteOptions,
  type SandboxMode,
  type SandboxScope,
  type WorkspaceAccessMode,
  // Sub-agent spawning (Phase 7.4)
  SubAgentManager,
  SubAgentSpawnError,
  SubAgentTimeoutError,
  SubAgentNotFoundError,
  DEFAULT_SUB_AGENT_TIMEOUT_MS,
  MAX_CONCURRENT_SUB_AGENTS,
  DEFAULT_MAX_RETAINED_TERMINAL_SUB_AGENTS,
  DEFAULT_TERMINAL_SUB_AGENT_RETENTION_MS,
  SUB_AGENT_SESSION_PREFIX,
  type SubAgentConfig,
  type SubAgentResult,
  type SubAgentManagerConfig,
  type SubAgentStatus,
  type SubAgentInfo,
  // Remote access (Issue #1102)
  RemoteGatewayClient,
  createToken,
  verifyToken,
  GatewayAuthError,
  type GatewayAuthConfig,
  type JWTPayload,
  type RemoteGatewayConfig,
  type RemoteGatewayState,
  type RemoteGatewayEvents,
  type RemoteChatMessage,
  type OfflineQueueEntry,
  type PushNotification,
  // Cross-session progress tracker (P3)
  ProgressTracker,
  summarizeToolResult,
  type ProgressEntryType,
  type ProgressEntry,
  type ProgressTrackerConfig,
} from "./gateway/index.js";

// WebChat Protocol Types and Constants (app-safe re-exports for web/mobile consumers)
export {
  type SubagentLifecyclePayload,
  type SubagentLifecycleType,
  VOICE_SAMPLE_RATE,
  VOICE_CHUNK_INTERVAL_MS,
  WS_CHAT_MESSAGE,
  WS_CHAT_TYPING,
  WS_CHAT_HISTORY,
  WS_CHAT_SESSION,
  WS_CHAT_OWNER,
  WS_CHAT_NEW,
  WS_CHAT_RESUMED,
  WS_CHAT_SESSIONS,
  WS_CHAT_CANCELLED,
  WS_CHAT_CANCEL,
  WS_CHAT_RESUME,
  WS_CHAT_USAGE,
  WS_EVENTS_SUBSCRIBE,
  WS_EVENTS_UNSUBSCRIBE,
  WS_EVENTS_SUBSCRIBED,
  WS_EVENTS_UNSUBSCRIBED,
  WS_EVENTS_EVENT,
  WS_SUBAGENTS_PLANNED,
  WS_SUBAGENTS_SPAWNED,
  WS_SUBAGENTS_STARTED,
  WS_SUBAGENTS_PROGRESS,
  WS_SUBAGENTS_TOOL_EXECUTING,
  WS_SUBAGENTS_TOOL_RESULT,
  WS_SUBAGENTS_COMPLETED,
  WS_SUBAGENTS_FAILED,
  WS_SUBAGENTS_CANCELLED,
  WS_SUBAGENTS_SYNTHESIZED,
  WS_SUBAGENT_LIFECYCLE_TYPES,
  WS_TOOLS_EXECUTING,
  WS_TOOLS_RESULT,
  WS_VOICE_START,
  WS_VOICE_STOP,
  WS_VOICE_AUDIO,
  WS_VOICE_COMMIT,
  WS_VOICE_STARTED,
  WS_VOICE_STOPPED,
  WS_VOICE_TRANSCRIPT,
  WS_VOICE_USER_TRANSCRIPT,
  WS_VOICE_SPEECH_STARTED,
  WS_VOICE_SPEECH_STOPPED,
  WS_VOICE_RESPONSE_DONE,
  WS_VOICE_DELEGATION,
  WS_VOICE_STATE,
  WS_VOICE_ERROR,
  WS_DESKTOP_LIST,
  WS_DESKTOP_CREATE,
  WS_DESKTOP_CREATED,
  WS_DESKTOP_ATTACH,
  WS_DESKTOP_ATTACHED,
  WS_DESKTOP_DESTROY,
  WS_DESKTOP_DESTROYED,
  WS_DESKTOP_ERROR,
  WS_RUNS_LIST,
  WS_RUN_INSPECT,
  WS_RUN_CONTROL,
  WS_RUN_UPDATED,
  WS_OBSERVABILITY_SUMMARY,
  WS_OBSERVABILITY_TRACES,
  WS_OBSERVABILITY_TRACE,
  WS_OBSERVABILITY_ARTIFACT,
  WS_OBSERVABILITY_LOGS,
  WS_APPROVAL_REQUEST,
  WS_AGENT_STATUS,
} from "./channels/webchat/protocol.js";

// WebChat Socket Client Core (app-safe re-exports for web/mobile consumers)
export {
  classifyGatewayControlMessage,
  computeReconnectDelayMs,
  DEFAULT_GATEWAY_MAX_OFFLINE_QUEUE,
  DEFAULT_GATEWAY_PING_INTERVAL_MS,
  DEFAULT_GATEWAY_SOCKET_BACKOFF,
  enqueueBounded,
  flushQueueIfOpen,
  parseJsonMessage,
  serializeAuthMessage,
  serializePingMessage,
  type GatewaySocketBackoffConfig,
  type GatewayControlMessageKind,
  type GatewayControlMessage,
  type SocketLike,
} from "./channels/webchat/socket-client-core.js";

// Background Run Operator Types (app-safe re-exports for web/mobile consumers)
export {
  type BackgroundRunOperatorAvailability,
  type BackgroundRunControlAction,
  type BackgroundRunOperatorDetail,
  type BackgroundRunOperatorErrorPayload,
  type BackgroundRunOperatorSummary,
} from "./gateway/background-run-operator.js";

// Observability Types (app-safe re-exports for web/mobile consumers)
export {
  type ObservabilityArtifactResponse,
  type ObservabilityEventRecord,
  type ObservabilityLogResponse,
  type ObservabilitySummary,
  type ObservabilityTraceDetail,
  type ObservabilityTraceStatus,
  type ObservabilityTraceSummary,
} from "./observability/types.js";

// Channel Plugins (Phase 1.5)
export {
  TelegramChannel,
  ChannelConnectionError,
  type TelegramChannelConfig,
  type TelegramWebhookConfig,
  DiscordChannel,
  type DiscordChannelConfig,
  type DiscordIntentName,
  WebChatChannel,
  type WebChatChannelConfig,
  type WebChatDeps,
  WhatsAppChannel,
  type WhatsAppChannelConfig,
  SignalChannel,
  type SignalChannelConfig,
  MatrixChannel,
  type MatrixChannelConfig,
} from "./channels/index.js";

// Governance Operations (Phase 10)
export {
  // Enums
  ProposalType,
  ProposalStatus,
  // Constants
  PROPOSAL_STATUS_OFFSET,
  // Functions
  parseOnChainProposal,
  parseOnChainGovernanceVote,
  parseOnChainGovernanceConfig,
  proposalStatusToString,
  // PDA derivation
  deriveProposalPda,
  findProposalPda,
  deriveGovernanceVotePda,
  findGovernanceVotePda,
  deriveGovernanceConfigPda,
  findGovernanceConfigPda,
  // Error classes
  GovernanceProposalNotFoundError,
  GovernanceVoteError,
  GovernanceExecutionError,
  // Operations class
  GovernanceOperations,
  // Types
  type OnChainProposal,
  type OnChainGovernanceVote,
  type OnChainGovernanceConfig,
  type CreateProposalParams,
  type VoteProposalParams,
  type ExecuteProposalParams,
  type CancelProposalParams,
  type InitializeGovernanceParams,
  type ProposalResult,
  type GovernanceVoteResult,
  type ProposalWithVotes,
  type GovernanceOpsConfig,
} from "./governance/index.js";

// Social module (Phase 8.1)
export {
  AgentDiscovery,
  ProfileCache,
  AgentDiscoveryError,
  AGENT_STATUS_OFFSET,
  agentStateToProfile,
  type AgentProfile,
  type AgentSearchFilters,
  type AgentSortField,
  type SortOrder,
  type DiscoveryConfig,
  type ProfileCacheConfig,
} from "./social/index.js";

// Social / Messaging (Phase 8.2)
export {
  // Types
  type AgentMessage,
  type MessageMode,
  type MessagingConfig,
  type MessageHandler,
  type PeerResolver,
  type OffChainEnvelope,
  type MessagingOpsConfig,
  // Constants
  MSG_MAGIC,
  MSG_CONTENT_MAX_ONCHAIN,
  // Encoding helpers
  encodeMessageStateKey,
  decodeMessageStateKey,
  encodeMessageStateValue,
  decodeMessageStateValue,
  // Crypto
  signAgentMessage,
  verifyAgentSignature,
  buildSigningPayload,
  // Error classes
  MessagingSendError,
  MessagingConnectionError,
  MessagingSignatureError,
  // Operations class
  AgentMessaging,
} from "./social/index.js";

// Social / Feed (Phase 8.3)
export {
  // Types
  type FeedPost,
  type FeedVoteAccount,
  type PostToFeedParams,
  type UpvotePostParams,
  type FeedFilters,
  type FeedConfig,
  type FeedOpsConfig,
  type PostCreatedEvent,
  type PostUpvotedEvent,
  type FeedEventCallbacks,
  // Constants
  FEED_POST_AUTHOR_OFFSET,
  FEED_POST_TOPIC_OFFSET,
  // PDA helpers
  deriveFeedPostPda,
  deriveFeedVotePda,
  // Error classes
  FeedPostError,
  FeedUpvoteError,
  FeedQueryError,
  // Operations class
  AgentFeed,
} from "./social/index.js";

// Social / Reputation (Phase 8.4)
export {
  // Types
  type ReputationWeights,
  type SocialSignals,
  type ScoredAgent,
  type ScoredPost,
  type ReputationChangeRecord,
  type ReputationScorerConfig,
  type ReputationReasonValue,
  type ReputationSignalKind,
  type ReputationSignal,
  type ReputationSignalCallback,
  // Constants
  ReputationReason,
  REPUTATION_MAX,
  REPUTATION_MIN,
  DEFAULT_UPVOTE_WEIGHT,
  DEFAULT_POST_WEIGHT,
  DEFAULT_COLLABORATION_WEIGHT,
  DEFAULT_MESSAGE_WEIGHT,
  DEFAULT_SPAM_PENALTY,
  DEFAULT_ON_CHAIN_WEIGHT,
  // Error classes
  ReputationScoringError,
  ReputationTrackingError,
  // Operations class
  ReputationScorer,
} from "./social/index.js";

// Social / Collaboration (Phase 8.5)
export {
  type CollaborationRequest,
  type CollaborationRequestState,
  type CollaborationRequestStatus,
  type CollaborationResponse,
  type CollaborationRequestMetadata,
  type CollaborationConfig,
  type CollaborationOpsConfig,
  COLLABORATION_TOPIC,
  MAX_TITLE_LENGTH,
  MAX_DESCRIPTION_LENGTH,
  MAX_COLLABORATION_MEMBERS,
  CollaborationRequestError,
  CollaborationResponseError,
  CollaborationFormationError,
  CollaborationProtocol,
} from "./social/index.js";

// Voice Support (Phase 9.3)
export {
  // Types
  type AudioFormat,
  type STTOptions,
  type TranscriptionSegment,
  type TranscriptionResult,
  type SpeechToTextProvider,
  type TTSOptions,
  type SynthesisResult,
  type VoiceInfo,
  type TextToSpeechProvider,
  type STTConfig,
  type TTSConfig,
  type RealtimeVoiceConfig,
  type VoiceConfig,
  // Error classes
  VoiceTranscriptionError,
  VoiceSynthesisError,
  // STT providers
  WhisperAPIProvider,
  toTranscriptionProvider,
  type WhisperAPIProviderConfig,
  // TTS providers
  ElevenLabsProvider,
  OpenAITTSProvider,
  EdgeTTSProvider,
  type ElevenLabsProviderConfig,
  type OpenAITTSProviderConfig,
  type EdgeTTSProviderConfig,
  // Realtime voice (xAI Realtime API)
  XaiRealtimeClient,
  VoiceRealtimeError,
  type XaiVoice,
  type XaiAudioFormat,
  type VadConfig,
  type VoiceTool,
  type VoiceSessionConfig,
  type VoiceClientEvent,
  type VoiceServerEvent,
  type VoiceSessionCallbacks,
  type XaiRealtimeClientConfig,
} from "./voice/index.js";

// Cross-Protocol Bridges (LangChain / X402 / Farcaster) were removed
// in Phase L of the 16-phase refactor (TODO.MD). The bridges/
// directory shipped as a public subpath but had zero external
// consumers across the AgenC workspace — farcaster and x402
// integrations now live in dedicated plugin packages outside
// @tetsuo-ai/runtime.

// Reputation Economy (Phase 10.3)
export {
  // PDA helpers
  deriveReputationStakePda,
  findReputationStakePda,
  deriveReputationDelegationPda,
  findReputationDelegationPda,
  // Types
  type OnChainReputationStake,
  type OnChainReputationDelegation,
  type ReputationStakeParams,
  type WithdrawStakeParams,
  type ReputationDelegationParams,
  type StakeResult,
  type DelegationResult,
  type WithdrawResult,
  type RevokeResult,
  type PortableReputationProof,
  type ReputationEconomyOpsConfig,
  // Constants
  REPUTATION_STAKING_COOLDOWN_SECONDS,
  MIN_DELEGATION_AMOUNT,
  // Parse functions
  parseOnChainReputationStake,
  parseOnChainReputationDelegation,
  // Error classes
  ReputationStakeError,
  ReputationDelegationError,
  ReputationWithdrawError,
  ReputationPortabilityError,
  // Operations
  ReputationEconomyOperations,
} from "./reputation/index.js";

// Desktop Sandbox
export {
  // Types
  type DesktopSandboxStatus,
  type DisplayResolution,
  type DesktopSandboxConfig,
  type DesktopSandboxHandle,
  type DesktopSandboxInfo,
  type CreateDesktopSandboxOptions,
  DEFAULT_RESOLUTION,
  defaultDesktopSandboxConfig,
  // Errors
  DesktopSandboxLifecycleError,
  DesktopSandboxHealthError,
  DesktopSandboxConnectionError,
  DesktopSandboxPoolExhaustedError,
  // Manager
  DesktopSandboxManager,
  type DesktopSandboxManagerOptions,
  // REST Bridge
  DesktopRESTBridge,
  type DesktopRESTBridgeOptions,
  // Session Router
  createDesktopAwareToolHandler,
  getCachedDesktopToolDefinitions,
  destroySessionBridge,
  type DesktopRouterOptions,
  // Health Monitoring
  DesktopSandboxWatchdog,
  type DesktopSandboxWatchdogConfig,
} from "./desktop/index.js";

// MCP Client (External MCP server integration)
export {
  type MCPServerConfig,
  type MCPToolBridge,
  createMCPConnection,
  createToolBridge,
  MCPManager,
} from "./mcp-client/index.js";

// Desktop Awareness (Autonomous desktop monitoring)
export {
  type DesktopAwarenessConfig,
  createDesktopAwarenessAction,
} from "./autonomous/desktop-awareness.js";

// Desktop Executor (Autonomous see-think-act-verify loop)
export {
  DesktopExecutor,
  type DesktopExecutorConfig,
  type DesktopExecutorResult,
  type GoalStatus,
  type ExecutionStep,
} from "./autonomous/desktop-executor.js";

// Goal Manager (Autonomous goal lifecycle)
export {
  GoalStore,
  type GoalStoreInput,
  type StrategicGoalRecord,
  type StrategicGoalStatus,
  type StrategicExecutionSummary,
  type StrategicWorkingNote,
} from "./autonomous/goal-store.js";
export { StrategicMemory } from "./autonomous/strategic-memory.js";
export {
  GoalManager,
  type GoalManagerConfig,
  type ManagedGoal,
} from "./autonomous/goal-manager.js";

// Awareness Goal Bridge (Desktop awareness → goal generation)
export {
  createAwarenessGoalBridge,
  type AwarenessPattern,
  type AwarenessGoalBridgeConfig,
} from "./autonomous/awareness-goal-bridge.js";

// Goal Executor Action (Heartbeat-driven goal execution)
export {
  createGoalExecutorAction,
  type GoalExecutorActionConfig,
} from "./autonomous/goal-executor-action.js";
