import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { test } from "node:test";

import {
  parseGeneratedWrapperContent,
  renderGeneratedWrapperContent,
} from "../lib/generated-wrapper.mjs";

function prePrivateNodeWrapperFixture({ kind, nodeBin, runtimeBin, agencHome }) {
  const metadata = Buffer.from(JSON.stringify({
    nodeBin,
    runtimeBin,
    agencHome,
  }), "utf8").toString("base64url");
  if (kind === "cmd") {
    const batch = (value) => value.replaceAll("%", "%%");
    return [
      "@echo off",
      "setlocal DisableDelayedExpansion",
      "rem Generated by AgenC install.ps1 - rewritten on every install/upgrade.",
      `rem AgenC wrapper metadata v1: ${metadata}`,
      `if not defined AGENC_HOME set "AGENC_HOME=${batch(agencHome)}"`,
      `"${batch(nodeBin)}" "${batch(runtimeBin)}" %*`,
      "",
    ].join("\r\n");
  }
  const quote = (value) => `'${value.replaceAll("'", `'"'"'`)}'`;
  return [
    "#!/bin/sh",
    "# Generated by AgenC install.sh — rewritten on every install/upgrade.",
    `# AgenC wrapper metadata v1: ${metadata}`,
    'if [ -z "${AGENC_HOME:-}" ]; then',
    `  export AGENC_HOME=${quote(agencHome)}`,
    "fi",
    "# Capture one V8 near-heap-limit snapshot unless the operator already configured it.",
    'case " ${NODE_OPTIONS:-} " in',
    "  *heapsnapshot-near-heap-limit*)",
    `    exec ${quote(nodeBin)} ${quote(runtimeBin)} "$@"`,
    "    ;;",
    "  *)",
    '    mkdir -p "${AGENC_HOME}/oom-snapshots" 2>/dev/null || :',
    `    exec ${quote(nodeBin)} --heapsnapshot-near-heap-limit=1 ` +
      '--diagnostic-dir="${AGENC_HOME}/oom-snapshots" ' +
      `${quote(runtimeBin)} "$@"`,
    "    ;;",
    "esac",
    "",
  ].join("\n");
}

test("POSIX wrapper resolves child node commands from the private runtime", {
  skip: process.platform === "win32",
}, () => {
  const root = mkdtempSync(join(tmpdir(), "agenc-generated-wrapper-"));
  try {
    const nodeBin = join(
      root,
      "runtime",
      "node_modules",
      ".agenc-node",
      "bin",
      "node",
    );
    const runtimeBin = join(
      root,
      "runtime",
      "node_modules",
      "@tetsuo-ai",
      "runtime",
      "bin",
      "agenc.cjs",
    );
    const agencHome = join(root, "home");
    const ambientBin = join(root, "ambient-bin");
    const wrapper = join(root, "agenc");
    for (const directory of [
      dirname(nodeBin),
      dirname(runtimeBin),
      agencHome,
      ambientBin,
    ]) {
      mkdirSync(directory, { recursive: true });
    }
    writeFileSync(nodeBin, [
      "#!/bin/sh",
      'if [ "${1:-}" = "--agenc-private-node-probe" ]; then',
      "  printf 'private-node-path-ok\\n'",
      "  exit 0",
      "fi",
      `exec ${JSON.stringify(process.execPath)} "$@"`,
      "",
    ].join("\n"), { mode: 0o755 });
    chmodSync(nodeBin, 0o755);
    writeFileSync(runtimeBin, [
      'const { spawnSync } = require("node:child_process");',
      'const child = spawnSync("node", ["--agenc-private-node-probe"], { encoding: "utf8" });',
      "if (child.error) throw child.error;",
      "process.stdout.write(child.stdout);",
      "",
    ].join("\n"));
    writeFileSync(wrapper, renderGeneratedWrapperContent({
      kind: "posix",
      nodeBin,
      runtimeBin,
      agencHome,
    }), { mode: 0o755 });
    chmodSync(wrapper, 0o755);

    const result = spawnSync(wrapper, [], {
      encoding: "utf8",
      env: {
        PATH: ambientBin,
        NODE_OPTIONS: "--heapsnapshot-near-heap-limit=1",
      },
    });

    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, "private-node-path-ok\n");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("Windows wrapper prepends its private Node directory before exact execution", () => {
  const content = renderGeneratedWrapperContent({
    kind: "cmd",
    nodeBin: "/AgenC Runtime/.agenc-node/node.exe",
    runtimeBin: "/AgenC Runtime/@tetsuo-ai/runtime/bin/agenc",
    agencHome: "/Users/operator/.agenc",
  });
  const pathLine = 'set "PATH=/AgenC Runtime/.agenc-node;%PATH%"';
  const execLine =
    '"/AgenC Runtime/.agenc-node/node.exe" ' +
    '"/AgenC Runtime/@tetsuo-ai/runtime/bin/agenc" %*';

  assert.ok(content.includes(pathLine));
  assert.ok(content.indexOf(pathLine) < content.indexOf(execLine));
});

test("parser accepts only exact pre-private-Node metadata-v1 wrappers", () => {
  const root = mkdtempSync(join(tmpdir(), "agenc-legacy-wrapper-"));
  try {
    const agencHome = join(root, "home");
    const values = {
      nodeBin: join(root, ".nvm", "versions", "node", "v25.9.0", "bin", "node"),
      runtimeBin: join(
        agencHome,
        "runtime",
        "0.10.0",
        "linux-x64-glibc-node-abi-141",
        "node_modules",
        "@tetsuo-ai",
        "runtime",
        "bin",
        "agenc",
      ),
      agencHome,
    };
    const posixPath = join(root, "bin", "agenc");
    const posix = prePrivateNodeWrapperFixture({ kind: "posix", ...values });
    assert.deepEqual(parseGeneratedWrapperContent(posixPath, posix), {
      kind: "posix",
      path: posixPath,
      ...values,
    });
    assert.equal(
      parseGeneratedWrapperContent(
        posixPath,
        posix.replace("    ;;", "    echo injected\n    ;;"),
      ),
      null,
    );

    const cmdValues = {
      nodeBin: join(root, "Node % Runtime", "node.exe"),
      runtimeBin: join(agencHome, "runtime", "0.10.0", "bin % runtime", "agenc.js"),
      agencHome,
    };
    const cmdPath = join(root, "bin", "agenc.cmd");
    const cmd = prePrivateNodeWrapperFixture({ kind: "cmd", ...cmdValues });
    assert.deepEqual(parseGeneratedWrapperContent(cmdPath, cmd), {
      kind: "cmd",
      path: cmdPath,
      ...cmdValues,
    });
    assert.equal(
      parseGeneratedWrapperContent(
        cmdPath,
        cmd.replace(" %*", " %*\r\necho injected"),
      ),
      null,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
