// @ts-nocheck
// Stub — feature-gated path; real implementation lives in openclaude upstream.
const __stubProxy: any = new Proxy(function __stub(..._args: any[]): any { return __stubProxy; }, {
  get(target, prop) {
    if (prop === 'then') return undefined;
    if (prop === Symbol.toPrimitive) return () => '';
    if (prop === Symbol.iterator) return function* () {};
    if (prop === Symbol.asyncIterator) return async function* () {};
    if (prop === 'length') return 0;
    if (prop === 'size') return 0;
    if (prop === 'cache') return new Map();
    return __stubProxy;
  },
  apply() { return __stubProxy; },
  construct() { return __stubProxy; },
  has() { return true; },
  set() { return true; },
});
export type AttributedCounter<_T = any> = any;
export const AttributedCounter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type ChannelEntry<_T = any> = any;
export const ChannelEntry: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type InvokedSkillInfo<_T = any> = any;
export const InvokedSkillInfo: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type SessionCronTask<_T = any> = any;
export const SessionCronTask: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type addInvokedSkill<_T = any> = any;
export const addInvokedSkill: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type addSessionCronTask<_T = any> = any;
export const addSessionCronTask: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type addSlowOperation<_T = any> = any;
export const addSlowOperation: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type addToInMemoryErrorLog<_T = any> = any;
export const addToInMemoryErrorLog: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type addToToolDuration<_T = any> = any;
export const addToToolDuration: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type addToTotalCostState<_T = any> = any;
export const addToTotalCostState: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type addToTotalDurationState<_T = any> = any;
export const addToTotalDurationState: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type addToTotalLinesChanged<_T = any> = any;
export const addToTotalLinesChanged: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type addToTurnClassifierDuration<_T = any> = any;
export const addToTurnClassifierDuration: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type addToTurnHookDuration<_T = any> = any;
export const addToTurnHookDuration: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearBetaHeaderLatches<_T = any> = any;
export const clearBetaHeaderLatches: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearInvokedSkills<_T = any> = any;
export const clearInvokedSkills: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearInvokedSkillsForAgent<_T = any> = any;
export const clearInvokedSkillsForAgent: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearRegisteredHooks<_T = any> = any;
export const clearRegisteredHooks: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearRegisteredPluginHooks<_T = any> = any;
export const clearRegisteredPluginHooks: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type clearSystemPromptSectionState<_T = any> = any;
export const clearSystemPromptSectionState: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type consumePostCompaction<_T = any> = any;
export const consumePostCompaction: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type flushInteractionTime<_T = any> = any;
export const flushInteractionTime: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getActiveTimeCounter<_T = any> = any;
export const getActiveTimeCounter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getActiveTimeCounterImpl<_T = any> = any;
export const getActiveTimeCounterImpl: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getAdditionalDirectoriesForClaudeMd<_T = any> = any;
export const getAdditionalDirectoriesForClaudeMd: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getAfkModeHeaderLatched<_T = any> = any;
export const getAfkModeHeaderLatched: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getAgentColorMap<_T = any> = any;
export const getAgentColorMap: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getAllowedChannels<_T = any> = any;
export const getAllowedChannels: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getAllowedSettingSources<_T = any> = any;
export const getAllowedSettingSources: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getApiKeyFromFd<_T = any> = any;
export const getApiKeyFromFd: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getBudgetContinuationCount<_T = any> = any;
export const getBudgetContinuationCount: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getCacheEditingHeaderLatched<_T = any> = any;
export const getCacheEditingHeaderLatched: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getCachedClaudeMdContent<_T = any> = any;
export const getCachedClaudeMdContent: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getChromeFlagOverride<_T = any> = any;
export const getChromeFlagOverride: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getClientType<_T = any> = any;
export const getClientType: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getCodeEditToolDecisionCounter<_T = any> = any;
export const getCodeEditToolDecisionCounter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getCommitCounter<_T = any> = any;
export const getCommitCounter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getCostCounter<_T = any> = any;
export const getCostCounter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getCurrentTurnTokenBudget<_T = any> = any;
export const getCurrentTurnTokenBudget: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getCwdState<_T = any> = any;
export const getCwdState: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getDirectConnectServerUrl<_T = any> = any;
export const getDirectConnectServerUrl: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getEventLogger<_T = any> = any;
export const getEventLogger: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getFastModeHeaderLatched<_T = any> = any;
export const getFastModeHeaderLatched: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getFlagSettingsInline<_T = any> = any;
export const getFlagSettingsInline: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getFlagSettingsPath<_T = any> = any;
export const getFlagSettingsPath: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getHasDevChannels<_T = any> = any;
export const getHasDevChannels: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getInitJsonSchema<_T = any> = any;
export const getInitJsonSchema: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getInitialMainLoopModel<_T = any> = any;
export const getInitialMainLoopModel: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getInlinePlugins<_T = any> = any;
export const getInlinePlugins: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getInvokedSkills<_T = any> = any;
export const getInvokedSkills: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getInvokedSkillsForAgent<_T = any> = any;
export const getInvokedSkillsForAgent: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getIsInteractive<_T = any> = any;
export const getIsInteractive: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getIsNonInteractiveSession<_T = any> = any;
export const getIsNonInteractiveSession: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getIsRemoteMode<_T = any> = any;
export const getIsRemoteMode: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getIsScrollDraining<_T = any> = any;
export const getIsScrollDraining: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getKairosActive<_T = any> = any;
export const getKairosActive: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getLastAPIRequest<_T = any> = any;
export const getLastAPIRequest: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getLastAPIRequestMessages<_T = any> = any;
export const getLastAPIRequestMessages: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getLastApiCompletionTimestamp<_T = any> = any;
export const getLastApiCompletionTimestamp: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getLastClassifierRequests<_T = any> = any;
export const getLastClassifierRequests: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getLastEmittedDate<_T = any> = any;
export const getLastEmittedDate: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getLastInteractionTime<_T = any> = any;
export const getLastInteractionTime: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getLastMainRequestId<_T = any> = any;
export const getLastMainRequestId: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getLocCounter<_T = any> = any;
export const getLocCounter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getLoggerProvider<_T = any> = any;
export const getLoggerProvider: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getMainLoopModelOverride<_T = any> = any;
export const getMainLoopModelOverride: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getMainThreadAgentType<_T = any> = any;
export const getMainThreadAgentType: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getMeter<_T = any> = any;
export const getMeter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getMeterProvider<_T = any> = any;
export const getMeterProvider: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getModelStrings<_T = any> = any;
export const getModelStrings: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getModelStringsState<_T = any> = any;
export const getModelStringsState: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getModelUsage<_T = any> = any;
export const getModelUsage: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getOauthTokenFromFd<_T = any> = any;
export const getOauthTokenFromFd: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getOriginalCwd<_T = any> = any;
export const getOriginalCwd: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getParentSessionId<_T = any> = any;
export const getParentSessionId: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getParentSessionIdFromState<_T = any> = any;
export const getParentSessionIdFromState: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getPlanSlugCache<_T = any> = any;
export const getPlanSlugCache: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getPrCounter<_T = any> = any;
export const getPrCounter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getProjectRoot<_T = any> = any;
export const getProjectRoot: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getPromptCache1hAllowlist<_T = any> = any;
export const getPromptCache1hAllowlist: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getPromptCache1hEligible<_T = any> = any;
export const getPromptCache1hEligible: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getPromptId<_T = any> = any;
export const getPromptId: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getQuestionPreviewFormat<_T = any> = any;
export const getQuestionPreviewFormat: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getRegisteredHooks<_T = any> = any;
export const getRegisteredHooks: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getReplBridgeHandle<_T = any> = any;
export const getReplBridgeHandle: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getScheduledTasksEnabled<_T = any> = any;
export const getScheduledTasksEnabled: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSdkAgentProgressSummariesEnabled<_T = any> = any;
export const getSdkAgentProgressSummariesEnabled: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSdkBetas<_T = any> = any;
export const getSdkBetas: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSessionBypassPermissionsMode<_T = any> = any;
export const getSessionBypassPermissionsMode: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSessionCounter<_T = any> = any;
export const getSessionCounter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSessionCreatedTeams<_T = any> = any;
export const getSessionCreatedTeams: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSessionCronTasks<_T = any> = any;
export const getSessionCronTasks: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSessionId<_T = any> = any;
export const getSessionId: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSessionIngressToken<_T = any> = any;
export const getSessionIngressToken: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSessionProjectDir<_T = any> = any;
export const getSessionProjectDir: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSessionSource<_T = any> = any;
export const getSessionSource: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSessionTrustAccepted<_T = any> = any;
export const getSessionTrustAccepted: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSlowOperations<_T = any> = any;
export const getSlowOperations: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getStatsStore<_T = any> = any;
export const getStatsStore: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getStrictToolResultPairing<_T = any> = any;
export const getStrictToolResultPairing: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getSystemPromptSectionCache<_T = any> = any;
export const getSystemPromptSectionCache: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTeleportedSessionInfo<_T = any> = any;
export const getTeleportedSessionInfo: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getThinkingClearLatched<_T = any> = any;
export const getThinkingClearLatched: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTokenCounter<_T = any> = any;
export const getTokenCounter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalAPIDuration<_T = any> = any;
export const getTotalAPIDuration: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalAPIDurationWithoutRetries<_T = any> = any;
export const getTotalAPIDurationWithoutRetries: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalCacheCreationInputTokens<_T = any> = any;
export const getTotalCacheCreationInputTokens: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalCacheReadInputTokens<_T = any> = any;
export const getTotalCacheReadInputTokens: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalCostUSD<_T = any> = any;
export const getTotalCostUSD: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalDuration<_T = any> = any;
export const getTotalDuration: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalInputTokens<_T = any> = any;
export const getTotalInputTokens: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalLinesAdded<_T = any> = any;
export const getTotalLinesAdded: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalLinesRemoved<_T = any> = any;
export const getTotalLinesRemoved: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalOutputTokens<_T = any> = any;
export const getTotalOutputTokens: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalToolDuration<_T = any> = any;
export const getTotalToolDuration: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTotalWebSearchRequests<_T = any> = any;
export const getTotalWebSearchRequests: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTracerProvider<_T = any> = any;
export const getTracerProvider: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTurnClassifierCount<_T = any> = any;
export const getTurnClassifierCount: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTurnClassifierDurationMs<_T = any> = any;
export const getTurnClassifierDurationMs: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTurnHookCount<_T = any> = any;
export const getTurnHookCount: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTurnHookDurationMs<_T = any> = any;
export const getTurnHookDurationMs: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTurnOutputTokens<_T = any> = any;
export const getTurnOutputTokens: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTurnToolCount<_T = any> = any;
export const getTurnToolCount: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getTurnToolDurationMs<_T = any> = any;
export const getTurnToolDurationMs: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getUsageForModel<_T = any> = any;
export const getUsageForModel: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getUseCoworkPlugins<_T = any> = any;
export const getUseCoworkPlugins: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type getUserMsgOptIn<_T = any> = any;
export const getUserMsgOptIn: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type handleAutoModeTransition<_T = any> = any;
export const handleAutoModeTransition: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type handlePlanModeTransition<_T = any> = any;
export const handlePlanModeTransition: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type hasExitedPlanModeInSession<_T = any> = any;
export const hasExitedPlanModeInSession: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type hasShownLspRecommendationThisSession<_T = any> = any;
export const hasShownLspRecommendationThisSession: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type hasUnknownModelCost<_T = any> = any;
export const hasUnknownModelCost: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type incrementBudgetContinuationCount<_T = any> = any;
export const incrementBudgetContinuationCount: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isReplBridgeActive<_T = any> = any;
export const isReplBridgeActive: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type isSessionPersistenceDisabled<_T = any> = any;
export const isSessionPersistenceDisabled: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type markFirstTeleportMessageLogged<_T = any> = any;
export const markFirstTeleportMessageLogged: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type markPostCompaction<_T = any> = any;
export const markPostCompaction: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type markScrollActivity<_T = any> = any;
export const markScrollActivity: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type needsAutoModeExitAttachment<_T = any> = any;
export const needsAutoModeExitAttachment: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type needsPlanModeExitAttachment<_T = any> = any;
export const needsPlanModeExitAttachment: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type onSessionSwitch<_T = any> = any;
export const onSessionSwitch: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type preferThirdPartyAuthentication<_T = any> = any;
export const preferThirdPartyAuthentication: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type regenerateSessionId<_T = any> = any;
export const regenerateSessionId: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type registerHookCallbacks<_T = any> = any;
export const registerHookCallbacks: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type removeSessionCronTasks<_T = any> = any;
export const removeSessionCronTasks: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type resetCostState<_T = any> = any;
export const resetCostState: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type resetModelStringsForTestingOnly<_T = any> = any;
export const resetModelStringsForTestingOnly: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type resetSdkInitState<_T = any> = any;
export const resetSdkInitState: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type resetStateForTests<_T = any> = any;
export const resetStateForTests: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type resetTotalDurationStateAndCost_FOR_TESTS_ONLY<_T = any> = any;
export const resetTotalDurationStateAndCost_FOR_TESTS_ONLY: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type resetTurnClassifierDuration<_T = any> = any;
export const resetTurnClassifierDuration: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type resetTurnHookDuration<_T = any> = any;
export const resetTurnHookDuration: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type resetTurnToolDuration<_T = any> = any;
export const resetTurnToolDuration: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setAdditionalDirectoriesForClaudeMd<_T = any> = any;
export const setAdditionalDirectoriesForClaudeMd: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setAfkModeHeaderLatched<_T = any> = any;
export const setAfkModeHeaderLatched: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setAllowedChannels<_T = any> = any;
export const setAllowedChannels: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setAllowedSettingSources<_T = any> = any;
export const setAllowedSettingSources: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setApiKeyFromFd<_T = any> = any;
export const setApiKeyFromFd: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setCacheEditingHeaderLatched<_T = any> = any;
export const setCacheEditingHeaderLatched: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setCachedClaudeMdContent<_T = any> = any;
export const setCachedClaudeMdContent: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setChromeFlagOverride<_T = any> = any;
export const setChromeFlagOverride: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setClientType<_T = any> = any;
export const setClientType: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setCostStateForRestore<_T = any> = any;
export const setCostStateForRestore: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setCwdState<_T = any> = any;
export const setCwdState: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setDirectConnectServerUrl<_T = any> = any;
export const setDirectConnectServerUrl: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setEventLogger<_T = any> = any;
export const setEventLogger: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setFastModeHeaderLatched<_T = any> = any;
export const setFastModeHeaderLatched: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setFlagSettingsInline<_T = any> = any;
export const setFlagSettingsInline: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setFlagSettingsPath<_T = any> = any;
export const setFlagSettingsPath: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setHasDevChannels<_T = any> = any;
export const setHasDevChannels: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setHasExitedPlanMode<_T = any> = any;
export const setHasExitedPlanMode: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setHasUnknownModelCost<_T = any> = any;
export const setHasUnknownModelCost: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setInitJsonSchema<_T = any> = any;
export const setInitJsonSchema: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setInitialMainLoopModel<_T = any> = any;
export const setInitialMainLoopModel: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setInlinePlugins<_T = any> = any;
export const setInlinePlugins: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setIsInteractive<_T = any> = any;
export const setIsInteractive: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setIsRemoteMode<_T = any> = any;
export const setIsRemoteMode: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setKairosActive<_T = any> = any;
export const setKairosActive: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setLastAPIRequest<_T = any> = any;
export const setLastAPIRequest: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setLastAPIRequestMessages<_T = any> = any;
export const setLastAPIRequestMessages: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setLastApiCompletionTimestamp<_T = any> = any;
export const setLastApiCompletionTimestamp: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setLastClassifierRequests<_T = any> = any;
export const setLastClassifierRequests: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setLastEmittedDate<_T = any> = any;
export const setLastEmittedDate: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setLastMainRequestId<_T = any> = any;
export const setLastMainRequestId: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setLoggerProvider<_T = any> = any;
export const setLoggerProvider: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setLspRecommendationShownThisSession<_T = any> = any;
export const setLspRecommendationShownThisSession: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setMainLoopModelOverride<_T = any> = any;
export const setMainLoopModelOverride: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setMainThreadAgentType<_T = any> = any;
export const setMainThreadAgentType: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setMeter<_T = any> = any;
export const setMeter: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setMeterProvider<_T = any> = any;
export const setMeterProvider: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setModelStrings<_T = any> = any;
export const setModelStrings: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setModelStringsState<_T = any> = any;
export const setModelStringsState: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setNeedsAutoModeExitAttachment<_T = any> = any;
export const setNeedsAutoModeExitAttachment: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setNeedsPlanModeExitAttachment<_T = any> = any;
export const setNeedsPlanModeExitAttachment: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setOauthTokenFromFd<_T = any> = any;
export const setOauthTokenFromFd: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setOriginalCwd<_T = any> = any;
export const setOriginalCwd: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setProjectRoot<_T = any> = any;
export const setProjectRoot: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setPromptCache1hAllowlist<_T = any> = any;
export const setPromptCache1hAllowlist: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setPromptCache1hEligible<_T = any> = any;
export const setPromptCache1hEligible: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setPromptId<_T = any> = any;
export const setPromptId: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setQuestionPreviewFormat<_T = any> = any;
export const setQuestionPreviewFormat: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setScheduledTasksEnabled<_T = any> = any;
export const setScheduledTasksEnabled: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setSdkAgentProgressSummariesEnabled<_T = any> = any;
export const setSdkAgentProgressSummariesEnabled: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setSdkBetas<_T = any> = any;
export const setSdkBetas: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setSessionBypassPermissionsMode<_T = any> = any;
export const setSessionBypassPermissionsMode: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setSessionIngressToken<_T = any> = any;
export const setSessionIngressToken: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setSessionPersistenceDisabled<_T = any> = any;
export const setSessionPersistenceDisabled: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setSessionSource<_T = any> = any;
export const setSessionSource: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setSessionTrustAccepted<_T = any> = any;
export const setSessionTrustAccepted: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setStatsStore<_T = any> = any;
export const setStatsStore: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setStrictToolResultPairing<_T = any> = any;
export const setStrictToolResultPairing: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setSystemPromptSectionCacheEntry<_T = any> = any;
export const setSystemPromptSectionCacheEntry: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setTeleportedSessionInfo<_T = any> = any;
export const setTeleportedSessionInfo: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setThinkingClearLatched<_T = any> = any;
export const setThinkingClearLatched: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setTracerProvider<_T = any> = any;
export const setTracerProvider: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setUseCoworkPlugins<_T = any> = any;
export const setUseCoworkPlugins: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type setUserMsgOptIn<_T = any> = any;
export const setUserMsgOptIn: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type snapshotOutputTokensForTurn<_T = any> = any;
export const snapshotOutputTokensForTurn: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type switchSession<_T = any> = any;
export const switchSession: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type updateLastInteractionTime<_T = any> = any;
export const updateLastInteractionTime: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
export type waitForScrollIdle<_T = any> = any;
export const waitForScrollIdle: { <T = any>(..._args: any[]): any; [k: string]: any; new (..._args: any[]): any } = __stubProxy as any;
