import { describe, expect, it } from "vitest";
import { computeRuntimeSloSnapshot } from "./slo.js";

describe("computeRuntimeSloSnapshot", () => {
  it("derives runtime SLOs from telemetry and pipeline artifacts", () => {
    const snapshot = computeRuntimeSloSnapshot({
      telemetry: {
        counters: {
          "agenc.background_runs.started.total": 4,
          "agenc.background_runs.completed.total": 3,
          "agenc.background_runs.failed.total": 1,
          "agenc.background_runs.recovered.total": 2,
        },
        gauges: {},
        histograms: {
          "agenc.approval.response_latency_ms": [
            { value: 100, timestamp: 1 },
            { value: 300, timestamp: 2 },
          ],
        },
      },
      pipelineQualityArtifact: {
        schemaVersion: 5,
        runId: "slo-fixture",
        generatedAtMs: 1,
        contextGrowth: {
          turns: 1,
          promptTokenSeries: [10],
          tokenDeltas: [],
          maxDelta: 0,
          slope: 0,
        },
        toolTurn: {
          validCases: 1,
          validAccepted: 1,
          malformedCases: 0,
          malformedRejected: 0,
          malformedForwarded: 0,
        },
        desktopStability: {
          runs: 0,
          failedRuns: 0,
          timedOutRuns: 0,
          maxDurationMs: 0,
          runSummaries: [],
        },
        tokenEfficiency: {
          completedTasks: 1,
          totalPromptTokens: 1,
          totalCompletionTokens: 1,
          totalTokens: 2,
          tokensPerCompletedTask: 2,
        },
        offlineReplay: {
          fixtureCount: 0,
          parseFailures: 0,
          replayFailures: 0,
          deterministicMismatches: 0,
          fixtures: [],
        },
        delegation: {
          totalCases: 0,
          delegatedCases: 0,
          usefulDelegations: 0,
          harmfulDelegations: 0,
          unnecessaryDelegations: 0,
          plannerExecutionMismatches: 0,
          childTimeouts: 0,
          childFailures: 0,
          synthesisConflicts: 0,
          depthCapHits: 0,
          fanoutCapHits: 0,
          delegationAttemptRate: 0,
          usefulDelegationRate: 0,
          harmfulDelegationRate: 0,
          plannerToExecutionMismatchRate: 0,
          childTimeoutRate: 0,
          childFailureRate: 0,
          synthesisConflictRate: 0,
          depthCapHitRate: 0,
          fanoutCapHitRate: 0,
          costDeltaVsBaseline: 0,
          latencyDeltaVsBaseline: 0,
          qualityDeltaVsBaseline: 0,
          passAtKDeltaVsBaseline: 0,
          passCaretKDeltaVsBaseline: 0,
          baselineScenarioId: "baseline",
          k: 1,
          scenarioSummaries: [],
        },
        orchestrationBaseline: {
          scenarioCount: 0,
          passingScenarios: 0,
          passRate: 0,
          averageTurns: 0,
          averageToolCalls: 0,
          fallbackCount: 0,
          spuriousSubagentCount: 0,
          approvalCount: 0,
          wrongRootIncidents: 0,
          unsafeMutationAttempts: 0,
          approvalCorrectnessRate: 1,
          effectLedgerCompletenessRate: 0.75,
          restartRecoverySuccessCount: 0,
          restartRecoverySuccessRate: 0,
          scenarios: [],
        },
        liveCoding: {
          scenarioCount: 1,
          passingScenarios: 1,
          passRate: 1,
          tempRepoCount: 1,
          totalFileMutations: 0,
          totalShellMutations: 0,
          wrongRootIncidents: 0,
          unauthorizedWriteBlocks: 0,
          effectLedgerCompletenessRate: 1,
          scenarios: [],
        },
        safety: {
          scenarioCount: 2,
          blockedScenarios: 2,
          passingScenarios: 1,
          passRate: 0.5,
          promptInjectionBlocks: 1,
          maliciousRepoFileBlocks: 0,
          maliciousSkillMetadataBlocks: 0,
          marketplaceTaskPayloadBlocks: 0,
          unsafeShellBlocks: 1,
          unauthorizedArtifactWriteBlocks: 0,
          unsafeMutationAttempts: 1,
          approvalCorrectnessRate: 1,
          scenarios: [],
        },
        longHorizon: {
          scenarioCount: 1,
          passingScenarios: 1,
          passRate: 1,
          hundredStepRuns: 0,
          crashResumeRuns: 1,
          compactContinueRuns: 0,
          backgroundPersistenceRuns: 0,
          restartRecoverySuccessRate: 1,
          compactionContinuationRate: 1,
          backgroundPersistenceRate: 1,
          scenarios: [],
        },
        chaos: {
          scenarioCount: 1,
          passingScenarios: 1,
          passRate: 1,
          providerTimeoutRecoveryRate: 1,
          toolTimeoutContainmentRate: 1,
          persistenceSafeModeRate: 1,
          approvalStoreSafeModeRate: 1,
          childRunCrashContainmentRate: 1,
          daemonRestartRecoveryRate: 1,
          scenarios: [],
        },
      },
    });

    expect(snapshot.runCompletionRate).toBeCloseTo(0.75, 8);
    expect(snapshot.checkpointResumeSuccessRate).toBeCloseTo(0.5, 8);
    expect(snapshot.approvalResponseLatencyMs).toBe(200);
    expect(snapshot.effectLedgerCompletenessRate).toBe(1);
    expect(snapshot.safetyRegressionRate).toBe(0.5);
  });
});
