/**
 * Transcript classification only: names and aliases of the default slash surface.
 * Kept separate from executable commands so reading a transcript never loads
 * their implementations. The registry parity test checks the complete list.
 */
const BUILT_IN_COMMAND_NAMES: ReadonlySet<string> = new Set([
  "help",
  "hello",
  "status",
  "goal",
  "login",
  "logout",
  "whoami",
  "account",
  "subscription",
  "billing",
  "usage",
  "grok-login",
  "xai-login",
  "grok-logout",
  "xai-logout",
  "openai-login",
  "chatgpt-login",
  "openai-logout",
  "chatgpt-logout",
  "cost",
  "stats",
  "model",
  "provider",
  "providers",
  "effort",
  "resolve",
  "resolve-effects",
  "swarm",
  "ledger",
  "wallet",
  "permissions",
  "approvals",
  "allowed-tools",
  "plan",
  "agents",
  "tasks",
  "jobs",
  "bashes",
  "todos",
  "todo",
  "config",
  "keybindings",
  "hooks",
  "skills",
  "mcp",
  "remote",
  "plugins",
  "plugin",
  "marketplace",
  "memory",
  "resume",
  "sessions",
  "rewind",
  "init",
  "output-style",
  "style",
  "output-style:new",
  "clear",
  "reset",
  "new",
  "compact",
  "compact-rollback",
  "compact-retain",
  "context",
  "ctx",
  "coordinator",
  "fleet",
  "diff",
  "claim",
  "delegate",
  "proof",
  "settle",
  "stake",
  "exit",
  "quit"
]);

export function isBuiltInCommandName(name: string): boolean {
  return BUILT_IN_COMMAND_NAMES.has(name);
}

export function builtInCommandNames(): Set<string> {
  return new Set(BUILT_IN_COMMAND_NAMES);
}
