import {test,expect} from 'vitest';
import {ToolRouter} from '../../src/tools/router.js';
import {createPlanningTools} from '../../src/tools/system/planning.js';
import {EventLog} from '../../src/session/event-log.js';
import {resolveAgentRuntimeOptions} from '../../src/session/runtime-options.js';
import {llmMessageToDurableResponseItem,responseItemToLlmMessage} from '../../src/session/message-history-conversion.js';
import {buildChatCompletionsRequest} from '../../src/llm/wire/chat-completions.js';
import {buildOpenAIResponsesRequest} from '../../src/llm/wire/responses-openai.js';
import {buildXaiResponsesRequest,extractXaiReasoningReplay} from '../../src/llm/wire/responses-xai.js';
import {buildAnthropicMessagesRequest} from '../../src/llm/wire/messages-anthropic.js';
test('review: real TodoWrite model dispatch preserves raw durable and wire arguments',async()=>{
 const todos=[{content:'Review the fix',activeForm:'Reviewing the fix',status:'in_progress'}];
 const inner=JSON.stringify(todos,null,2);
 const raw=' { "todos" : '+JSON.stringify(inner)+' }\n';
 const call={id:'review-call',name:'TodoWrite',arguments:raw};
 const encrypted={type:'reasoning',id:'review-r',encrypted_content:Buffer.from('mock-encrypted').toString('base64'),summary:[]};
 const history:any={role:'assistant',content:'',toolCalls:[call],...extractXaiReasoningReplay([encrypted],'grok-4.7'),providerReasoningProvenance:{provider:'grok',model:'grok-4.7'}};
 const before=JSON.stringify(history);
 const tool=createPlanningTools().find(t=>t.name==='TodoWrite')!;
 const router=new ToolRouter([{tool,supportsParallelToolCalls:false}]);
 const result=await router.dispatchModelToolCall(call,{session:{eventLog:new EventLog(),services:{admissionRequired:false,runtimeOptions:resolveAgentRuntimeOptions({})}} as never,turn:{subId:'review-turn'} as never,tracker:{appendFileDiff(){},snapshot(){return []},clear(){}},approvalPolicy:'never',sandboxMode:'workspace_write'});
 expect(result.isError).not.toBe(true);
 expect(result.content).toContain('Todos have been modified successfully');
 expect(JSON.stringify(history)).toBe(before);
 const restored=responseItemToLlmMessage(JSON.parse(JSON.stringify(llmMessageToDurableResponseItem(history))));
 expect(restored.toolCalls?.[0]?.arguments).toBe(raw);
 const chat:any=buildChatCompletionsRequest({model:'mock',messages:[restored],tools:[]});
 expect(chat.messages[0].tool_calls[0].function.arguments).toBe(raw);
 const openai:any=buildOpenAIResponsesRequest({model:'mock',messages:[restored],tools:[]});
 expect(openai.input.find((x:any)=>x.type==='function_call').arguments).toBe(raw);
 const xai:any=buildXaiResponsesRequest({model:'grok-4.7',messages:[restored]});
 expect(xai.input).toContainEqual(encrypted);
 expect(xai.input.find((x:any)=>x.type==='function_call').arguments).toBe(raw);
 const anthropic:any=buildAnthropicMessagesRequest({model:'mock',messages:[restored],tools:[]});
 expect(anthropic.messages[0].content.find((x:any)=>x.type==='tool_use').input.todos).toBe(inner);
});
