import { getInitialSettings } from '../utils/settings/settings.js'

export function getSpinnerVerbs(): string[] {
  const settings = getInitialSettings()
  const config = settings.spinnerVerbs
  if (!config) {
    return SPINNER_VERBS
  }
  if (config.mode === 'replace') {
    return config.verbs.length > 0 ? config.verbs : SPINNER_VERBS
  }
  return [...SPINNER_VERBS, ...config.verbs]
}

// Spinner verbs for loading messages.
// Cyberpunk-flavored: technical action verbs from compilers, networks,
// crypto, runtime systems, and reverse engineering. No clichés.
// Disjoint from the previous default list (no carryover).
//
// IMPORTANT: do NOT add words that NAME a real system/daemon/transport state
// (e.g. "Booting", "Daemonizing", "Mounting", "Buffering", "Reconnecting",
// "Connecting"). A frozen flavor verb that happens to spell a genuine state
// reads as a fault — a 12-minute slow turn once showed "Booting…" and looked
// like the daemon was hung. Keep these to harmless action flavor only.
export const SPINNER_VERBS = [
  'Backporting',
  'Branching',
  'Bridging',
  'Caching',
  'Chaining',
  'Checksumming',
  'Clocking',
  'Compressing',
  'Concatenating',
  'Cracking',
  'Cross-compiling',
  'Debouncing',
  'Debugging',
  'Decoding',
  'Decompiling',
  'Decrypting',
  'Defragmenting',
  'Demuxing',
  'Deobfuscating',
  'Dereferencing',
  'Deserializing',
  'Diffing',
  'Disassembling',
  'Dispatching',
  'Dumping',
  'Embedding',
  'Encoding',
  'Encrypting',
  'Enumerating',
  'Exfiltrating',
  'Extracting',
  'Fingerprinting',
  'Flushing',
  'Forking',
  'Forwarding',
  'Fuzzing',
  'Gating',
  'Geolocating',
  'Heap-walking',
  'Hijacking',
  'Hot-patching',
  'Indexing',
  'Injecting',
  'Instrumenting',
  'Intercepting',
  'Interleaving',
  'Interpolating',
  'Inverting',
  'Iterating',
  'Jamming',
  'Latching',
  'Lowering',
  'Mapping',
  'Marshalling',
  'Masking',
  'Memoizing',
  'Merging',
  'Mirroring',
  'Multiplexing',
  'Negotiating',
  'Normalizing',
  'Obfuscating',
  'Offloading',
  'Optimizing',
  'Packing',
  'Parsing',
  'Patching',
  'Persisting',
  'Pinging',
  'Pipelining',
  'Pivoting',
  'Polling',
  'Probing',
  'Profiling',
  'Pruning',
  'Querying',
  'Queueing',
  'Recompiling',
  'Reconciling',
  'Rehashing',
  'Rendering',
  'Replaying',
  'Resolving',
  'Retracing',
  'Routing',
  'Salting',
  'Scanning',
  'Scheduling',
  'Scrambling',
  'Scraping',
  'Seeking',
  'Serializing',
  'Sharding',
  'Sieving',
  'Signing',
  'Slicing',
  'Sniffing',
  'Snooping',
  'Soldering',
  'Spawning',
  'Splicing',
  'Spoofing',
  'Squashing',
  'Staging',
  'Stitching',
  'Streaming',
  'Striding',
  'Strobing',
  'Surveilling',
  'Swapping',
  'Synchronizing',
  'Tabulating',
  'Tagging',
  'Tapping',
  'Telemetering',
  'Tessellating',
  'Threading',
  'Throttling',
  'Tokenizing',
  'Trampolining',
  'Transcoding',
  'Transpiling',
  'Traversing',
  'Triangulating',
  'Triaging',
  'Triggering',
  'Tunneling',
  'Unmarshalling',
  'Unmasking',
  'Unpacking',
  'Vectorizing',
  'Verifying',
  'Versioning',
  'Wardialing',
  'Watermarking',
  'Weaving',
  'Wiretapping',
]
