import type { ParsedArgv } from "./types.js";
export type { ParsedArgv } from "./types.js";

export function buildHelp(): string {
  return [
    "agenc-runtime [--help] [--config <path>]",
    "onboard [--help] [options]",
    "health [--help] [options]",
    "doctor [--help] [options]",
    "doctor security [--help] [options]",
    "init [--help] [options]",
    "config <init|validate|show> [--help] [options]",
    "start [--help] [options]",
    "stop [--help] [options]",
    "restart [--help] [options]",
    "status [--help] [options]",
    "shell [profile] [--help] [options]",
    "resume [--help] [options]",
    "session [status|list|inspect|history|resume|fork] [--help] [options]",
    "plan [--help] [options]",
    "agents [roles|list|spawn|assign|inspect|stop] [--help] [options]",
    "tasks [list|get|wait|output] [--help] [options]",
    "files [query] [--help] [options]",
    "grep <pattern> [--help] [options]",
    "git <status|diff|show|branch|summary|worktree> [--help] [options]",
    "branch [--help]",
    "worktree <list|create|remove|status> [--help] [options]",
    "diff [--help] [options]",
    "review [--help] [options]",
    "permissions [--help] [options]",
    "mcp [--help] [options]",
    "skills [--help]",
    "model [--help] [options]",
    "effort [--help] [options]",
    "service install [--help] [options]",
    "connector <list|status|add|remove> [--help] [options]",
    "sessions <list|kill> [--help] [options]",
    "logs [--help] [options]",
    "replay [--help] <command> [options]",
    "plugin [--help] <command> [options]",
    "jobs [--help] <command> [options]",
    "agent [--help] <command> [options]",
    "market [--help] <domain> <command> [options]",
    "market inspect <surface> [subject]",
    "market tui",
    "skill [--help] <command> [options]",
    "",
    "Bootstrap commands:",
    "  onboard   Generate a runtime config file and run sanity checks",
    "  health    Report RPC, store, wallet, and config status",
    "  doctor    Run all health checks and provide remediation guidance",
    "  doctor security  Security posture checks",
    "  init      Generate an AGENC.md contributor guide for the current repo",
    "",
    "Config commands:",
    "  config init      Generate gateway config and scaffold workspace",
    "  config validate  Validate an existing gateway config file",
    "  config show      Display the loaded gateway config",
    "",
    "Daemon commands:",
    "  start     Start the gateway daemon",
    "  stop      Stop the gateway daemon",
    "  restart   Restart the gateway daemon",
    "  status    Show daemon status",
    "  shell     Open the line-oriented daemon shell over the existing webchat/control-plane path",
    "  resume    Reopen the shell session for this workspace/profile",
    "  service install  Generate systemd/launchd service template",
    "",
    "Coding shell commands:",
    "  plan [status|enter|exit|implement|review|verify]  Control the coding workflow stage",
    "  agents [roles|list|spawn|assign|inspect|stop]  Manage child agents and explicit delegation",
    "  tasks [list|get|wait|output]   Inspect session tasks",
    "  files [query]           Show repo inventory or search files",
    "  grep <pattern>          Search repo-local files",
    "  git <...>               Structured git status/diff/branch/show/worktree",
    "  branch                  Alias for git branch",
    "  worktree <...>          Alias for git worktree",
    "  diff                    Show change summary plus diff",
    "  review [--staged|--delegate|--mode security|--mode pr-comments]  Summarize repo state for review",
    "",
    "Shell control commands:",
    "  session [status|list|inspect|history|resume|fork]  Inspect the current shell session or continuity catalog",
    "  permissions                    Show policy/approval state",
    "  mcp [status|list|inspect|tools|validate|reconnect|enable|disable]  Inspect configured MCP servers and tools",
    "  skills [list|inspect|enable|disable|sources]  Use the local shell skill surface",
    "  model                          Show or switch the configured model",
    "  effort                         Show or switch configured reasoning effort",
    "",
    "Low-level session commands:",
    "  sessions list              List active control plane sessions",
    "  sessions kill <sessionId>  Disconnect a control plane session",
    "",
    "Log commands:",
    "  logs                       Show daemon log viewing instructions",
    "",
    "Connector commands:",
    "  connector list                            List supported connector lifecycle status",
    "  connector status [telegram]               Show connector status details",
    "  connector add telegram --bot-token-env TELEGRAM_BOT_TOKEN",
    "                                          Configure the Telegram connector",
    "  connector remove telegram                 Remove the Telegram connector",
    "",
    "Replay subcommands:",
    "  backfill   Backfill replay timeline from on-chain history",
    "  compare    Compare replay projection against local trace",
    "  incident   Reconstruct incident timeline and summarize",
    "",
    "Jobs subcommands:",
    "  list                               List scheduled jobs",
    "  run <jobName>                      Trigger a scheduled job immediately",
    "  enable <jobName>                   Enable a scheduled job",
    "  disable <jobName>                  Disable a scheduled job",
    "",
    "Agent subcommands:",
    "  register [--capabilities mask] [--endpoint url]",
    "                                    Register the signer wallet as an on-chain agent",
    "",
    "Market subcommands:",
    "  tasks list [--status open,in_progress]       List marketplace tasks",
    "  tasks create --description txt --reward lamports",
    "                                              Create a public marketplace task",
    "  tasks detail <taskPda>                       Inspect a task",
    "  tasks cancel <taskPda>                       Cancel an open task",
    "  tasks claim <taskPda>                        Claim a task",
    "  tasks complete <taskPda> [--result-data txt] Complete a task (auto-hashes proof when omitted)",
    "  tasks dispute <taskPda> --evidence txt       Open a dispute for a task",
    "  skills list [--query text] [--tags t1,t2]    List marketplace skills",
    "  skills detail <skillPda>                     Inspect a skill registration",
    "  skills purchase <skillPda>                   Purchase and install a marketplace skill",
    '  skills rate <skillPda> <1-5> [--review "text"] Rate a marketplace skill',
    "  governance list                              List governance proposals",
    "  governance detail <proposalPda>              Inspect a governance proposal",
    "  governance vote <proposalPda> <yes|no>       Vote on a governance proposal",
    "  disputes list [--status active,resolved]     List disputes",
    "  disputes detail <disputePda>                 Inspect a dispute",
    "  disputes resolve <disputePda> --arbiter-votes votePda:arbiterPda[,..]",
    "                                              Resolve a dispute with explicit vote accounts",
    "  reputation summary [agentPda]                Inspect reputation state",
    "  reputation stake <lamports>                  Stake SOL on reputation",
    "  reputation delegate <amount> --delegatee-agent-pda <pda>",
    "                                              Delegate reputation to another agent",
    "  inspect <surface> [subject]                  Inspect a shared marketplace surface",
    "  tui                                          Launch the interactive terminal marketplace workspace",
    "",
    "Skill subcommands:",
    "  list                               List all discovered skills",
    "  info <name>                        Show detailed skill information",
    "  validate                           Validate all discovered skills",
    "  create <name>                      Scaffold a new skill in ~/.agenc/skills/",
    "  install <url-or-path>              Install a skill from URL or local path",
    "  uninstall <name>                   Remove a user-level skill",
    "  enable <name>                      Enable a disabled skill",
    "  disable <name>                     Disable a skill",
    "  search <query> [--tags t1,t2] [--limit N]  Search on-chain skill registry",
    "  registry-install <skill-id>        Install a skill from the on-chain registry",
    "  publish <path> [--tags t1,t2] [--price N]  Publish a skill to the on-chain registry",
    '  rate <skill-id> <1-5> [--review "text"]    Rate a skill in the on-chain registry',
    "  verify <skill-id> [--path <file>]  Verify skill hash against on-chain registry",
    "  import-openclaw <path-or-url>      Import an OpenClaw skill to AgenC format",
    "",
    "Plugin subcommands:",
    "  list                               List registered plugins",
    "  install --manifest <path> [--precedence workspace|user|builtin] [--slot memory|llm|proof|telemetry|custom]",
    "                                   Install or register a plugin",
    "  disable <pluginId>                 Disable a plugin",
    "  enable <pluginId>                  Enable a plugin",
    "  reload <pluginId> [--manifest <path>] Reload a plugin and optional manifest update",
    "",
    "Global options:",
    "  -h, --help                               Show this usage",
    "      --output, --output-format json|jsonl|table  Response output format",
    "      --strict-mode                         Enable strict validation",
    "      --role <role>                         Operator role (read|investigate|execute|admin)",
    "      --rpc                                 RPC endpoint",
    "      --program-id                          Program id",
    "      --trace-id                            Trace id",
    "      --store-type memory|sqlite             Replay event store",
    "      --sqlite-path <path>                  SQLite DB path (sqlite store)",
    "      --idempotency-window <seconds>        Default: 900",
    "      --log-level silent|error|warn|info|debug",
    "      --config <path>                       Config file path (default: ~/.agenc/config.json)",
    "",
    "onboard options:",
    "      --non-interactive                     Skip interactive prompts (CI-friendly)",
    "      --force                               Overwrite existing config file",
    "",
    "health options:",
    "      --non-interactive                     Skip interactive prompts (CI-friendly)",
    "      --deep                                Run extended checks (latency, store integrity)",
    "",
    "doctor options:",
    "      --non-interactive                     Skip interactive prompts (CI-friendly)",
    "      --deep                                Run extended checks (latency, store integrity)",
    "      --fix                                 Attempt automatic remediation where possible",
    "",
    "start options:",
    "      --config <path>                           Gateway config file path",
    "      --foreground                              Run in foreground (systemd/Docker mode)",
    "      --pid-path <path>                         Custom PID file path",
    "      --yolo                                    Enable unsafe delegation benchmark mode and disable host execution deny lists",
    "",
    "stop options:",
    "      --pid-path <path>                         Custom PID file path",
    "      --timeout <ms>                            Shutdown timeout in ms (default: 30000)",
    "",
    "status options:",
    "      --pid-path <path>                         Custom PID file path",
    "      --port <port>                             Override control plane port",
    "",
    "shell options:",
    "      --pid-path <path>                         Custom PID file path",
    "      --port <port>                             Override control plane port",
    "      --profile <name>                          Shell profile: general|coding|research|validation|documentation|operator",
    "      --new                                     Force a fresh shell session for this workspace/profile",
    "      --session <id>                            Resume a specific session id instead of the stored workspace/profile session",
    "",
    "coding shell command options:",
    "      --profile <name>                          Override the default alias profile",
    "      --pid-path <path>                         Custom PID file path",
    "      --port <port>                             Override control-plane port",
    "      --session <id>                            Reuse a specific daemon session id",
    "      --new                                     Force a fresh session before running a one-shot shell command",
    "      --path <dir>                              Repo/workspace path override where supported",
    "      --regex                                   Regex mode for files/grep",
    "      --glob <g1,g2>                            File glob filters for files/grep",
    "      --max <n>                                 Result cap for files/grep",
    "      --context <n>                             Context lines for grep",
    "      --staged                                  Use staged diff/review surfaces",
    "      --from <ref> --to <ref>                   Diff revision range",
    "      --files <a,b>                             Limit diff to specific files",
    "      --branch <name> --ref <ref>               Worktree creation inputs",
    "      --detached                                Detached worktree creation",
    "      --force                                   Force worktree removal",
    "      --timeout <ms>                            Task wait/output timeout",
    "      --status <value>                          Task status filter",
    "      --block                                   Block waiting for task output",
    "      --bundle <name>                           Child-agent tool bundle override",
    "      --workspace <path>                        Child-agent workspace root override",
    "      --worktree auto|<path>                    Child-agent worktree policy or existing worktree path",
    "      --cwd <path>                              Child-agent working directory under the resolved root",
    "      --wait                                    Wait for child-agent completion",
    "      --all                                     Include completed child agents where supported",
    "",
    "service install options:",
    "      --macos                                   Generate launchd plist instead of systemd unit",
    "      --yolo                                    Include unsafe benchmark mode (--yolo) in the generated service command",
    "",
    "backfill options:",
    "      --to-slot <slot>                      Highest slot to scan (required)",
    "      --page-size <size>                    Number of events per page",
    "",
    "compare options:",
    "      --local-trace-path <path>              Path to local trajectory trace (required)",
    "      --task-pda <pda>                      Limit by task id",
    "      --dispute-pda <pda>                   Limit by dispute id",
    "      --redact-fields <fields>               Comma-separated output redaction keys",
    "",
    "incident options:",
    "      --task-pda <pda>                      Limit by task id",
    "      --dispute-pda <pda>                   Limit by dispute id",
    "      --query <dsl>                         Analyst query DSL filter string",
    "      --redact-fields <fields>               Comma-separated output redaction keys",
    "      --from-slot <slot>                    Replay incident from slot",
    "      --to-slot <slot>                      Replay incident to slot",
    "",
    "config init options:",
    "      --non-interactive                     Skip interactive prompts (CI-friendly)",
    "      --force                               Overwrite existing config file",
    "",
    "init options:",
    "      --force                               Overwrite an existing AGENC.md",
    "      --path <dir>                          Target project root (default: current working directory)",
    "      --pid-path <path>                     Custom PID file path",
    "      --port <port>                         Override control plane port",
    "",
    "sessions options:",
    "      --pid-path <path>                         Custom PID file path",
    "      --port <port>                             Override control plane port",
    "",
    "logs options:",
    "      --pid-path <path>                         Custom PID file path",
    "      --session <id>                            Filter by session ID",
    "      --lines <n>                               Number of recent log lines (used in journalctl hint)",
    "",
    "connector options:",
    "      --pid-path <path>                         Custom PID file path",
    "      --port <port>                             Override control plane port",
    "      --restart true|false                      Restart matching daemon after config mutation (default: true)",
    "      --bot-token-env <ENV_NAME>                Read Telegram bot token from an environment variable",
    "      --bot-token-stdin                         Read Telegram bot token from stdin",
    "      --allowed-users <id1,id2>                 Restrict Telegram access to specific user IDs",
    "      --polling-interval-ms <n>                 Telegram polling interval in ms",
    "      --max-attachment-bytes <n>                Max inbound Telegram attachment size",
    "      --rate-limit-per-chat <n>                 Outbound Telegram messages per second per chat",
    "",
    "plugin options:",
    "      --manifest <path>                     Plugin manifest path (install/reload)",
    "      --precedence workspace|user|builtin  Plugin installation precedence",
    "      --slot memory|llm|proof|telemetry|custom Plugin slot claim",
    "",
    "market options:",
    "      --status <s1,s2>                      Status filter for tasks/disputes list",
    "      --description <text>                  Task description for market tasks create",
    "      --reward <lamports>                   Task reward for market tasks create",
    "      --reward-mint <mint>                  Optional SPL reward mint for task creation",
    "      --required-capabilities <u64>         Required capability bitmask for task creation (default: 1)",
    "      --max-workers <n>                     Max workers for task creation",
    "      --deadline <unix>                     Task deadline for task creation",
    "      --task-type <type>                    Task type for task list/create: 0/exclusive, 1/collaborative, 2/competitive, 3/bid-exclusive",
    "      --min-reputation <n>                  Minimum worker reputation for task creation",
    "      --constraint-hash <hex>               Optional 32-byte private-task constraint hash",
    "      --validation-mode auto|creator-review Hold payout until creator approval when creator-review",
    "      --review-window-secs <n>              Review window for creator-review task creation",
    "      --creator-agent-pda <pda>             Explicit creator agent PDA for task creation",
    "      --job-spec <text>                    Full off-chain job spec text for task creation",
    "      --full-description <text>            Detailed off-chain task description",
    "      --acceptance-criteria <items>        Comma/newline-separated acceptance criteria",
    "      --deliverables <items>               Comma/newline-separated deliverables",
    "      --constraints <json>                 JSON constraints stored in the off-chain job spec",
    "      --attachment <url>                   Off-chain job spec attachment URL (repeatable)",
    "      --job-spec-store-dir <path>          Local content-addressed job spec store override",
    "      --query <text>                        Text filter for skills list",
    "      --tags <t1,t2>                        Tag filter for skills list",
    "      --limit <n>                           Limit skills list results",
    "      --proof-hash <hex>                    Explicit 32-byte proof hash for task completion",
    "      --result-data <text>                  Task completion result data",
    "      --evidence <text>                     Dispute evidence text",
    "      --resolution-type refund|complete|split  Desired dispute outcome",
    "      --expected-price <lamports>           Purchase price guard for skills",
    "      --arbiter-votes <votePda:arbiterPda,...> Required resolve pairs",
    "      --extra-workers <claimPda:workerPda,...> Optional collaborative worker pairs",
    "      --delegatee-agent-pda <pda>           Target agent PDA for reputation delegation",
    "      --delegatee-agent-id <hex>            Target agent id for reputation delegation",
    "      --expires-at <unix>                   Optional reputation delegation expiry",
    "      --worker-agent-pda <pda>              Explicit worker agent for task actions",
    "      --worker-claim-pda <pda>              Explicit worker claim PDA for disputes",
    "      --initiator-agent-pda <pda>           Explicit initiator agent PDA for disputes",
    "      --buyer-agent-pda <pda>               Explicit buyer agent PDA for skill purchase",
    "      --rater-agent-pda <pda>               Explicit rater agent PDA for skill rating",
    "      --voter-agent-pda <pda>               Explicit voter agent PDA for governance",
    "      --staker-agent-pda <pda>              Explicit staker agent PDA for reputation stake",
    "      --delegator-agent-pda <pda>           Explicit delegator agent PDA for reputation delegation",
    "",
    "Examples:",
    "  agenc-runtime start --config ~/.agenc/config.json",
    "  agenc-runtime start --foreground --config ~/.agenc/config.json",
    "  agenc-runtime start --foreground --yolo --config ~/.agenc/config.json",
    "  agenc-runtime stop",
    "  agenc-runtime restart --config ~/.agenc/config.json",
    "  agenc-runtime status",
    "  agenc-runtime shell coding",
    "  agenc-runtime resume --profile coding",
    "  agenc-runtime plan",
    "  agenc-runtime agents roles",
    '  agenc-runtime agents spawn coding --objective "Implement the task" --worktree auto',
    "  agenc-runtime agents assign task-123 verify --wait",
    "  agenc-runtime files package",
    "  agenc-runtime grep shellProfile --glob src/**/*.ts",
    "  agenc-runtime git status",
    "  agenc-runtime git diff --staged",
    "  agenc-runtime worktree create ../agenc-alt --branch alt-impl",
    "  agenc-runtime review --staged",
    "  agenc-runtime session",
    "  agenc-runtime permissions",
    "  agenc-runtime mcp list",
    "  agenc-runtime model list",
    "  agenc-runtime effort high",
    "  agenc-runtime shell --profile research --new",
    "  agenc-runtime service install",
    "  agenc-runtime service install --macos",
    "  agenc-runtime config init",
    "  agenc-runtime config init --force",
    "  agenc-runtime config validate --config ~/.agenc/config.json",
    "  agenc-runtime config show",
    "  agenc-runtime sessions list",
    "  agenc-runtime sessions kill client_1",
    "  agenc-runtime logs",
    "  agenc-runtime connector list",
    "  agenc-runtime connector status telegram",
    "  agenc-runtime connector add telegram --bot-token-env TELEGRAM_BOT_TOKEN",
    "  printf '%s' \"$TELEGRAM_BOT_TOKEN\" | agenc-runtime connector add telegram --bot-token-stdin --restart=false",
    "  agenc-runtime connector remove telegram",
    "  agenc-runtime onboard --force",
    "  agenc-runtime health --deep",
    "  agenc-runtime doctor --deep --fix",
    "  agenc-runtime doctor security --deep --fix",
    "  agenc-runtime init",
    "  agenc-runtime init --force",
    "  agenc-runtime replay backfill --to-slot 12345 --page-size 500",
    "  agenc-runtime replay compare --local-trace-path ./trace.json --task-pda AGENTpda",
    "  agenc-runtime replay incident --task-pda AGENTpda --from-slot 100 --to-slot 200",
    "  agenc-runtime plugin install --manifest ./plugin.json --precedence workspace --slot llm",
    "  agenc-runtime plugin disable memory.plugin",
    "  agenc-runtime plugin list",
    "  agenc-runtime market tasks list --status open,in_progress",
    "  agenc-runtime market tasks create --description 'public task' --reward 50000000",
    "  agenc-runtime market tasks create --description 'reviewed task' --reward 50000000 --validation-mode creator-review --review-window-secs 3600 --creator-agent-pda <agentPda>",
    "  agenc-runtime market tasks claim <taskPda>",
    "  agenc-runtime market tasks cancel <taskPda>",
    "  agenc-runtime market tasks complete <taskPda> --result-data 'completed via cli'",
    "  agenc-runtime market tasks dispute <taskPda> --evidence 'worker failed validation' --resolution-type refund",
    "  agenc-runtime market tui",
    "  agenc-runtime market skills list --query swap --tags defi",
    "  agenc-runtime market skills purchase <skillPda>",
    "  agenc-runtime market governance vote <proposalPda> yes",
    "  agenc-runtime market disputes resolve <disputePda> --arbiter-votes vote1:arbiter1,vote2:arbiter2",
    "  agenc-runtime market reputation summary",
    "  agenc-runtime market reputation delegate 250 --delegatee-agent-pda <agentPda> --expires-at 1760000000",
    "  agenc-runtime skill list",
    "  agenc-runtime skill info my-skill",
    "  agenc-runtime skill validate",
    "  agenc-runtime skill create my-new-skill",
    "  agenc-runtime skill install ./path/to/skill.md",
    "  agenc-runtime skill uninstall my-skill",
    "  agenc-runtime skill enable my-skill",
    "  agenc-runtime skill disable my-skill",
    '  agenc-runtime skill search "defi swap" --tags defi,swap --limit 5',
    "  agenc-runtime skill registry-install my-skill-id",
    "  agenc-runtime skill publish ./skills/my-skill.md --tags defi --price 1000000",
    '  agenc-runtime skill rate my-skill-id 5 --review "Great skill!"',
    "  agenc-runtime skill verify my-skill-id --path ./local-skill.md",
    "  agenc-runtime skill import-openclaw ./openclaw-skill.md",
  ].join("\n");
}

export function parseArgv(argv: string[]): ParsedArgv {
  const positional: string[] = [];
  const flags: Record<string, string | number | boolean> = {};

  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (token === "--") {
      positional.push(...argv.slice(index + 1));
      break;
    }

    if (!token.startsWith("-")) {
      positional.push(token);
      continue;
    }

    if (token === "-") {
      positional.push(token);
      continue;
    }

    if (token === "-h") {
      flags.h = true;
      continue;
    }

    if (!token.startsWith("--")) {
      // Single short option not in scope (keep deterministic error path by treating as positional for now)
      positional.push(token);
      continue;
    }

    const body = token.slice(2);
    if (!body) {
      continue;
    }

    const parts = body.split("=", 2);
    const rawName = parts[0];
    const rawValue = parts[1];
    if (parts.length === 2) {
      flags[rawName] = parseStringValue(rawValue);
      continue;
    }

    const next = argv[index + 1];
    if (next !== undefined && !next.startsWith("-")) {
      flags[rawName] = parseStringValue(next);
      index += 1;
      continue;
    }

    flags[rawName] = true;
  }

  return { positional, flags };
}

function parseStringValue(raw: string): string | number | boolean {
  const lowered = raw.toLowerCase();
  if (lowered === "true") return true;
  if (lowered === "false") return false;
  if (/^-?\d+$/.test(raw) && raw.length <= 15) {
    return Number.parseInt(raw, 10);
  }
  return raw;
}
