import type { KeybindingAction, KeybindingContextName } from "../keybindings/types.js";

export const WORKBENCH_CONTEXTS = [
  "Workbench",
  "Explorer",
  "Surface",
  "Agents",
  "Composer",
] as const satisfies readonly KeybindingContextName[];

export const WORKBENCH_ACTIONS = [
  "workbench:focusExplorer",
  "workbench:focusSurface",
  "workbench:focusAgents",
  "workbench:focusComposer",
  "workbench:focusUp",
  "workbench:focusNext",
  "workbench:closeSurface",
  "workbench:openDiff",
  "workbench:openSearch",
  "explorer:up",
  "explorer:down",
  "explorer:top",
  "explorer:bottom",
  "explorer:expand",
  "explorer:collapse",
  "explorer:open",
  "explorer:openKeepFocus",
  "explorer:attach",
  "explorer:revealActive",
  "surface:up",
  "surface:down",
  "surface:pageUp",
  "surface:pageDown",
  "surface:top",
  "surface:bottom",
  "surface:open",
  "surface:openKeepFocus",
  "surface:attach",
  "surface:attachAll",
  "surface:groupUp",
  "surface:groupDown",
  "surface:accept",
  "surface:reject",
  "surface:stop",
  "agents:up",
  "agents:down",
  "agents:open",
  "agents:stop",
] as const satisfies readonly KeybindingAction[];
