import type { KeybindingAction, KeybindingContextName } from "../keybindings/types.js";

export const WORKBENCH_CONTEXTS = [
  "Workbench",
  "Explorer",
  "Surface",
  "Buffer",
  "Agents",
  "Composer",
] as const satisfies readonly KeybindingContextName[];

export const WORKBENCH_ACTIONS = [
  "workbench:focusExplorer",
  "workbench:focusSurface",
  "workbench:focusAgents",
  "workbench:focusComposer",
  "workbench:focusUp",
  "workbench:focusNext",
  "workbench:closeSurface",
  "workbench:openDiff",
  "workbench:openSearch",
  "explorer:up",
  "explorer:down",
  "explorer:top",
  "explorer:bottom",
  "explorer:expand",
  "explorer:collapse",
  "explorer:open",
  "explorer:openKeepFocus",
  "explorer:edit",
  "explorer:editKeepFocus",
  "explorer:attach",
  "explorer:revealActive",
  "surface:up",
  "surface:down",
  "surface:pageUp",
  "surface:pageDown",
  "surface:top",
  "surface:bottom",
  "surface:open",
  "surface:openKeepFocus",
  "surface:edit",
  "surface:attach",
  "surface:attachAll",
  "surface:groupUp",
  "surface:groupDown",
  "surface:accept",
  "surface:reject",
  "surface:stop",
  "buffer:save",
  "buffer:revert",
  "buffer:close",
  "buffer:closeDiscard",
  "buffer:undo",
  "buffer:redo",
  "buffer:hover",
  "buffer:definition",
  "buffer:up",
  "buffer:down",
  "buffer:left",
  "buffer:right",
  "buffer:pageUp",
  "buffer:pageDown",
  "buffer:lineStart",
  "buffer:lineEnd",
  "buffer:top",
  "buffer:bottom",
  "buffer:selectUp",
  "buffer:selectDown",
  "buffer:selectLeft",
  "buffer:selectRight",
  "buffer:selectLineStart",
  "buffer:selectLineEnd",
  "agents:up",
  "agents:down",
  "agents:open",
  "agents:stop",
] as const satisfies readonly KeybindingAction[];
