/** Regenerate only after reviewing migration changes and running parity tests. */
import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import Database from "better-sqlite3";
import { build } from "esbuild";
import { applyMigrations } from "../src/state/sqlite-driver.js";
import { STATE_DB_MIGRATIONS } from "../src/state/migrations/index.js";
import { freshStateArtifactPath, freshStateManifestPath, sha256 } from "./fresh-state-schema-artifact.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const identifier = (value: string) => `"${value.replaceAll('"', '""')}"`;
const seedTables = new Set([
  "schema_migrations", "csv_storage_quota", "csv_job_supervisor_state",
  "workflow_handoff_quota_global", "workflow_handoff_sequence",
]);
const expressions: Record<string, string> = {
  "csv_storage_quota.updated_at": "CAST(strftime('%s', 'now') AS INTEGER)",
  "csv_job_supervisor_state.updated_at_ms": "CAST(strftime('%s', 'now') AS INTEGER) * 1000",
};
const literal = (value: unknown): string => {
  if (value === null) return "NULL";
  if (typeof value === "string") return `'${value.replaceAll("'", "''")}'`;
  if (typeof value === "number" && Number.isSafeInteger(value)) return String(value);
  throw new Error("Review new seed value type before regenerating fresh state");
};

const db = new Database(":memory:");
let sql: string;
try {
  db.pragma("foreign_keys = ON");
  // Always execute the unchanged legacy runner, never openStateDatabases or the
  // fast path being generated. Custom apply functions are part of this oracle.
  applyMigrations(db, STATE_DB_MIGRATIONS);
  const schema = db.prepare<[], { type: string; name: string; sql: string | null }>(
    "SELECT type, name, sql FROM sqlite_schema ORDER BY type, name",
  ).all();
  const seeds: string[] = [];
  for (const table of schema.filter((row) => row.type === "table")) {
    const rows = db.prepare(`SELECT * FROM ${identifier(table.name)}`).all() as Record<string, unknown>[];
    if (rows.length > 0 && !seedTables.has(table.name)) {
      throw new Error(`Review new seed table ${table.name} before regenerating fresh state`);
    }
    for (const row of rows) {
      const columns = Object.keys(row).filter((column) => table.name !== "schema_migrations" || column !== "applied_at");
      seeds.push(`INSERT INTO ${identifier(table.name)} (${columns.map(identifier).join(", ")})\nVALUES (${columns.map((column) => expressions[`${table.name}.${column}`] ?? literal(row[column])).join(", ")});`);
    }
  }
  const statements = (type: string) => schema.filter((row) =>
    row.type === type && row.sql !== null && !row.name.startsWith("sqlite_"),
  ).map((row) => `${row.sql};`);
  sql = [
    ...statements("table"), ...statements("index"), ...seeds,
    ...statements("view"), ...statements("trigger"),
  ].join("\n\n") + "\n";
} finally {
  db.close();
}

const escaped = sql.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");
const artifact = `// Generated by npm run generate:fresh-state-schema. Do not edit by hand.\n` +
  `// The build verifies migration inputs; parity tests verify the legacy result.\n` +
  `export const FRESH_STATE_MIGRATIONS = ${JSON.stringify(STATE_DB_MIGRATIONS.map(({ version, name }) => ({ version, name })), null, 2)} as const;\n\n` +
  `export const FRESH_STATE_SCHEMA_SQL = \`\n${escaped}\`;\n`;

// Bundle only the registry to capture all value dependencies that can affect
// generated SQL, including constants and helpers outside migrations/. Type-only
// migration sources are also pinned so changes cannot evade the build gate.
const graph = await build({
  absWorkingDir: root, entryPoints: ["src/state/migrations/index.ts"],
  bundle: true, packages: "external", platform: "node", format: "esm",
  write: false, metafile: true, logLevel: "silent",
});
const inputs = new Set(Object.keys(graph.metafile!.inputs).map((path) => relative(root, resolve(root, path))));
for (const name of await readdir(resolve(root, "src/state/migrations"))) {
  if (name.endsWith(".ts")) inputs.add(`src/state/migrations/${name}`);
}
inputs.add("scripts/generate-fresh-state-schema.ts");
inputs.add("scripts/fresh-state-schema-artifact.mjs");
const sources = Object.fromEntries(await Promise.all([...inputs].sort().map(async (path) => {
  if (path.startsWith("..") || path.includes("node_modules")) throw new Error(`Unexpected migration source ${path}`);
  return [path, sha256(await readFile(resolve(root, path)))];
})));
await writeFile(resolve(root, freshStateArtifactPath), artifact);
await writeFile(resolve(root, freshStateManifestPath), JSON.stringify({
  format: 1, artifactSha256: sha256(artifact), sources,
}, null, 2) + "\n");
console.log(`Generated fresh state schema from ${STATE_DB_MIGRATIONS.length} canonical migrations (${inputs.size} source commitments).`);
